# -*- coding: utf-8 -*-
"""TC bổ sung UC1 Danh sách gói cước (CMS admin) — chức năng Cài đặt bảng và Bộ lọc.

Nguồn: 8 ảnh chụp màn hình thực tế màn Quản lý gói cước (vt-cms) — popup Cài đặt bảng (đầu/cuối danh sách),
tab Bộ lọc mặc định, dropdown Chu kỳ / Loại hình gói / Trạng thái / Kênh phân phối, trạng thái đã chọn Web OA.
SRS chưa mô tả 2 chức năng này (TC-15 ghi chú "Chưa có popup", TC-99 ghi chú "Cần bổ sung thêm TC cài đặt bảng
và bộ lọc") -> rule không nhìn thấy trên UI đều gắn "Cần BA confirm".
Khuôn format: sheet "CMS-Quản lý gói cước" (cột A..G), chèn vào UC1 sau nhóm "Phân trang".

ROWS:
  ('S', 'Tên nhóm')                 -> dòng nhóm (merge A:F) như "Phân trang"
  ('P', 'Pre-condition: ...')       -> dòng điều kiện tiên quyết (merge A:G)
  ('T', chức_năng|None, mục_đích, các_bước, kết_quả, ghi_chú[, khoá])
        khoá: tên ngắn để sheet "Kỹ thuật thiết kế TC" tham chiếu ID thật qua {khoá}
"""

BA = 'Cần BA confirm'

ROWS = [
    # =====================================================================
    ('S', 'Cài đặt bảng (ẩn/hiện cột)'),
    ('P', 'Pre-condition: \nBước 1, 2: Như Pre-condition UC1\n'
          'Bước 3: Click button Cài đặt bảng → hiển thị popup Cài đặt bảng'),

    ('T', 'Button Cài đặt bảng',
     'Kiểm tra trạng thái button Cài đặt bảng khi popup đang mở',
     '1. Kiểm tra button Cài đặt bảng',
     '1. Button ở trạng thái active: viền, icon bánh răng và text "Cài đặt bảng" chuyển màu đỏ theo design',
     'Theo UI thực tế - Kỹ thuật: Sơ đồ chuyển trạng thái (Đóng → Mở)', 'cdb_active'),
    ('T', None,
     'Kiểm tra click lại button Cài đặt bảng khi popup đang mở',
     '1. Click button Cài đặt bảng',
     '1. \n- Đóng popup Cài đặt bảng, không lưu thay đổi chưa Cập nhật\n- Button trở về trạng thái mặc định: viền xám, text đen',
     f'Kỹ thuật: Sơ đồ chuyển trạng thái - {BA} hành vi bật/tắt khi click lại button', 'cdb_toggle'),
    ('T', None,
     'Kiểm tra click liên tục nhiều lần button Cài đặt bảng',
     'ĐK: Popup Cài đặt bảng đang đóng\n1. Click liên tiếp nhanh button Cài đặt bảng 5 lần',
     '1. Popup đóng/mở theo số lần click (lần lẻ mở, lần chẵn đóng), không mở nhiều popup chồng nhau, không vỡ giao diện',
     '', None),

    ('T', 'Popup Cài đặt bảng - Giao diện',
     'Kiểm tra giao diện popup Cài đặt bảng',
     '1. Kiểm tra popup Cài đặt bảng',
     '1. Hiển thị popup dạng dropdown ngay dưới button Cài đặt bảng gồm:\n'
     '+ Checkbox "Chọn tất cả"\n'
     '+ Danh sách checkbox các cột: Mã gói, Chu kỳ, Giá gốc (VNĐ), Kênh bán, Loại hình, Gia hạn tự động, Trạng thái, Thời gian cập nhật, Người cập nhật\n'
     '+ Button "Cập nhật" nền đen ở cuối popup',
     'Theo UI thực tế', 'cdb_ui'),
    ('T', None,
     'Kiểm tra thứ tự các option cột trong popup',
     '1. Đối chiếu thứ tự các option trong popup với thứ tự cột trên header bảng',
     '1. Thứ tự option trùng thứ tự cột trên bảng từ trái qua phải: Mã gói → Chu kỳ → Giá gốc (VNĐ) → Kênh bán → Loại hình → Gia hạn tự động → Trạng thái → Thời gian cập nhật → Người cập nhật',
     '', None),
    ('T', None,
     'Kiểm tra cột Thao tác không nằm trong danh sách cấu hình',
     '1. Cuộn hết danh sách option trong popup',
     '1. Không có option "Thao tác" → cột Thao tác luôn hiển thị, không cho phép ẩn',
     f'Suy ra từ UI thực tế (popup không có option Thao tác) - {BA} cột Thao tác là cột cố định', 'cdb_thaotac'),
    ('T', None,
     'Kiểm tra giá trị mặc định của popup khi chưa từng cấu hình',
     'ĐK: Tài khoản chưa từng cập nhật Cài đặt bảng\n1. Kiểm tra trạng thái các checkbox',
     '1. "Chọn tất cả" và 9 option cột đều ở trạng thái được chọn (checkbox đỏ có dấu tick); bảng hiển thị đủ 9 cột + cột Thao tác',
     'Theo UI thực tế', 'cdb_default'),
    ('T', None,
     'Kiểm tra cuộn danh sách option trong popup',
     '1. Cuộn chuột xuống trong vùng danh sách option',
     '1. \n- Danh sách cuộn dọc, hiển thị thanh cuộn bên phải popup\n- Cuộn xuống hiển thị đến option cuối "Người cập nhật", dòng "Chọn tất cả" cuộn khuất phía trên\n- Button "Cập nhật" luôn cố định cuối popup, không cuộn theo danh sách',
     'Theo UI thực tế (ảnh popup đầu/cuối danh sách)', None),
    ('T', None,
     'Kiểm tra hiệu ứng khi di chuột qua option',
     '1. Di chuột qua từng option trong popup',
     '1. Option đang được trỏ chuột hiển thị nền xám, con trỏ dạng bàn tay',
     'Theo UI thực tế', None),
    ('T', None,
     'Kiểm tra popup hiển thị nổi trên bảng danh sách',
     '1. Kiểm tra vị trí popup so với bảng danh sách',
     '1. Popup nổi đè lên bảng danh sách, không đẩy/xô lệch bảng và thanh công cụ',
     '', None),

    ('T', 'Checkbox Chọn tất cả',
     'Kiểm tra bỏ chọn "Chọn tất cả" khi tất cả cột đang được chọn',
     'ĐK: Tất cả option đang được chọn\n1. Click bỏ chọn checkbox "Chọn tất cả"',
     '1. Toàn bộ 9 option cột chuyển sang trạng thái bỏ chọn',
     'Kỹ thuật: Bảng quyết định', 'cdb_all_off'),
    ('T', None,
     'Kiểm tra chọn "Chọn tất cả" khi đang bỏ chọn một số cột',
     'ĐK: Đang bỏ chọn cột Chu kỳ và Kênh bán\n1. Click chọn checkbox "Chọn tất cả"',
     '1. Toàn bộ 9 option cột được chọn',
     'Kỹ thuật: Bảng quyết định', 'cdb_all_on'),
    ('T', None,
     'Kiểm tra trạng thái "Chọn tất cả" khi bỏ chọn 1 cột',
     'ĐK: Tất cả option đang được chọn\n1. Bỏ chọn option "Chu kỳ"',
     '1. Checkbox "Chọn tất cả" tự động bỏ tick (hoặc hiển thị trạng thái chọn một phần theo design)',
     f'Kỹ thuật: Bảng quyết định - {BA} có hiển thị trạng thái chọn một phần (indeterminate) không', 'cdb_partial'),
    ('T', None,
     'Kiểm tra "Chọn tất cả" tự động được chọn khi tick đủ các cột',
     'ĐK: Chỉ còn option "Chu kỳ" chưa được chọn\n1. Tick option "Chu kỳ"',
     '1. Checkbox "Chọn tất cả" tự động được tick',
     'Kỹ thuật: Bảng quyết định', 'cdb_auto_all'),
    ('T', None,
     'Kiểm tra click vào text tên cột thay vì ô checkbox',
     '1. Click vào text "Kênh bán" trong popup',
     '1. Checkbox của option Kênh bán đổi trạng thái chọn/bỏ chọn',
     f'{BA} vùng click của option', None),

    ('T', 'Button Cập nhật',
     'Kiểm tra ẩn 1 cột',
     '1. Bỏ chọn option "Gia hạn tự động"\n2. Click button Cập nhật',
     '2. \n- Đóng popup Cài đặt bảng\n- Bảng con của tất cả loại gói không còn cột Gia hạn tự động\n- Các cột còn lại giữ đúng thứ tự và dữ liệu',
     'Kỹ thuật: Phân tích giá trị biên (8/9 cột)', 'cdb_hide1'),
    ('T', None,
     'Kiểm tra ẩn nhiều cột',
     '1. Bỏ chọn option "Chu kỳ", "Giá gốc (VNĐ)", "Người cập nhật"\n2. Click button Cập nhật',
     '2. Bảng ẩn đúng 3 cột đã bỏ chọn; các cột còn lại và cột Thao tác hiển thị đúng thứ tự, đúng dữ liệu',
     'Kỹ thuật: Phân vùng tương đương', 'cdb_hideN'),
    ('T', None,
     'Kiểm tra hiển thị lại cột đã ẩn',
     'ĐK: Cột Chu kỳ đang bị ẩn\n1. Tick option "Chu kỳ"\n2. Click button Cập nhật',
     '2. Cột Chu kỳ hiển thị lại đúng vị trí ban đầu (sau cột Mã gói), dữ liệu hiển thị đúng',
     'Kỹ thuật: Sơ đồ chuyển trạng thái (Ẩn → Hiện)', 'cdb_show'),
    ('T', None,
     'Kiểm tra popup hiển thị đúng cấu hình đang áp dụng khi mở lại',
     'ĐK: Đã ẩn cột Kênh bán, Loại hình và click Cập nhật\n1. Click button Cài đặt bảng mở lại popup\n2. Kiểm tra các checkbox',
     '2. Option Kênh bán, Loại hình bỏ chọn; các option còn lại được chọn; "Chọn tất cả" bỏ chọn',
     '', None),
    ('T', None,
     'Kiểm tra ẩn cột Mã gói (cột đầu tiên của bảng)',
     '1. Bỏ chọn option "Mã gói"\n2. Click button Cập nhật',
     '2. \n- Bảng con bắt đầu từ cột Chu kỳ\n- Dòng cha Loại gói cước (tên loại gói, badge, loại dịch vụ) hiển thị bình thường, không vỡ layout',
     f'{BA} có cho phép ẩn cột định danh Mã gói không', 'cdb_hide_ma'),
    ('T', None,
     'Kiểm tra click Cập nhật khi không thay đổi option nào',
     '1. Không thay đổi checkbox nào\n2. Click button Cập nhật',
     '2. Đóng popup, bảng giữ nguyên các cột đang hiển thị',
     '', None),
    ('T', None,
     'Kiểm tra click liên tục nhiều lần button Cập nhật',
     '1. Bỏ chọn option "Trạng thái"\n2. Click liên tiếp nhanh button Cập nhật',
     '2. Cấu hình chỉ được áp dụng 1 lần, cột Trạng thái bị ẩn, không lỗi giao diện',
     '', None),
    ('T', None,
     'Kiểm tra bỏ chọn tất cả cột (0 cột hiển thị)',
     '1. Bỏ chọn checkbox "Chọn tất cả"\n2. Kiểm tra button Cập nhật\n3. Click button Cập nhật',
     '2. Button Cập nhật bị disable\n3. Không cho phép lưu cấu hình bảng không có cột dữ liệu nào',
     f'Kỹ thuật: Phân tích giá trị biên (0 cột) - Ảnh màn hình chưa thể hiện - {BA} (tham chiếu sheet CMS-CTKM: bỏ chọn tất cả → button disable)', 'cdb_zero'),
    ('T', None,
     'Kiểm tra chỉ giữ lại 1 cột hiển thị',
     '1. Bỏ chọn "Chọn tất cả"\n2. Tick option "Mã gói"\n3. Click button Cập nhật',
     '3. Bảng con chỉ hiển thị cột Mã gói và cột Thao tác, bảng giãn đủ chiều rộng, không có thanh cuộn ngang thừa',
     'Kỹ thuật: Phân tích giá trị biên (1 cột)', 'cdb_one'),
    ('T', None,
     'Kiểm tra bảng không còn cuộn ngang khi ẩn bớt cột',
     'ĐK: Bảng đang hiển thị đủ 9 cột và có thanh cuộn ngang\n1. Bỏ chọn Kênh bán, Loại hình, Gia hạn tự động, Người cập nhật\n2. Click button Cập nhật',
     '2. \n- Các cột còn lại giãn theo chiều rộng bảng, không còn thanh cuộn ngang\n- Cột Thao tác vẫn hiển thị bên phải',
     '', None),

    ('T', 'Đóng popup không lưu',
     'Kiểm tra click ra ngoài popup sau khi thay đổi option',
     '1. Bỏ chọn option "Chu kỳ"\n2. Click vào vùng trống ngoài popup\n3. Click button Cài đặt bảng mở lại popup',
     '2. Đóng popup, huỷ thay đổi: cột Chu kỳ vẫn hiển thị trên bảng\n3. Option Chu kỳ vẫn ở trạng thái được chọn',
     f'Kỹ thuật: Sơ đồ chuyển trạng thái (Đang chỉnh → Huỷ) - {BA} (tham chiếu sheet CMS-CTKM: click ra ngoài → huỷ thao tác)', 'cdb_outside'),
    ('T', None,
     'Kiểm tra nhấn phím Esc khi popup đang mở',
     '1. Bỏ chọn option "Kênh bán"\n2. Nhấn phím Esc',
     '2. Đóng popup, không lưu thay đổi, cột Kênh bán vẫn hiển thị',
     f'{BA}', 'cdb_esc'),
    ('T', None,
     'Kiểm tra click icon Bộ lọc khi popup Cài đặt bảng đang mở',
     '1. Bỏ chọn option "Loại hình"\n2. Click icon Bộ lọc',
     '2. \n- Popup Cài đặt bảng đóng, không lưu thay đổi chưa Cập nhật (cột Loại hình vẫn hiển thị)\n- Mở tab Bộ lọc',
     f'{BA}', 'cdb_to_filter'),

    ('T', 'Lưu cấu hình Cài đặt bảng',
     'Kiểm tra cấu hình cột sau khi tải lại trang',
     'ĐK: Đã ẩn cột Người cập nhật và click Cập nhật\n1. Nhấn F5 tải lại trang',
     '1. Cấu hình được giữ nguyên: cột Người cập nhật vẫn bị ẩn',
     f'Ảnh màn hình không thể hiện cơ chế lưu - {BA} cấu hình lưu theo tài khoản / theo trình duyệt / reset khi tải lại', 'cdb_f5'),
    ('T', None,
     'Kiểm tra cấu hình cột khi chuyển sang màn khác rồi quay lại',
     'ĐK: Đã ẩn cột Kênh bán và click Cập nhật\n1. Click menu Quản lý loại gói cước\n2. Click lại menu Quản lý gói cước',
     '2. Cột Kênh bán vẫn bị ẩn',
     f'{BA}', None),
    ('T', None,
     'Kiểm tra cấu hình cột sau khi đăng xuất và đăng nhập lại',
     'ĐK: Đã ẩn cột Giá gốc (VNĐ) và click Cập nhật\n1. Đăng xuất\n2. Đăng nhập lại cùng tài khoản, vào màn Quản lý gói cước',
     '2. Cột Giá gốc (VNĐ) vẫn bị ẩn',
     f'{BA}', None),
    ('T', None,
     'Kiểm tra cấu hình của tài khoản này không ảnh hưởng tài khoản khác',
     'ĐK: Admin A đã ẩn cột Trạng thái\n1. Đăng nhập Admin B trên trình duyệt khác\n2. Vào màn Quản lý gói cước',
     '2. Admin B vẫn thấy đủ 9 cột theo cấu hình của Admin B',
     f'{BA}', None),
    ('T', None,
     'Kiểm tra cấu hình bảng không ảnh hưởng màn hình khác',
     'ĐK: Đã ẩn cột Trạng thái tại màn Quản lý gói cước\n1. Mở màn Quản lý loại gói cước, Chương trình khuyến mãi',
     '1. Bảng danh sách của các màn khác không bị ảnh hưởng',
     '', None),
    ('T', None,
     'Kiểm tra cấu hình cột giữ nguyên khi chuyển trang và đổi số dòng/trang',
     'ĐK: Đã ẩn cột Giá gốc (VNĐ)\n1. Click trang 2\n2. Chọn 20 dòng',
     '1. Trang 2 không hiển thị cột Giá gốc (VNĐ)\n2. Danh sách tải lại vẫn không hiển thị cột Giá gốc (VNĐ)',
     '', None),
    ('T', None,
     'Kiểm tra cấu hình áp dụng cho loại gói được mở rộng sau khi cập nhật',
     'ĐK: Các dòng cha đang thu gọn\n1. Bỏ chọn Kênh bán, click Cập nhật\n2. Click mở rộng 1 loại gói cước',
     '2. Bảng con vừa mở rộng không có cột Kênh bán',
     '', None),
    ('T', None,
     'Kiểm tra ẩn cột đang được sắp xếp',
     'ĐK: Bảng con đang sắp xếp theo Giá gốc tăng dần\n1. Bỏ chọn Giá gốc (VNĐ), click Cập nhật\n2. Kiểm tra thứ tự danh sách',
     '2. Cột Giá gốc (VNĐ) bị ẩn; thứ tự gói cước giữ nguyên theo Giá gốc tăng dần, không lỗi',
     f'{BA} giữ hay reset thứ tự sắp xếp khi ẩn cột đang sort', None),

    # =====================================================================
    ('S', 'Bộ lọc'),
    ('P', 'Pre-condition: \nBước 1, 2: Như Pre-condition UC1\n'
          'Bước 3: Click icon Bộ lọc → hiển thị tab Bộ lọc bên phải màn hình'),

    ('T', 'Icon Bộ lọc',
     'Kiểm tra trạng thái icon Bộ lọc khi tab Bộ lọc đang mở',
     '1. Kiểm tra icon Bộ lọc',
     '1. Icon phễu lọc và viền button chuyển màu đỏ (active) theo design',
     'Theo UI thực tế - Kỹ thuật: Sơ đồ chuyển trạng thái (Đóng → Mở)', 'bl_active'),
    ('T', None,
     'Kiểm tra click icon Bộ lọc khi tab Bộ lọc đang mở',
     '1. Click icon Bộ lọc',
     '1. \n- Đóng tab Bộ lọc\n- Icon trở về màu đen\n- Vùng danh sách giãn lại đủ chiều rộng ban đầu',
     'Kỹ thuật: Sơ đồ chuyển trạng thái (Mở → Đóng) - tham chiếu sheet CMS-CTKM', 'bl_close'),
    ('T', None,
     'Kiểm tra bố cục màn hình khi mở tab Bộ lọc',
     '1. Kiểm tra bố cục màn hình',
     '1. \n- Tab Bộ lọc hiển thị cố định bên phải màn hình\n- Thanh công cụ (button Thêm gói cước, Xuất file excel, Cài đặt bảng, icon Bộ lọc) và bảng danh sách thu hẹp tương ứng, không bị che, không vỡ layout\n- Bảng danh sách hiển thị thanh cuộn ngang, cột Thao tác cố định bên phải',
     'Theo UI thực tế', None),
    ('T', None,
     'Kiểm tra click liên tục nhiều lần icon Bộ lọc',
     '1. Click liên tiếp nhanh icon Bộ lọc 5 lần',
     '1. Tab Bộ lọc đóng/mở theo số lần click, không hiển thị nhiều tab chồng nhau, không vỡ layout',
     '', None),

    ('T', 'Tab Bộ lọc - Giao diện',
     'Kiểm tra giao diện tab Bộ lọc',
     '1. Kiểm tra tab Bộ lọc',
     '1. Hiển thị giống design gồm:\n+ Tiêu đề "Bộ lọc" màu đỏ\n+ Link "Xoá lọc" màu xanh góc phải\n+ 4 trường chọn: Chu kỳ, Loại hình gói, Trạng thái, Kênh phân phối\n+ Button "Áp dụng" ở cuối tab',
     'Theo UI thực tế. Lưu ý: tên bộ lọc "Kênh phân phối", "Loại hình gói" khác tên cột "Kênh bán", "Loại hình" trên bảng', 'bl_ui'),
    ('T', None,
     'Kiểm tra giá trị mặc định của tab Bộ lọc',
     '1. Kiểm tra các trường lọc và button Áp dụng',
     '1. \n- 4 trường lọc để trống, hiển thị placeholder đúng tên trường, icon mũi tên hướng xuống\n- Button "Áp dụng" bị disable (nền xám)',
     'Theo UI thực tế - Kỹ thuật: Bảng quyết định (R1: chưa chọn giá trị)', 'bl_default'),
    ('T', None,
     'Kiểm tra mở dropdown trường lọc',
     '1. Click trường Chu kỳ',
     '1. \n- Viền trường đậm, mũi tên đổi hướng lên\n- Hiển thị danh sách bên dưới gồm ô "Tìm kiếm" (icon kính lúp) và các option kèm checkbox chưa chọn',
     'Theo UI thực tế', None),
    ('T', None,
     'Kiểm tra chỉ mở 1 dropdown tại một thời điểm',
     'ĐK: Dropdown Chu kỳ đang mở\n1. Click trường Loại hình gói',
     '1. Dropdown Chu kỳ đóng, dropdown Loại hình gói mở',
     'Theo UI thực tế', None),
    ('T', None,
     'Kiểm tra dropdown không đóng sau khi chọn 1 option',
     '1. Click trường Kênh phân phối\n2. Tick option "Web OA"',
     '2. Dropdown vẫn mở để chọn tiếp option khác (chọn nhiều)',
     'Theo UI thực tế', None),
    ('T', None,
     'Kiểm tra đóng dropdown khi click lại trường hoặc click ra ngoài',
     'ĐK: Dropdown Chu kỳ đang mở, đã tick "Ngày"\n1. Click lại trường Chu kỳ\n2. Mở lại dropdown, click vùng trống trong tab Bộ lọc',
     '1. Dropdown đóng, giữ nguyên giá trị "Ngày" đã chọn\n2. Dropdown đóng, giữ nguyên giá trị đã chọn',
     '', None),

    ('T', 'Trường Chu kỳ',
     'Kiểm tra danh sách option trường Chu kỳ',
     '1. Click trường Chu kỳ',
     '1. Hiển thị 4 option: Ngày, Tuần, Tháng, Năm',
     'Theo UI thực tế - Kỹ thuật: Phân vùng tương đương (đơn vị chu kỳ)', 'ck_list'),
    ('T', None,
     'Kiểm tra hiển thị khi chọn 1 giá trị',
     '1. Click trường Chu kỳ\n2. Tick option "Ngày"',
     '2. \n- Checkbox "Ngày" chuyển đỏ có dấu tick, dòng option có nền xám\n- Trường hiển thị nhãn nhỏ "Chu kỳ" phía trên và chip "Ngày ×"\n- Button "Áp dụng" enable (nền đỏ)',
     'Theo UI thực tế (ảnh chọn Web OA) - Kỹ thuật: Bảng quyết định (R2)', 'ck_select1'),
    ('T', None,
     'Kiểm tra lọc Chu kỳ = Ngày',
     'ĐK: Có gói chu kỳ 14 ngày, 2 tuần, 12 tháng, 1 năm\n1. Chọn Chu kỳ = Ngày\n2. Click Áp dụng',
     '2. Chỉ hiển thị gói có đơn vị chu kỳ Ngày (14 ngày); không hiển thị gói 2 tuần, 12 tháng, 1 năm',
     'Kỹ thuật: Phân vùng tương đương', 'ck_ngay'),
    ('T', None,
     'Kiểm tra lọc Chu kỳ = Tuần',
     'ĐK: Có gói chu kỳ 14 ngày, 2 tuần, 12 tháng, 1 năm\n1. Chọn Chu kỳ = Tuần\n2. Click Áp dụng',
     '2. Chỉ hiển thị gói 2 tuần; không hiển thị gói 14 ngày dù cùng 14 ngày quy đổi',
     f'Kỹ thuật: Phân vùng tương đương - {BA} lọc theo đơn vị đã lưu, không quy đổi (khớp TC-61)', 'ck_tuan'),
    ('T', None,
     'Kiểm tra lọc Chu kỳ = Tháng',
     'ĐK: Có gói chu kỳ 14 ngày, 2 tuần, 12 tháng, 1 năm\n1. Chọn Chu kỳ = Tháng\n2. Click Áp dụng',
     '2. Chỉ hiển thị gói 12 tháng; không hiển thị gói 1 năm',
     'Kỹ thuật: Phân vùng tương đương', 'ck_thang'),
    ('T', None,
     'Kiểm tra lọc Chu kỳ = Năm',
     'ĐK: Có gói chu kỳ 14 ngày, 2 tuần, 12 tháng, 1 năm\n1. Chọn Chu kỳ = Năm\n2. Click Áp dụng',
     '2. Chỉ hiển thị gói 1 năm',
     'Kỹ thuật: Phân vùng tương đương', 'ck_nam'),
    ('T', None,
     'Kiểm tra lọc chọn nhiều giá trị Chu kỳ',
     'ĐK: Có gói chu kỳ 14 ngày, 2 tuần, 12 tháng, 1 năm\n1. Chọn Chu kỳ = Ngày và Tháng\n2. Click Áp dụng',
     '2. Hiển thị gói có đơn vị Ngày hoặc Tháng (14 ngày, 12 tháng); không hiển thị gói 2 tuần, 1 năm',
     f'Kỹ thuật: Bảng quyết định (R3: nhiều giá trị trong 1 trường = HOẶC) - {BA}', 'ck_multi'),
    ('T', None,
     'Kiểm tra lọc chọn tất cả giá trị Chu kỳ',
     '1. Chọn đủ 4 giá trị Ngày, Tuần, Tháng, Năm\n2. Click Áp dụng',
     '2. Kết quả giống danh sách khi không lọc theo Chu kỳ (tổng số kết quả không đổi)',
     'Kỹ thuật: Phân tích giá trị biên (chọn tối đa 4/4 option)', 'ck_all'),
    ('T', None,
     'Kiểm tra bỏ chọn bằng cách click lại option đã chọn',
     'ĐK: Chỉ đang chọn Chu kỳ = Ngày\n1. Click lại option "Ngày"',
     '1. \n- Checkbox "Ngày" bỏ tick, chip "Ngày" biến mất, trường về placeholder "Chu kỳ"\n- Button "Áp dụng" disable trở lại',
     'Kỹ thuật: Bảng quyết định (quay về R1)', 'ck_untick'),
    ('T', None,
     'Kiểm tra xoá giá trị bằng icon × trên chip',
     'ĐK: Đang chọn Chu kỳ = Ngày và Tháng\n1. Click icon × trên chip "Ngày"',
     '1. Chip "Ngày" bị xoá, checkbox "Ngày" bỏ tick; chip "Tháng" giữ nguyên',
     'Theo UI thực tế (chip có icon ×)', 'ck_chip_x'),

    ('T', 'Ô Tìm kiếm trong dropdown',
     'Kiểm tra hiển thị mặc định ô Tìm kiếm',
     '1. Click trường Trạng thái\n2. Kiểm tra ô tìm kiếm',
     '2. Ô tìm kiếm để trống, có icon kính lúp và placeholder "Tìm kiếm"; hiển thị đủ option bên dưới',
     'Theo UI thực tế - Áp dụng tương tự cho cả 4 trường lọc', None),
    ('T', None,
     'Kiểm tra tìm kiếm đúng tên option',
     '1. Mở dropdown Chu kỳ\n2. Nhập "Tháng" vào ô Tìm kiếm',
     '2. Danh sách chỉ còn option "Tháng"',
     'Kỹ thuật: Phân vùng tương đương (khớp toàn bộ)', 'tk_full'),
    ('T', None,
     'Kiểm tra tìm kiếm theo một phần tên option',
     '1. Mở dropdown Trạng thái\n2. Nhập "kinh doanh"',
     '2. Danh sách còn 2 option: "Đang kinh doanh", "Ngừng kinh doanh"',
     'Kỹ thuật: Phân vùng tương đương (khớp một phần)', 'tk_part'),
    ('T', None,
     'Kiểm tra tìm kiếm không phân biệt chữ hoa, chữ thường',
     '1. Mở dropdown Kênh phân phối\n2. Nhập "WEB OA"',
     '2. Hiển thị option "Web OA"',
     'Kỹ thuật: Phân vùng tương đương', None),
    ('T', None,
     'Kiểm tra tìm kiếm tiếng Việt không dấu',
     '1. Mở dropdown Trạng thái\n2. Nhập "nhap"',
     '2. Hiển thị option "Nháp"',
     f'{BA} có hỗ trợ tìm không dấu không', None),
    ('T', None,
     'Kiểm tra tìm kiếm không có kết quả',
     '1. Mở dropdown Loại hình gói\n2. Nhập "abcxyz"',
     '2. Không hiển thị option nào, hiển thị thông báo không có dữ liệu theo design',
     f'Kỹ thuật: Phân vùng tương đương (không khớp) - {BA} nội dung thông báo', 'tk_none'),
    ('T', None,
     'Kiểm tra nhập khoảng trắng đầu/cuối hoặc toàn khoảng trắng',
     '1. Mở dropdown Chu kỳ\n2. Nhập "  Ngày  "\n3. Xoá, nhập toàn ký tự khoảng trắng',
     '2. Tự trim khoảng trắng đầu/cuối, hiển thị option "Ngày"\n3. Hiển thị đủ 4 option như khi để trống',
     '', None),
    ('T', None,
     'Kiểm tra nhập ký tự đặc biệt, mã script',
     '1. Mở dropdown Chu kỳ\n2. Nhập "@#$%^&*" \n3. Nhập "<script>alert(1)</script>"',
     '2. Không có kết quả, không lỗi\n3. Không thực thi script, hiển thị dạng text, không có kết quả',
     '', None),
    ('T', None,
     'Kiểm tra giữ giá trị đã chọn khi tìm kiếm trong dropdown',
     'ĐK: Đã tick Trạng thái = Nháp\n1. Nhập "kinh doanh" vào ô Tìm kiếm\n2. Tick "Đang kinh doanh"\n3. Xoá từ khoá tìm kiếm',
     '3. Hiển thị lại đủ 4 option; "Nháp" và "Đang kinh doanh" đều đang được tick; trường hiển thị 2 chip tương ứng',
     '', 'tk_keep'),
    ('T', None,
     'Kiểm tra ô Tìm kiếm khi đóng rồi mở lại dropdown',
     'ĐK: Đã nhập "Tháng" vào ô Tìm kiếm của dropdown Chu kỳ\n1. Đóng dropdown\n2. Mở lại dropdown Chu kỳ',
     '2. Ô tìm kiếm được xoá trắng, hiển thị đủ 4 option',
     f'{BA}', None),

    ('T', 'Trường Loại hình gói',
     'Kiểm tra danh sách option trường Loại hình gói',
     '1. Click trường Loại hình gói',
     '1. Hiển thị 3 option: Nền, Chính, Add-on',
     f'Theo UI thực tế - {BA}: bộ lọc có "Nền" nhưng cột Loại hình (TC-66) chỉ mô tả Chính / Add-on', 'lh_list'),
    ('T', None,
     'Kiểm tra lọc Loại hình gói = Chính',
     'ĐK: Có gói loại hình Chính và Add-on\n1. Chọn Loại hình gói = Chính\n2. Click Áp dụng',
     '2. Chỉ hiển thị gói có cột Loại hình = Chính',
     'Kỹ thuật: Phân vùng tương đương', 'lh_chinh'),
    ('T', None,
     'Kiểm tra lọc Loại hình gói = Add-on',
     'ĐK: Có gói loại hình Chính và Add-on\n1. Chọn Loại hình gói = Add-on\n2. Click Áp dụng',
     '2. Chỉ hiển thị gói có cột Loại hình = Add-on',
     'Kỹ thuật: Phân vùng tương đương', 'lh_addon'),
    ('T', None,
     'Kiểm tra lọc Loại hình gói = Nền',
     '1. Chọn Loại hình gói = Nền\n2. Click Áp dụng',
     '2. Chỉ hiển thị gói loại hình Nền; nếu chưa có gói Nền hiển thị "Danh sách trống"',
     f'Kỹ thuật: Phân vùng tương đương - {BA} nghiệp vụ loại hình Nền', 'lh_nen'),
    ('T', None,
     'Kiểm tra lọc chọn nhiều giá trị Loại hình gói',
     '1. Chọn Loại hình gói = Chính và Add-on\n2. Click Áp dụng',
     '2. Hiển thị gói có loại hình Chính hoặc Add-on',
     'Kỹ thuật: Bảng quyết định (R3)', None),

    ('T', 'Trường Trạng thái',
     'Kiểm tra danh sách option trường Trạng thái',
     '1. Click trường Trạng thái',
     '1. Hiển thị 4 option: Nháp, Đã phát hành, Đang kinh doanh, Ngừng kinh doanh; không có option "Đã xoá"',
     'Theo UI thực tế - Kỹ thuật: Phân vùng tương đương (trạng thái gói, khớp TC-46)', 'tt_list'),
    ('T', None,
     'Kiểm tra lọc Trạng thái = Nháp',
     'ĐK: Có gói ở cả 4 trạng thái\n1. Chọn Trạng thái = Nháp\n2. Click Áp dụng',
     '2. Chỉ hiển thị gói có status pill "Nháp"',
     'Kỹ thuật: Phân vùng tương đương', 'tt_nhap'),
    ('T', None,
     'Kiểm tra lọc Trạng thái = Đã phát hành',
     'ĐK: Có gói ở cả 4 trạng thái\n1. Chọn Trạng thái = Đã phát hành\n2. Click Áp dụng',
     '2. Chỉ hiển thị gói có status pill "Đã phát hành"',
     'Kỹ thuật: Phân vùng tương đương', 'tt_ph'),
    ('T', None,
     'Kiểm tra lọc Trạng thái = Đang kinh doanh',
     'ĐK: Có gói ở cả 4 trạng thái\n1. Chọn Trạng thái = Đang kinh doanh\n2. Click Áp dụng',
     '2. Chỉ hiển thị gói có status pill "Đang kinh doanh"',
     'Kỹ thuật: Phân vùng tương đương', 'tt_dkd'),
    ('T', None,
     'Kiểm tra lọc Trạng thái = Ngừng kinh doanh',
     'ĐK: Có gói ở cả 4 trạng thái\n1. Chọn Trạng thái = Ngừng kinh doanh\n2. Click Áp dụng',
     '2. Chỉ hiển thị gói có status pill "Ngừng kinh doanh"',
     'Kỹ thuật: Phân vùng tương đương', 'tt_nkd'),
    ('T', None,
     'Kiểm tra lọc chọn nhiều giá trị Trạng thái',
     '1. Chọn Trạng thái = Nháp và Đang kinh doanh\n2. Click Áp dụng',
     '2. Hiển thị gói ở trạng thái Nháp hoặc Đang kinh doanh; không hiển thị Đã phát hành, Ngừng kinh doanh',
     'Kỹ thuật: Bảng quyết định (R3)', None),
    ('T', None,
     'Kiểm tra hiển thị khi chọn nhiều chip vượt chiều rộng trường',
     '1. Chọn đủ 4 giá trị Trạng thái\n2. Kiểm tra hiển thị trường Trạng thái',
     '2. Các chip tự xuống dòng hoặc thu gọn dạng "+N" theo design, không tràn ra ngoài tab Bộ lọc, không che trường Kênh phân phối',
     f'Kỹ thuật: Phân tích giá trị biên (4/4 option, text dài nhất) - {BA} cách hiển thị', 'tt_overflow'),
    ('T', None,
     'Kiểm tra kết quả lọc Trạng thái sau khi gói tự động chuyển trạng thái',
     'ĐK: Gói X Đã phát hành, Bật/tắt trạng thái = Tự động, thời gian bắt đầu = hiện tại + 2 phút\n1. Lọc Trạng thái = Đã phát hành → có gói X\n2. Chờ qua thời gian bắt đầu\n3. Click Áp dụng lại',
     '3. Gói X không còn trong kết quả lọc Đã phát hành; lọc Đang kinh doanh thì có gói X',
     'Kỹ thuật: Sơ đồ chuyển trạng thái gói (Đã phát hành → Đang kinh doanh), liên quan TC-71', None),

    ('T', 'Trường Kênh phân phối',
     'Kiểm tra danh sách option trường Kênh phân phối',
     '1. Click trường Kênh phân phối',
     '1. Hiển thị 2 option: Web OA, Miniapp Tammi',
     f'Theo UI thực tế - {BA}: option "Miniapp Tammi" khác giá trị cột Kênh bán "Mini app gói cước"', 'kp_list'),
    ('T', None,
     'Kiểm tra lọc Kênh phân phối = Web OA',
     'ĐK: Có gói chỉ bán Web OA, gói chỉ bán Mini app, gói bán cả 2 kênh\n1. Chọn Kênh phân phối = Web OA\n2. Click Áp dụng',
     '2. Hiển thị gói chỉ bán Web OA và gói bán cả 2 kênh; không hiển thị gói chỉ bán Mini app',
     'Kỹ thuật: Phân vùng tương đương', 'kp_web'),
    ('T', None,
     'Kiểm tra lọc Kênh phân phối = Miniapp Tammi',
     'ĐK: Có gói chỉ bán Web OA, gói chỉ bán Mini app, gói bán cả 2 kênh\n1. Chọn Kênh phân phối = Miniapp Tammi\n2. Click Áp dụng',
     '2. Hiển thị gói chỉ bán Mini app và gói bán cả 2 kênh; không hiển thị gói chỉ bán Web OA',
     'Kỹ thuật: Phân vùng tương đương', 'kp_mini'),
    ('T', None,
     'Kiểm tra lọc chọn cả 2 Kênh phân phối',
     'ĐK: Có gói chỉ bán Web OA, gói chỉ bán Mini app, gói bán cả 2 kênh\n1. Chọn Web OA và Miniapp Tammi\n2. Click Áp dụng',
     '2. Hiển thị cả 3 nhóm gói (gói có ít nhất 1 trong 2 kênh)',
     f'Kỹ thuật: Bảng quyết định (R3) - {BA} điều kiện HOẶC hay gói phải có đủ cả 2 kênh', 'kp_both'),

    ('T', 'Kết hợp nhiều trường lọc',
     'Kiểm tra lọc kết hợp 2 trường',
     'ĐK: Có gói 12 tháng Nháp, 12 tháng Đang kinh doanh, 14 ngày Nháp\n1. Chọn Chu kỳ = Tháng, Trạng thái = Nháp\n2. Click Áp dụng',
     '2. Chỉ hiển thị gói thoả cả 2 điều kiện (12 tháng Nháp)',
     'Kỹ thuật: Bảng quyết định (R4: nhiều trường = VÀ)', 'kh_2'),
    ('T', None,
     'Kiểm tra lọc kết hợp đủ 4 trường',
     '1. Chọn Chu kỳ = Ngày, Loại hình gói = Chính, Trạng thái = Nháp, Kênh phân phối = Web OA\n2. Click Áp dụng',
     '2. Chỉ hiển thị gói thoả đồng thời cả 4 điều kiện',
     'Kỹ thuật: Bảng quyết định (R4)', 'kh_4'),
    ('T', None,
     'Kiểm tra lọc kết hợp không có bản ghi thoả mãn',
     'ĐK: Không có gói nào chu kỳ Năm ở trạng thái Ngừng kinh doanh\n1. Chọn Chu kỳ = Năm, Trạng thái = Ngừng kinh doanh\n2. Click Áp dụng',
     '2. Không hiển thị bảng dữ liệu, hiển thị text "Danh sách trống"; phân trang không có trang nào',
     'Kỹ thuật: Bảng quyết định (R6) - text theo TC-18', 'kh_empty'),

    ('T', 'Button Áp dụng',
     'Kiểm tra hiển thị danh sách nhóm Cha - Con sau khi Áp dụng',
     'ĐK: Loại gói A có gói Nháp và Đang kinh doanh, loại gói B chỉ có gói Đang kinh doanh\n1. Chọn Trạng thái = Nháp\n2. Click Áp dụng\n3. Mở rộng các dòng cha',
     '3. \n- Chỉ hiển thị dòng cha loại gói A (loại gói có ít nhất 1 gói thoả điều kiện), không hiển thị loại gói B\n- Bảng con loại gói A chỉ chứa gói Nháp',
     f'{BA}: loại gói không có gói thoả điều kiện có bị ẩn không; badge hiển thị tổng số gói hay số gói sau lọc', 'ad_group'),
    ('T', None,
     'Kiểm tra phân trang và text tổng số kết quả sau khi Áp dụng',
     'ĐK: Đang ở trang 3, danh sách 48 kết quả\n1. Chọn Trạng thái = Nháp\n2. Click Áp dụng',
     '2. \n- Danh sách tự động quay về trang 1\n- Text chân trang cập nhật theo kết quả lọc: "Hiển thị 1–x trong tổng số y kết quả"\n- Dãy số trang tính lại theo kết quả lọc',
     'Kỹ thuật: Phân tích giá trị biên (trang 1) - liên quan TC-86', 'ad_paging'),
    ('T', None,
     'Kiểm tra chọn giá trị nhưng chưa click Áp dụng',
     '1. Chọn Chu kỳ = Ngày\n2. Không click Áp dụng, kiểm tra danh sách',
     '2. Danh sách không thay đổi; chỉ lọc khi click button Áp dụng',
     'Kỹ thuật: Sơ đồ chuyển trạng thái (Đã chọn, chưa áp dụng)', 'ad_noapply'),
    ('T', None,
     'Kiểm tra thay đổi điều kiện sau khi đã Áp dụng',
     'ĐK: Đang áp dụng lọc Chu kỳ = Ngày\n1. Đổi thành Chu kỳ = Tháng (chưa Áp dụng)\n2. Click Áp dụng',
     '1. Danh sách vẫn giữ kết quả lọc Ngày\n2. Danh sách cập nhật theo Chu kỳ = Tháng',
     'Kỹ thuật: Sơ đồ chuyển trạng thái (Đã áp dụng → Đã chọn → Đã áp dụng)', 'ad_change'),
    ('T', None,
     'Kiểm tra trạng thái tab Bộ lọc sau khi click Áp dụng',
     '1. Chọn Trạng thái = Nháp\n2. Click Áp dụng',
     '2. Tab Bộ lọc vẫn mở, giữ nguyên giá trị đã chọn trên các trường',
     f'{BA} tab Bộ lọc giữ mở hay tự đóng sau Áp dụng', None),
    ('T', None,
     'Kiểm tra click liên tục nhiều lần button Áp dụng',
     '1. Chọn Trạng thái = Nháp\n2. Click liên tiếp nhanh button Áp dụng',
     '2. Danh sách chỉ hiển thị 1 kết quả lọc đúng, không nhân đôi dữ liệu, không lỗi',
     '', None),

    ('T', 'Link Xoá lọc',
     'Kiểm tra click Xoá lọc khi chưa chọn giá trị nào',
     '1. Click link "Xoá lọc"',
     '1. Không có thay đổi, danh sách giữ nguyên, button Áp dụng vẫn disable',
     'Kỹ thuật: Sơ đồ chuyển trạng thái', None),
    ('T', None,
     'Kiểm tra click Xoá lọc khi đã chọn nhưng chưa Áp dụng',
     '1. Chọn Chu kỳ = Ngày, Trạng thái = Nháp\n2. Click link "Xoá lọc"',
     '2. \n- 4 trường lọc trở về trống\n- Button Áp dụng disable\n- Danh sách không thay đổi',
     'Kỹ thuật: Sơ đồ chuyển trạng thái (Đã chọn → Mặc định)', 'xl_notapplied'),
    ('T', None,
     'Kiểm tra click Xoá lọc khi đang áp dụng bộ lọc',
     'ĐK: Đang áp dụng lọc Trạng thái = Nháp\n1. Click link "Xoá lọc"',
     '1. \n- 4 trường lọc trở về trống, button Áp dụng disable\n- Danh sách tự động hiển thị lại đầy đủ như mặc định, về trang 1',
     f'Kỹ thuật: Sơ đồ chuyển trạng thái (Đã áp dụng → Mặc định) - {BA} xoá lọc có tự tải lại danh sách không', 'xl_applied'),

    ('T', 'Đóng/mở tab và lưu điều kiện lọc',
     'Kiểm tra đóng tab Bộ lọc khi đang áp dụng lọc',
     'ĐK: Đang áp dụng lọc Chu kỳ = Tháng\n1. Click icon Bộ lọc đóng tab\n2. Click icon Bộ lọc mở lại tab',
     '1. Danh sách vẫn giữ kết quả lọc Chu kỳ = Tháng\n2. Trường Chu kỳ hiển thị đúng giá trị "Tháng" đã áp dụng',
     f'{BA}', 'ot_applied'),
    ('T', None,
     'Kiểm tra đóng tab Bộ lọc khi đã chọn nhưng chưa Áp dụng',
     '1. Chọn Trạng thái = Nháp (chưa Áp dụng)\n2. Click icon Bộ lọc đóng tab\n3. Mở lại tab Bộ lọc',
     '2. Danh sách không thay đổi\n3. Trường Trạng thái trống (giá trị chưa áp dụng bị huỷ)',
     f'{BA}', 'ot_notapplied'),
    ('T', None,
     'Kiểm tra tải lại trang khi đang áp dụng lọc',
     'ĐK: Đang áp dụng lọc Trạng thái = Nháp\n1. Nhấn F5',
     '1. Xoá điều kiện lọc, hiển thị danh sách mặc định, tab Bộ lọc đóng',
     f'{BA} (tham chiếu sheet CMS-CTKM: reload page → xoá điều kiện và kết quả tìm kiếm)', 'ot_f5'),
    ('T', None,
     'Kiểm tra điều kiện lọc khi chuyển sang màn khác rồi quay lại',
     'ĐK: Đang áp dụng lọc Trạng thái = Nháp\n1. Click menu Quản lý loại gói cước\n2. Click lại menu Quản lý gói cước',
     '2. Hiển thị danh sách mặc định, không giữ điều kiện lọc',
     f'{BA}', None),
    ('T', None,
     'Kiểm tra điều kiện lọc sau khi xem chi tiết gói rồi quay lại',
     'ĐK: Đang áp dụng lọc Trạng thái = Nháp\n1. Click icon (i) tại 1 gói cước\n2. Click Back về danh sách',
     '2. Danh sách vẫn giữ điều kiện lọc Trạng thái = Nháp',
     f'{BA}', None),

    # =====================================================================
    ('S', 'Kết hợp Bộ lọc - Tìm kiếm - Sắp xếp - Phân trang - Cài đặt bảng'),
    ('T', 'Bộ lọc + Ô tìm kiếm',
     'Kiểm tra lọc kết hợp từ khoá ô tìm kiếm',
     'ĐK: Có gói "HOAI1" Nháp và "HOAI3" Đang kinh doanh\n1. Nhập "HOAI" vào ô tìm kiếm\n2. Mở tab Bộ lọc, chọn Trạng thái = Nháp, click Áp dụng',
     '2. Chỉ hiển thị gói thoả cả từ khoá "HOAI" và Trạng thái = Nháp (HOAI1)',
     'Kỹ thuật: Bảng quyết định (R5: từ khoá VÀ bộ lọc)', 'cb_search'),
    ('T', None,
     'Kiểm tra nhập từ khoá tìm kiếm khi đang áp dụng lọc',
     'ĐK: Đang áp dụng lọc Trạng thái = Nháp\n1. Nhập "HOAI1" vào ô tìm kiếm',
     '1. Tìm kiếm trong phạm vi kết quả lọc, điều kiện lọc vẫn giữ nguyên',
     'Kỹ thuật: Bảng quyết định (R5)', None),
    ('T', None,
     'Kiểm tra Xoá lọc không xoá từ khoá ô tìm kiếm',
     'ĐK: Đang có từ khoá "HOAI" và lọc Trạng thái = Nháp\n1. Click link "Xoá lọc"',
     '1. Chỉ xoá điều kiện lọc; ô tìm kiếm vẫn giữ "HOAI", danh sách hiển thị theo từ khoá',
     f'{BA}', None),
    ('T', 'Bộ lọc + Sắp xếp',
     'Kiểm tra sắp xếp cột trong kết quả lọc',
     'ĐK: Đang áp dụng lọc Trạng thái = Nháp\n1. Mở rộng 1 loại gói\n2. Click icon ⇅ tại cột Giá gốc',
     '2. Chỉ các gói Nháp được sắp xếp theo giá tăng dần, không xuất hiện gói trạng thái khác',
     'Liên quan TC-53', None),
    ('T', 'Bộ lọc + Phân trang',
     'Kiểm tra chuyển trang khi đang áp dụng lọc',
     'ĐK: Kết quả lọc nhiều hơn 10 loại gói cước\n1. Click trang 2',
     '1. Trang 2 hiển thị tiếp kết quả lọc, điều kiện lọc giữ nguyên',
     '', None),
    ('T', None,
     'Kiểm tra đổi số dòng/trang khi đang áp dụng lọc',
     'ĐK: Đang áp dụng lọc Trạng thái = Nháp\n1. Chọn 20 dòng',
     '1. Danh sách về trang 1, hiển thị tối đa 20 loại gói cước thoả điều kiện lọc; điều kiện lọc giữ nguyên',
     'Liên quan TC-84', None),
    ('T', 'Bộ lọc + Cài đặt bảng',
     'Kiểm tra lọc theo trường có cột đang bị ẩn',
     'ĐK: Đã ẩn cột Trạng thái tại Cài đặt bảng\n1. Chọn Trạng thái = Nháp\n2. Click Áp dụng',
     '2. Danh sách vẫn lọc đúng các gói Nháp dù cột Trạng thái không hiển thị',
     '', 'cb_hidden'),
    ('T', None,
     'Kiểm tra tìm kiếm khi cột Mã gói đang bị ẩn',
     'ĐK: Đã ẩn cột Mã gói tại Cài đặt bảng\n1. Nhập mã gói "HOAI2" vào ô tìm kiếm',
     '1. Vẫn tìm thấy gói HOAI2 (dữ liệu tìm kiếm không phụ thuộc cột hiển thị)',
     '', None),
    ('T', None,
     'Kiểm tra cấu hình cột giữ nguyên khi áp dụng và xoá lọc',
     'ĐK: Đã ẩn cột Kênh bán\n1. Lọc Trạng thái = Nháp, click Áp dụng\n2. Click "Xoá lọc"',
     '1., 2. Cột Kênh bán vẫn bị ẩn',
     '', None),
    ('T', 'Bộ lọc + Xuất file excel',
     'Kiểm tra Xuất file excel khi đang lọc và đang ẩn cột',
     'ĐK: Đang lọc Trạng thái = Nháp, đã ẩn cột Kênh bán\n1. Click button Xuất file excel',
     '1. File xuất theo điều kiện lọc đang áp dụng (không chỉ trang đang xem)',
     f'Tính năng Xuất excel đang phát triển (TC-13) → chấm N/A - {BA} có xuất theo cột đang hiển thị không', None),

    ('T', 'Ngoại lệ & phi chức năng',
     'Kiểm tra click Áp dụng khi mất kết nối mạng',
     '1. Chọn Trạng thái = Nháp\n2. Ngắt kết nối mạng\n3. Click Áp dụng',
     '3. Hiển thị toast "Thất bại. Vui lòng kiểm tra lại kết nối.", giữ nguyên danh sách và giá trị đã chọn',
     'Toast theo TC-94', None),
    ('T', None,
     'Kiểm tra click Áp dụng khi API lọc lỗi hệ thống',
     'ĐK: API danh sách trả lỗi 500\n1. Chọn Trạng thái = Nháp\n2. Click Áp dụng',
     '2. Hiển thị toast "Hệ thống bận. Vui lòng thử lại sau." kèm mã lỗi tương ứng, cho phép thử lại',
     'Toast theo TC-96', None),
    ('T', None,
     'Kiểm tra tham số gửi lên API khi Áp dụng',
     '1. Mở DevTools > Network\n2. Chọn Chu kỳ = Ngày, Trạng thái = Nháp, Đang kinh doanh\n3. Click Áp dụng',
     '3. Request API danh sách gửi đúng tham số lọc (chu kỳ = Ngày; trạng thái = Nháp, Đang kinh doanh), trang = 1',
     'Bổ sung tên API và tên tham số sau khi dev cung cấp', None),
    ('T', None,
     'Kiểm tra kết quả lọc khớp với CSDL',
     '1. Áp dụng lọc Chu kỳ = Tháng, Loại hình gói = Chính\n2. Đối chiếu kết quả với truy vấn DB cùng điều kiện (loại trừ gói Đã xoá)',
     '2. Số lượng và danh sách gói hiển thị khớp kết quả truy vấn DB',
     '', None),
    ('T', None,
     'Kiểm tra thời gian phản hồi khi Áp dụng lọc',
     'ĐK: Có ≥ 100 loại gói cước\n1. Chọn đủ 4 trường lọc\n2. Click Áp dụng, đo thời gian phản hồi API',
     '2. API phản hồi < 500ms',
     'Ngưỡng theo TC-99', None),
    ('T', None,
     'Kiểm tra giao diện tab Bộ lọc và popup Cài đặt bảng khi thu nhỏ, phóng to',
     '1. Mở tab Bộ lọc\n2. Nhấn Ctrl - và Ctrl +\n3. Mở popup Cài đặt bảng, nhấn Ctrl - và Ctrl +',
     '2., 3. Tab Bộ lọc, popup Cài đặt bảng co giãn tương ứng, không vỡ layout, button Áp dụng / Cập nhật luôn nhìn thấy và thao tác được',
     '', None),
    ('T', None,
     'Kiểm tra thao tác bàn phím trong tab Bộ lọc',
     '1. Mở tab Bộ lọc\n2. Nhấn Tab liên tục',
     '2. Con trỏ di chuyển lần lượt: Xoá lọc → Chu kỳ → Loại hình gói → Trạng thái → Kênh phân phối → Áp dụng (khi enable)',
     '', None),
]

TECHNIQUES = [
    {
        'title': '1. PHÂN VÙNG TƯƠNG ĐƯƠNG - Giá trị các trường Bộ lọc',
        'header': ['Trường lọc', 'Lớp tương đương (option)', 'Giá trị đại diện / dữ liệu', 'Lớp không hợp lệ / ngoài phạm vi', 'TC'],
        'rows': [
            ['Chu kỳ', 'Ngày | Tuần | Tháng | Năm', '14 ngày · 2 tuần · 12 tháng · 1 năm (lọc theo đơn vị đã lưu, không quy đổi)',
             'Gói Đã xoá (không hiển thị)', '{ck_ngay}, {ck_tuan}, {ck_thang}, {ck_nam}'],
            ['Loại hình gói', 'Nền | Chính | Add-on', 'Gói Chính, gói Add-on, gói Nền', '-', '{lh_chinh}, {lh_addon}, {lh_nen}'],
            ['Trạng thái', 'Nháp | Đã phát hành | Đang kinh doanh | Ngừng kinh doanh', '1 gói mỗi trạng thái',
             'Đã xoá - không có trong option', '{tt_list}, {tt_nhap}, {tt_ph}, {tt_dkd}, {tt_nkd}'],
            ['Kênh phân phối', 'Web OA | Miniapp Tammi', 'Gói chỉ Web OA · chỉ Mini app · cả 2 kênh', '-', '{kp_web}, {kp_mini}, {kp_both}'],
            ['Ô Tìm kiếm trong dropdown', 'Khớp toàn bộ | Khớp một phần | Không khớp',
             '"Tháng" · "kinh doanh" · "abcxyz"', 'Ký tự đặc biệt, script, toàn khoảng trắng', '{tk_full}, {tk_part}, {tk_none}'],
        ],
    },
    {
        'title': '2. BẢNG QUYẾT ĐỊNH - Kết quả khi Áp dụng Bộ lọc',
        'header': ['Điều kiện / Kết quả', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6'],
        'rows': [
            ['Số trường có giá trị', '0', '1', '1', '≥ 2', '≥ 1', '≥ 1'],
            ['Số giá trị trong 1 trường', '0', '1', '≥ 2', '≥ 1', '≥ 1', '≥ 1'],
            ['Có từ khoá ô tìm kiếm', '-', 'Không', 'Không', 'Không', 'Có', '-'],
            ['Có bản ghi thoả mãn', '-', 'Có', 'Có', 'Có', 'Có', 'Không'],
            ['Button Áp dụng', 'Disable', 'Enable', 'Enable', 'Enable', 'Enable', 'Enable'],
            ['Kết quả', 'Danh sách mặc định', 'Gói = giá trị đã chọn', 'Gói thuộc 1 trong các giá trị (HOẶC)',
             'Gói thoả mọi trường (VÀ)', 'Gói thoả từ khoá VÀ bộ lọc', '"Danh sách trống"'],
            ['TC', '{bl_default}', '{ck_select1}, {ck_ngay}', '{ck_multi}, {kp_both}', '{kh_2}, {kh_4}', '{cb_search}', '{kh_empty}'],
        ],
    },
    {
        'title': '3. BẢNG QUYẾT ĐỊNH - Checkbox "Chọn tất cả" trong popup Cài đặt bảng',
        'header': ['Trạng thái trước', 'Thao tác', 'Kết quả 9 option cột', 'Kết quả "Chọn tất cả"', 'Button Cập nhật', 'TC'],
        'rows': [
            ['9/9 cột chọn', 'Bỏ tick "Chọn tất cả"', 'Bỏ chọn cả 9', 'Bỏ tick', 'Disable', '{cdb_all_off}, {cdb_zero}'],
            ['Chọn một phần', 'Tick "Chọn tất cả"', 'Chọn cả 9', 'Tick', 'Enable', '{cdb_all_on}'],
            ['9/9 cột chọn', 'Bỏ tick 1 cột', '8/9 chọn', 'Bỏ tick / chọn một phần', 'Enable', '{cdb_partial}'],
            ['8/9 cột chọn', 'Tick cột còn thiếu', '9/9 chọn', 'Tự động tick', 'Enable', '{cdb_auto_all}'],
        ],
    },
    {
        'title': '4. PHÂN TÍCH GIÁ TRỊ BIÊN',
        'header': ['Ràng buộc', 'Biên dưới', 'Trên biên dưới', 'Dưới biên trên', 'Biên trên', 'TC'],
        'rows': [
            ['Số cột hiển thị (Cài đặt bảng, tối đa 9)', '0 cột → không cho lưu', '1 cột', '8 cột', '9 cột (mặc định)',
             '{cdb_zero}, {cdb_one}, {cdb_hide1}, {cdb_default}'],
            ['Số option chọn trong trường Chu kỳ (tối đa 4)', '0 → Áp dụng disable', '1', '2', '4 → bằng không lọc',
             '{ck_untick}, {ck_ngay}, {ck_multi}, {ck_all}'],
            ['Số chip trên trường Trạng thái (tối đa 4, text dài)', '0', '1', '-', '4 → kiểm tra tràn', '{tt_overflow}'],
            ['Trang sau khi Áp dụng / Xoá lọc', 'Trang 1', '-', '-', '-', '{ad_paging}, {xl_applied}'],
        ],
    },
    {
        'title': '5. SƠ ĐỒ CHUYỂN TRẠNG THÁI - Popup Cài đặt bảng',
        'header': ['Trạng thái hiện tại', 'Sự kiện', 'Trạng thái kế tiếp', 'Thay đổi cột trên bảng', 'TC'],
        'rows': [
            ['Đóng', 'Click button Cài đặt bảng', 'Mở (button đỏ)', '-', '{cdb_active}'],
            ['Mở / Đang chỉnh', 'Click Cập nhật', 'Đóng', 'Áp dụng cấu hình', '{cdb_hide1}, {cdb_show}'],
            ['Đang chỉnh', 'Click ra ngoài popup', 'Đóng', 'Huỷ thay đổi', '{cdb_outside}'],
            ['Đang chỉnh', 'Nhấn Esc', 'Đóng', 'Huỷ thay đổi', '{cdb_esc}'],
            ['Đang chỉnh', 'Click lại button Cài đặt bảng', 'Đóng', 'Huỷ thay đổi', '{cdb_toggle}'],
            ['Đang chỉnh', 'Click icon Bộ lọc', 'Đóng + mở tab Bộ lọc', 'Huỷ thay đổi', '{cdb_to_filter}'],
            ['Đã cập nhật', 'F5 tải lại trang', 'Đóng', 'Giữ cấu hình (BA confirm)', '{cdb_f5}'],
        ],
    },
    {
        'title': '6. SƠ ĐỒ CHUYỂN TRẠNG THÁI - Tab Bộ lọc',
        'header': ['Trạng thái hiện tại', 'Sự kiện', 'Trạng thái kế tiếp', 'Danh sách', 'TC'],
        'rows': [
            ['Đóng', 'Click icon Bộ lọc', 'Mở - mặc định (Áp dụng disable)', 'Không đổi', '{bl_active}, {bl_default}'],
            ['Mở - mặc định', 'Chọn ≥ 1 giá trị', 'Đã chọn - chưa áp dụng', 'Không đổi', '{ck_select1}, {ad_noapply}'],
            ['Đã chọn - chưa áp dụng', 'Click Áp dụng', 'Đã áp dụng', 'Lọc, về trang 1', '{ad_paging}'],
            ['Đã chọn - chưa áp dụng', 'Bỏ hết giá trị', 'Mở - mặc định', 'Không đổi', '{ck_untick}'],
            ['Đã chọn - chưa áp dụng', 'Click Xoá lọc', 'Mở - mặc định', 'Không đổi', '{xl_notapplied}'],
            ['Đã áp dụng', 'Đổi giá trị (chưa Áp dụng)', 'Đã chọn - chưa áp dụng', 'Giữ kết quả cũ', '{ad_change}'],
            ['Đã áp dụng', 'Click Xoá lọc', 'Mở - mặc định', 'Về danh sách mặc định', '{xl_applied}'],
            ['Đã áp dụng', 'Click icon Bộ lọc', 'Đóng (giữ lọc)', 'Giữ kết quả lọc', '{ot_applied}'],
            ['Đã chọn - chưa áp dụng', 'Click icon Bộ lọc', 'Đóng (huỷ giá trị chưa áp dụng)', 'Không đổi', '{ot_notapplied}'],
            ['Bất kỳ', 'F5 tải lại trang', 'Đóng - mặc định', 'Danh sách mặc định', '{ot_f5}'],
        ],
    },
    {
        'title': '7. ĐIỂM CẦN BA XÁC NHẬN (ảnh màn hình chưa thể hiện / SRS chưa mô tả)',
        'header': ['#', 'Nội dung', 'TC liên quan'],
        'rows': [
            ['1', 'Cột Thao tác là cột cố định, không cấu hình ẩn được? Có cho ẩn cột định danh Mã gói?', '{cdb_thaotac}, {cdb_hide_ma}'],
            ['2', 'Bỏ chọn tất cả cột: button Cập nhật disable hay báo lỗi?', '{cdb_zero}'],
            ['3', 'Click ra ngoài / Esc / click lại button khi đang chỉnh: huỷ thay đổi?', '{cdb_outside}, {cdb_esc}, {cdb_toggle}'],
            ['4', 'Cấu hình Cài đặt bảng lưu ở đâu (theo tài khoản / trình duyệt / reset khi F5)?', '{cdb_f5}'],
            ['5', '"Kênh phân phối" (Web OA, Miniapp Tammi) khác cột "Kênh bán" (Web OA, Mini app gói cước); "Loại hình gói" có "Nền" nhưng cột Loại hình chỉ Chính/Add-on', '{kp_list}, {lh_list}'],
            ['6', 'Nhiều giá trị trong 1 trường = HOẶC; nhiều trường = VÀ; Kênh phân phối chọn 2 kênh = HOẶC hay VÀ?', '{ck_multi}, {kp_both}, {kh_2}'],
            ['7', 'Sau lọc: loại gói không có gói thoả mãn có bị ẩn? Badge hiển thị tổng số gói hay số gói sau lọc?', '{ad_group}'],
            ['8', 'Xoá lọc có tự tải lại danh sách không cần Áp dụng? Có xoá từ khoá ô tìm kiếm không?', '{xl_applied}'],
            ['9', 'Đóng tab Bộ lọc: giữ điều kiện đã áp dụng, huỷ giá trị chưa áp dụng? F5 / chuyển màn có reset lọc?', '{ot_applied}, {ot_notapplied}, {ot_f5}'],
            ['10', 'Ô Tìm kiếm trong dropdown: hỗ trợ không dấu? Text khi không có kết quả?', '{tk_none}'],
            ['11', 'Chọn 4 chip Trạng thái: xuống dòng hay "+N"?', '{tt_overflow}'],
        ],
    },
]
