# -*- coding: utf-8 -*-
"""TC Quản lý gói cước (CMS admin) — UC1 Danh sách gói cước, UC2 Tạo mới gói cước.

Nguồn: SRS "Xây dựng module gói cước" - mục Qly gói cước (UC danh sách gói cước, UC2 tạo mới gói cước,
bảng Trạng thái gói cước) + ảnh design nhúng trong SRS (màn Quản lý gói cước, Tạo gói cước mới).
Khuôn format: sheet "Quanlykho" của file TC dự án.

ROWS:
  ('S', 'UCx: ...')        -> dòng UC (nền xanh, merge A:C)
  ('G', 'Tên nhóm')        -> dòng nhóm con (merge A:K)
  ('P', 'Pre-condition')   -> dòng điều kiện tiên quyết (merge A:M)
  ('T', chức_năng|None, mục_đích, các_bước, kết_quả, dữ_liệu, ghi_chú)
"""

BA = 'Cần BA confirm'
DT = 'Kỹ thuật: Bảng quyết định'
BVA = 'Kỹ thuật: Phân tích giá trị biên'
EP = 'Kỹ thuật: Phân vùng tương đương'
ST = 'Kỹ thuật: Sơ đồ chuyển trạng thái'

UI_OVERALL = ('1. Các label, có độ dài, rộng và khoảng cách bằng nhau, không xô lệch\n'
              '2. Các label sử dụng cùng 1 loại font, cỡ chữ, căn lề\n'
              '3. Kiểm tra tất cả lỗi về chính tả, cấu trúc câu, ngữ pháp trên màn hình\n'
              '4. Form được bố trí hợp lý và dễ sử dụng')

L1 = 'Mục QL gói cước - UC danh sách gói cước'
L2 = 'Mục QL gói cước - UC2 tạo mới gói cước'

ROWS = [
    # =====================================================================
    ('S', 'UC1: (CMS admin) Chức năng Xem danh sách gói cước'),
    ('P', 'Pre-condition: \nBước 1: Admin đăng nhập thành công vào hệ thống CMS, tài khoản có quyền xem phân hệ Gói cước\n'
          'Bước 2: Click menu Quản lý tính năng dịch vụ > Quản lý gói cước > Quản lý gói cước\n'),

    ('G', 'Kiểm tra gui UI/UX'),
    ('T', 'Kiểm tra UI', 'Kiểm tra hiển thị giao diện mặc định',
     '1. Kiểm tra hiển thị màn hình Quản lý gói cước',
     'Hiển thị màn hình giống design gồm:\n+ Tiêu đề: Quản lý gói cước\n+ Button Thêm gói cước\n+ Ô tìm kiếm\n'
     '+ Button Xuất file excel, Cài đặt bảng, icon Bộ lọc\n+ Bảng danh sách dạng nhóm Loại gói cước - Gói cước\n+ Vùng phân trang',
     '', L1 + ' - Mô tả giao diện'),
    ('T', None, 'Kiểm tra tổng thể giao diện màn hình',
     'Kiểm tra về bố cục, font chữ, chính tả, màu chữ', UI_OVERALL, '', ''),
    ('T', None, 'Kiểm tra thứ tự di chuyển trỏ trên màn hình khi nhấn phím Tab',
     'Nhấn Tab liên tục', 'Con trỏ di chuyển lần lượt theo thứ tự: Từ trái qua phải, từ trên xuống dưới', '', ''),
    ('T', None, 'Kiểm tra thứ tự con trỏ di chuyển ngược lại trên màn hình khi nhấn Shift-Tab',
     'Nhấn phím Shift-Tab liên tục', 'Con trỏ di chuyển ngược lại theo thứ tự: từ dưới lên trên, từ phải qua trái', '', ''),
    ('T', None, 'Kiểm tra giao diện khi thu nhỏ, phóng to',
     '1. Trên màn hình chức năng\n2. Nhấn tổ hợp phím Ctrl -\n3. Nhấn tổ hợp phím Ctrl +',
     'Màn hình thu nhỏ, phóng to tương ứng và không bị vỡ giao diện', '', ''),
    ('T', None, 'Kiểm tra hiển thị menu đang chọn trên sidebar',
     '1. Kiểm tra menu Quản lý gói cước trên sidebar',
     'Menu con Quản lý gói cước được highlight (đang chọn), nhóm menu Quản lý gói cước ở trạng thái mở rộng', '', L1 + ' - Trigger'),

    ('G', 'Vùng Tiêu đề & Thanh công cụ'),
    ('T', 'Tiêu đề trang', 'Kiểm tra text tiêu đề trang',
     '1. Kiểm tra tiêu đề màn hình', 'Hiển thị tiêu đề: Quản lý gói cước', '', L1 + ' STT 1'),
    ('T', 'Button Thêm gói cước', 'Kiểm tra hiển thị button Thêm gói cước',
     '1. Kiểm tra hiển thị button Thêm gói cước góc phải trên', 'Hiển thị button text "Thêm gói cước", trạng thái enable', '', L1 + ' STT 2'),
    ('T', None, 'Kiểm tra khi click button Thêm gói cước trên thanh công cụ',
     '1. Click button Thêm gói cước',
     '- Điều hướng đến màn Tạo gói cước mới\n- Trường Loại gói cước để trống, cho phép chọn loại gói',
     '', L1 + ' STT 2; ' + L2 + ' STT 13 Th2'),
    ('T', 'Ô tìm kiếm', 'Kiểm tra hiển thị mặc định ô tìm kiếm',
     '1. Kiểm tra ô tìm kiếm', 'Mặc định trống, hiển thị placeholder: "Tìm kiếm theo tên, mã gói cước"', '',
     L1 + ' STT 3. Design placeholder "Tìm kiếm theo tên, mã gói cước,..." - lệch dấu "...", ' + BA),
    ('T', None, 'Kiểm tra nhập dữ liệu vào ô tìm kiếm',
     '1. Nhập "OAPLUS" vào ô tìm kiếm', 'Cho phép nhập, hiển thị đúng dữ liệu vừa nhập', 'OAPLUS',
     'Chức năng tìm kiếm mô tả tại UC tìm kiếm riêng (SRS: "theo UC...") - chỉ test hiển thị/nhập liệu'),
    ('T', 'Button Xuất file excel', 'Kiểm tra hiển thị button Xuất file excel',
     '1. Kiểm tra button Xuất file excel', 'Hiển thị button viền, icon bảng tính màu xanh lá + text "Xuất file excel", trạng thái enable', '', L1 + ' STT 4'),
    ('T', None, 'Kiểm tra khi click button Xuất file excel',
     '1. Click button Xuất file excel', 'Thực hiện chức năng xuất file excel theo UC Xuất file excel', '',
     L1 + ' STT 4 - SRS chưa mô tả UC xuất excel, ' + BA),
    ('T', 'Button Cài đặt bảng', 'Kiểm tra hiển thị button Cài đặt bảng',
     '1. Kiểm tra button Cài đặt bảng', 'Hiển thị button viền, icon bánh răng + text "Cài đặt bảng", trạng thái enable', '', L1 + ' STT 5'),
    ('T', None, 'Kiểm tra khi click button Cài đặt bảng',
     '1. Click button Cài đặt bảng', 'Hiển thị popup cấu hình ẩn/hiện các cột dữ liệu của bảng danh sách gói cước', '',
     L1 + ' STT 5 - Chi tiết popup mô tả tại UC riêng'),
    ('T', 'Icon Bộ lọc', 'Kiểm tra hiển thị icon Bộ lọc',
     '1. Kiểm tra icon Bộ lọc', 'Hiển thị icon phễu lọc, trạng thái enable', '', L1 + ' STT 6'),
    ('T', None, 'Kiểm tra khi click icon Bộ lọc',
     '1. Click icon Bộ lọc', 'Mở tab bộ lọc', '', L1 + ' STT 6 - Chi tiết bộ lọc mô tả tại UC riêng'),

    ('G', 'Vùng danh sách - Dòng cha Loại gói cước'),
    ('T', 'Danh sách chưa có dữ liệu', 'Kiểm tra hiển thị khi hệ thống chưa có loại gói cước nào',
     'ĐK: Hệ thống chưa có loại gói cước nào (hoặc tất cả ở trạng thái Đã xoá)\n1. Truy cập màn hình Quản lý gói cước\n2. Kiểm tra vùng danh sách',
     'Không hiển thị bảng dữ liệu. Hiển thị text "Danh sách trống"', '', L1 + ' - Exception 2a, BR4'),
    ('T', 'Danh sách đã có dữ liệu', 'Kiểm tra hiển thị danh sách dạng nhóm Cha - Con',
     'ĐK: Hệ thống có loại gói cước và gói cước\n1. Truy cập màn hình Quản lý gói cước\n2. Kiểm tra vùng danh sách',
     'Hiển thị danh sách dạng nhóm: dòng cha là Loại gói cước, bên dưới là bảng con gói cước trực thuộc', '', L1 + ' BR_01'),
    ('T', 'Trạng thái Thu gọn/Mở rộng mặc định', 'Kiểm tra trạng thái mặc định của các dòng cha khi tải trang',
     '1. Truy cập màn hình Quản lý gói cước\n2. Kiểm tra các dòng Loại gói cước',
     '- Tất cả dòng cha ở trạng thái thu gọn, chỉ thấy dòng cha\n- Icon mũi tên hướng xuống ⌄',
     '', L1 + ' BR_02, STT 7. Ảnh design đang thể hiện trạng thái mở rộng - ' + BA),
    ('T', 'Nút Đóng / Mở rộng', 'Kiểm tra click mở rộng dòng cha đang thu gọn',
     'ĐK: Dòng cha đang thu gọn\n1. Click icon mũi tên ⌄ tại dòng Loại gói cước',
     '- Hiển thị bảng con danh sách gói cước thuộc loại gói đó\n- Icon đổi thành mũi tên hướng lên ⌃', '', L1 + ' STT 7 - ' + ST),
    ('T', None, 'Kiểm tra click thu gọn dòng cha đang mở rộng',
     'ĐK: Dòng cha đang mở rộng\n1. Click icon mũi tên ⌃ tại dòng Loại gói cước',
     '- Ẩn bảng con danh sách gói cước\n- Icon đổi thành mũi tên hướng xuống ⌄', '', L1 + ' STT 7 - ' + ST),
    ('T', None, 'Kiểm tra mở rộng đồng thời nhiều dòng cha',
     '1. Click mở rộng Loại gói A\n2. Click mở rộng Loại gói B',
     'Cả 2 dòng cha cùng mở rộng, mở dòng B không làm thu gọn dòng A', '', L1 + ' STT 7'),
    ('T', None, 'Kiểm tra mở rộng loại gói cước chưa có gói cước con',
     'ĐK: Loại gói cước chưa có gói cước nào (badge = 0)\n1. Click mở rộng dòng loại gói đó',
     '- Bảng con không có dòng gói cước nào\n- Vẫn hiển thị link "+ Thêm gói cước"', '',
     L1 + ' STT 7, 23 - SRS chưa mô tả hiển thị bảng con rỗng, ' + BA),
    ('T', None, 'Kiểm tra trạng thái thu gọn/mở rộng sau khi tải lại trang',
     'ĐK: Đang mở rộng 1 dòng cha\n1. Nhấn F5 tải lại trang',
     'Tất cả dòng cha trở về trạng thái thu gọn mặc định', '', L1 + ' BR_02'),
    ('T', 'Loại gói cước', 'Kiểm tra hiển thị tên loại gói cước trên dòng cha',
     '1. Kiểm tra thông tin tên loại gói trên dòng cha', 'Hiển thị "Tên loại gói: <Tên loại gói cước>" đúng dữ liệu đã tạo tại Quản lý loại gói cước', 'Plus OA Business',
     L1 + ' STT 8'),
    ('T', None, 'Kiểm tra dòng cha chỉ hiển thị loại gói cước khác trạng thái Đã xoá',
     'ĐK: Có loại gói A trạng thái Đang hoạt động, loại gói B trạng thái Đã xoá\n1. Kiểm tra danh sách dòng cha',
     '- Hiển thị loại gói A\n- Không hiển thị loại gói B', '', L1 + ' BR_01 - ' + EP),
    ('T', None, 'Kiểm tra loại gói cước vừa bị xoá biến mất khỏi danh sách',
     'ĐK: Loại gói A đang hiển thị\n1. Xoá loại gói A tại Quản lý loại gói cước\n2. Quay lại màn Quản lý gói cước',
     'Không còn hiển thị dòng cha loại gói A', '', L1 + ' BR_01 - ' + ST),
    ('T', None, 'Kiểm tra loại gói cước mới tạo hiển thị trên danh sách',
     '1. Tạo mới loại gói cước tại Quản lý loại gói cước\n2. Quay lại màn Quản lý gói cước',
     'Hiển thị dòng cha loại gói vừa tạo, badge số lượng = 0, đúng vị trí sắp xếp mặc định', '', L1 + ' BR_01'),
    ('T', None, 'Kiểm tra thứ tự hiển thị mặc định các dòng cha',
     'ĐK: Có nhiều loại gói cước thuộc loại dịch vụ khác nhau (OA, Meeting, Thiết bị)\n1. Kiểm tra thứ tự dòng cha',
     'Thứ tự mặc định sắp xếp theo tên loại dịch vụ từ A-Z', '',
     L1 + ' BR_01 - SRS chưa nêu thứ tự phụ khi cùng loại dịch vụ, ' + BA),
    ('T', 'Badge số lượng', 'Kiểm tra badge số lượng gói cước của loại gói',
     'ĐK: Loại gói A có 3 gói cước khác trạng thái Đã xoá\n1. Kiểm tra badge cạnh tên loại gói A',
     'Badge hiển thị số 3', '', L1 + ' STT 9'),
    ('T', None, 'Kiểm tra badge không tính gói cước trạng thái Đã xoá',
     'ĐK: Loại gói A có 3 gói (Nháp, Đang kinh doanh, Ngừng kinh doanh) và 1 gói Đã xoá\n1. Kiểm tra badge',
     'Badge hiển thị số 3', '', L1 + ' STT 9 - ' + EP),
    ('T', None, 'Kiểm tra badge cập nhật sau khi thêm mới gói cước',
     'ĐK: Badge loại gói A đang là X\n1. Tạo mới 1 gói cước thuộc loại gói A\n2. Quay lại danh sách',
     'Badge loại gói A hiển thị X+1', '', L1 + ' STT 9'),
    ('T', None, 'Kiểm tra badge cập nhật sau khi xoá gói cước',
     'ĐK: Badge loại gói A đang là X\n1. Xoá 1 gói cước Nháp thuộc loại gói A\n2. Kiểm tra badge',
     'Badge loại gói A hiển thị X-1', '', L1 + ' STT 9'),
    ('T', None, 'Kiểm tra badge khi loại gói chưa có gói cước',
     'ĐK: Loại gói A chưa có gói cước\n1. Kiểm tra badge', 'Badge hiển thị số 0', '', L1 + ' STT 9 - ' + BVA),
    ('T', 'Loại dịch vụ', 'Kiểm tra hiển thị loại dịch vụ trên dòng cha',
     '1. Kiểm tra thông tin loại dịch vụ', 'Hiển thị "Loại dịch vụ: <giá trị>" đúng loại dịch vụ của loại gói cước (OA, Meeting, Thiết bị...)', '',
     L1 + ' STT 10'),
    ('T', 'Loại hình OA áp dụng', 'Kiểm tra hiển thị Loại hình OA áp dụng khi loại dịch vụ = OA',
     'ĐK: Loại gói có loại dịch vụ = OA\n1. Kiểm tra dòng cha',
     'Hiển thị "Loại hình OA áp dụng: <tên loại hình>" sắp xếp tên A-Z, cách nhau dấu ";"', 'Doanh nghiệp; Khối nhà nước',
     L1 + ' STT 11 - ' + DT),
    ('T', None, 'Kiểm tra ẩn Loại hình OA áp dụng khi loại dịch vụ khác OA',
     'ĐK: Loại gói có loại dịch vụ = Thiết bị\n1. Kiểm tra dòng cha', 'Không hiển thị thông tin Loại hình OA áp dụng', '',
     L1 + ' STT 11 - ' + DT),
    ('T', None, 'Kiểm tra Loại hình OA áp dụng dài quá 20 ký tự',
     'ĐK: Chuỗi loại hình OA áp dụng dài 21 ký tự\n1. Kiểm tra hiển thị', 'Hiển thị 20 ký tự đầu, phần còn lại thay bằng "…"', 'Chuỗi 21 ký tự',
     L1 + ' STT 11 - ' + BVA),
    ('T', None, 'Kiểm tra Loại hình OA áp dụng đúng 20 ký tự',
     'ĐK: Chuỗi loại hình OA áp dụng dài 20 ký tự\n1. Kiểm tra hiển thị', 'Hiển thị đầy đủ 20 ký tự, không có "…"', 'Chuỗi 20 ký tự',
     L1 + ' STT 11 - ' + BVA),
    ('T', 'Danh mục OA áp dụng', 'Kiểm tra hiển thị Danh mục OA áp dụng khi loại dịch vụ = OA',
     'ĐK: Loại gói có loại dịch vụ = OA\n1. Kiểm tra dòng cha',
     'Hiển thị "Danh mục OA áp dụng: <tên danh mục>" sắp xếp tên A-Z, cách nhau dấu ";"', '',
     L1 + ' STT 12 - ' + DT),
    ('T', None, 'Kiểm tra ẩn Danh mục OA áp dụng khi loại dịch vụ khác OA',
     'ĐK: Loại gói có loại dịch vụ = Meeting\n1. Kiểm tra dòng cha', 'Không hiển thị thông tin Danh mục OA áp dụng', '',
     L1 + ' STT 12 - ' + DT),
    ('T', None, 'Kiểm tra Danh mục OA áp dụng dài quá 20 ký tự',
     'ĐK: Chuỗi danh mục OA áp dụng dài 21 ký tự\n1. Kiểm tra hiển thị', 'Hiển thị 20 ký tự đầu, phần còn lại thay bằng "…"', 'Chuỗi 21 ký tự',
     L1 + ' STT 12 - ' + BVA),
    ('T', 'Phạm vi áp dụng', 'Kiểm tra hiển thị Phạm vi áp dụng trên dòng cha',
     '1. Kiểm tra dòng cha', 'Hiển thị "Phạm vi áp dụng: <Tài khoản OA / Tài khoản Tammi>" theo design', '',
     'Design có "Phạm vi áp dụng" nhưng bảng mô tả SRS không có (thiếu STT 13) - ' + BA),

    ('G', 'Vùng danh sách - Bảng gói cước (dòng con)'),
    ('T', 'Header bảng con', 'Kiểm tra các cột của bảng danh sách gói cước',
     'ĐK: Mở rộng 1 dòng cha\n1. Kiểm tra header bảng',
     'Hiển thị các cột: Mã gói, Chu kỳ, Giá gốc (VNĐ), Kênh bán, Loại hình, Trạng thái, Thời gian cập nhật, Người cập nhật, Thao tác', '',
     L1 + ' STT 14-22. Design có thêm cột "Gia hạn tự động" không có trong SRS - ' + BA),
    ('T', None, 'Kiểm tra cột Thao tác cố định khi cuộn ngang bảng',
     'ĐK: Bảng có nhiều cột vượt độ rộng màn hình\n1. Cuộn ngang bảng', 'Cột Thao tác luôn hiển thị cố định bên phải, các cột khác cuộn bình thường, không vỡ layout', '',
     'Theo design - ' + BA),
    ('T', 'Danh sách gói cước con', 'Kiểm tra bảng con chỉ hiển thị gói cước khác trạng thái Đã xoá',
     'ĐK: Loại gói A có gói Nháp, Đã phát hành, Đang kinh doanh, Ngừng kinh doanh và 1 gói Đã xoá\n1. Mở rộng loại gói A',
     '- Hiển thị 4 gói ở trạng thái Nháp, Đã phát hành, Đang kinh doanh, Ngừng kinh doanh\n- Không hiển thị gói Đã xoá', '',
     L1 + ' BR_01 - ' + EP),
    ('T', None, 'Kiểm tra gói cước chỉ hiển thị dưới đúng loại gói cước của nó',
     '1. Mở rộng loại gói A và loại gói B\n2. Đối chiếu gói cước với dữ liệu DB', 'Gói cước hiển thị đúng dưới loại gói cước sở hữu, không lẫn sang loại gói khác', '',
     L1 + ' BR_01'),
    ('T', None, 'Kiểm tra thứ tự mặc định các gói cước con',
     'ĐK: Loại gói A có gói chu kỳ 12 tháng, 7 ngày, 1 năm, 2 tuần\n1. Mở rộng loại gói A',
     'Sắp xếp theo chu kỳ quy đổi ra ngày từ bé đến lớn: 7 ngày, 2 tuần, 12 tháng, 1 năm', '7 ngày=7; 2 tuần=14; 12 tháng=360; 1 năm=360',
     L1 + ' BR_01; ' + L2 + ' BR05. 12 tháng và 1 năm cùng 360 ngày (không thể cùng loại gói theo BR06) - dữ liệu minh hoạ'),
    ('T', 'Cột Mã gói', 'Kiểm tra hiển thị cột Mã gói',
     '1. Kiểm tra dữ liệu cột Mã gói', 'Hiển thị mã gói dạng text in hoa, đúng mã đã tạo', 'OAPLUS30', L1 + ' STT 14'),
    ('T', 'Sắp xếp cột (dòng con)', 'Kiểm tra sắp xếp cột Mã gói tăng dần',
     '1. Mở rộng 1 loại gói\n2. Click icon ⇅ tại cột Mã gói 1 lần', 'Danh sách gói con của loại gói đó sắp xếp theo Mã gói A-Z', '',
     L1 + ' STT 14, BR_03'),
    ('T', None, 'Kiểm tra sắp xếp cột Mã gói giảm dần',
     '1. Click icon ⇅ tại cột Mã gói 2 lần', 'Danh sách gói con sắp xếp theo Mã gói Z-A', '', L1 + ' STT 14, BR_03'),
    ('T', None, 'Kiểm tra sắp xếp cột Chu kỳ',
     '1. Click icon ⇅ tại cột Chu kỳ\n2. Click lại lần 2',
     '1. Sắp xếp chu kỳ bé đến lớn\n2. Sắp xếp chu kỳ lớn đến bé', '',
     L1 + ' STT 15, BR_03 - SRS chưa nêu so sánh theo số hay quy đổi ngày khi khác đơn vị, ' + BA),
    ('T', None, 'Kiểm tra sắp xếp cột Giá gốc',
     '1. Click icon ⇅ tại cột Giá gốc\n2. Click lại lần 2', '1. Sắp xếp giá bé đến lớn\n2. Sắp xếp giá lớn đến bé', '',
     L1 + ' STT 16, BR_03'),
    ('T', None, 'Kiểm tra sắp xếp cột Kênh bán',
     '1. Click icon ⇅ tại cột Kênh bán\n2. Click lại lần 2', '1. Sắp xếp tên kênh A-Z\n2. Sắp xếp tên kênh Z-A', '',
     L1 + ' STT 17, BR_03'),
    ('T', None, 'Kiểm tra sắp xếp cột Loại hình',
     '1. Click icon ⇅ tại cột Loại hình\n2. Click lại lần 2', '1. Sắp xếp tên loại hình A-Z\n2. Sắp xếp Z-A', '',
     L1 + ' STT 18, BR_03'),
    ('T', None, 'Kiểm tra sắp xếp cột Trạng thái',
     '1. Click icon ⇅ tại cột Trạng thái\n2. Click lại lần 2',
     '1. Sắp xếp theo thứ tự: Nháp → Đã phát hành → Đang kinh doanh → Ngừng kinh doanh\n2. Sắp xếp theo thứ tự ngược lại', '',
     L1 + ' STT 19, BR_03'),
    ('T', None, 'Kiểm tra sắp xếp cột Thời gian cập nhật',
     '1. Click icon ⇅ tại cột Thời gian cập nhật\n2. Click lại lần 2', '1. Sắp xếp từ gần đến xa\n2. Sắp xếp từ xa đến gần', '',
     L1 + ' STT 20, BR_03'),
    ('T', None, 'Kiểm tra sắp xếp cột Người cập nhật',
     '1. Click icon ⇅ tại cột Người cập nhật\n2. Click lại lần 2', '1. Sắp xếp tên A-Z\n2. Sắp xếp tên Z-A', '',
     L1 + ' STT 21, BR_03'),
    ('T', None, 'Kiểm tra sắp xếp chỉ áp dụng cục bộ trong loại gói đang thao tác',
     'ĐK: Mở rộng loại gói A và B\n1. Click sắp xếp cột Giá gốc tại bảng con loại gói A',
     '- Chỉ danh sách gói con của loại gói A thay đổi thứ tự\n- Bảng con loại gói B và thứ tự dòng cha không đổi', '',
     L1 + ' BR_03'),
    ('T', 'Cột Chu kỳ', 'Kiểm tra định dạng cột Chu kỳ',
     '1. Kiểm tra dữ liệu cột Chu kỳ', 'Hiển thị [Số] [Đơn vị], VD: 7 tháng, 12 tháng, 24 tháng', '', L1 + ' STT 15'),
    ('T', None, 'Kiểm tra hiển thị chu kỳ theo từng đơn vị',
     'ĐK: Có gói chu kỳ đơn vị Ngày, Tuần, Tháng, Năm\n1. Kiểm tra cột Chu kỳ',
     'Hiển thị đúng đơn vị đã lưu khi tạo: "30 ngày", "2 tuần", "12 tháng", "1 năm" (không tự quy đổi)', '',
     L1 + ' STT 15; ' + L2 + ' dữ liệu lưu billing_cycle_unit - ' + EP),
    ('T', 'Cột Giá gốc (VNĐ)', 'Kiểm tra định dạng cột Giá gốc',
     '1. Kiểm tra dữ liệu cột Giá gốc', 'Hiển thị số tiền có dấu chấm phân cách hàng nghìn, VD: 1.200.000', '1200000 -> 1.200.000',
     L1 + ' STT 16'),
    ('T', None, 'Kiểm tra hiển thị giá gốc giá trị lớn',
     'ĐK: Gói có giá gốc 9.999.999.999.999\n1. Kiểm tra cột Giá gốc', 'Hiển thị đúng 9.999.999.999.999, không vỡ layout, không hiển thị dạng số mũ', '9999999999999',
     L1 + ' STT 16 - DECIMAL(15,2) - ' + BVA),
    ('T', 'Cột Kênh bán', 'Kiểm tra hiển thị cột Kênh bán 1 kênh',
     'ĐK: Gói có kênh phân phối Web OA\n1. Kiểm tra cột Kênh bán', 'Hiển thị: Web OA', '', L1 + ' STT 17 - ' + EP),
    ('T', None, 'Kiểm tra hiển thị cột Kênh bán nhiều kênh',
     'ĐK: Gói có kênh phân phối Web OA và Mini app gói cước Tammi\n1. Kiểm tra cột Kênh bán',
     'Hiển thị đủ 2 kênh, text dài cắt "..." như design ("Mini app gói cước...")', '',
     L1 + ' STT 17 - SRS chưa nêu dấu phân cách/tooltip khi nhiều kênh, ' + BA),
    ('T', 'Cột Loại hình', 'Kiểm tra hiển thị cột Loại hình',
     'ĐK: Có gói Gói chính và gói Gói add-on\n1. Kiểm tra cột Loại hình', 'Hiển thị đúng: Chính / Add-on', '', L1 + ' STT 18 - ' + EP),
    ('T', 'Cột Trạng thái', 'Kiểm tra hiển thị trạng thái Nháp',
     'ĐK: Gói ở trạng thái Nháp\n1. Kiểm tra cột Trạng thái', 'Hiển thị status pill "Nháp" màu xám theo design', '', L1 + ' STT 19 - ' + EP),
    ('T', None, 'Kiểm tra hiển thị trạng thái Đã phát hành',
     'ĐK: Gói ở trạng thái Đã phát hành\n1. Kiểm tra cột Trạng thái', 'Hiển thị status pill "Đã phát hành" màu vàng theo design', '',
     L1 + ' STT 19 (SRS ghi "đã ban hành", design ghi "Đã phát hành" - ' + BA + ')'),
    ('T', None, 'Kiểm tra hiển thị trạng thái Đang kinh doanh',
     'ĐK: Gói ở trạng thái Đang kinh doanh\n1. Kiểm tra cột Trạng thái', 'Hiển thị status pill "Đang kinh doanh" màu xanh theo design', '', L1 + ' STT 19 - ' + EP),
    ('T', None, 'Kiểm tra hiển thị trạng thái Ngừng kinh doanh',
     'ĐK: Gói ở trạng thái Ngừng kinh doanh\n1. Kiểm tra cột Trạng thái', 'Hiển thị status pill "Ngừng kinh doanh" màu đỏ theo design', '', L1 + ' STT 19 - ' + EP),
    ('T', None, 'Kiểm tra trạng thái cập nhật khi gói tự động chuyển trạng thái',
     'ĐK: Gói Đã phát hành, Bật/tắt trạng thái = Tự động, thời gian bắt đầu = hiện tại + 2 phút\n1. Chờ qua thời gian bắt đầu\n2. Tải lại danh sách',
     'Cột Trạng thái của gói hiển thị "Đang kinh doanh"', '',
     'Bảng Trạng thái gói cước (Đã phát hành → Đang kinh doanh) - ' + ST),
    ('T', 'Cột Thời gian cập nhật', 'Kiểm tra định dạng cột Thời gian cập nhật',
     '1. Kiểm tra cột Thời gian cập nhật', 'Hiển thị thời điểm cập nhật gần nhất định dạng DD/MM/YYYY HH:mm:ss', '01/09/2026 10:09:50',
     L1 + ' STT 20'),
    ('T', None, 'Kiểm tra Thời gian/Người cập nhật thay đổi sau khi chỉnh sửa gói',
     '1. Admin B chỉnh sửa 1 gói cước\n2. Quay lại danh sách',
     'Thời gian cập nhật = thời điểm lưu chỉnh sửa, Người cập nhật = họ tên Admin B', '', L1 + ' STT 20, 21'),
    ('T', 'Cột Người cập nhật', 'Kiểm tra hiển thị cột Người cập nhật',
     '1. Kiểm tra cột Người cập nhật', 'Hiển thị họ và tên tài khoản Admin thực hiện cập nhật gần nhất', 'Nguyễn Văn A', L1 + ' STT 21'),
    ('T', 'Cột Thao tác', 'Kiểm tra hiển thị bộ icon thao tác',
     '1. Kiểm tra cột Thao tác từng dòng gói cước', 'Hiển thị 3 icon: (i) Xem chi tiết, ✏ Chỉnh sửa, 🗑 Xoá', '', L1 + ' STT 22'),
    ('T', None, 'Kiểm tra click icon (i)',
     '1. Click icon (i) tại 1 gói cước', 'Điều hướng đến trang Xem chi tiết đúng gói cước đã chọn', '', L1 + ' STT 22'),
    ('T', None, 'Kiểm tra click icon ✏',
     '1. Click icon ✏ tại 1 gói cước', 'Điều hướng đến trang Chỉnh sửa đúng gói cước đã chọn', '', L1 + ' STT 22'),
    ('T', None, 'Kiểm tra click icon 🗑',
     '1. Click icon 🗑 tại 1 gói cước', 'Thực hiện luồng Xoá gói cước theo UC xoá gói cước (hiển thị popup xác nhận)', '',
     L1 + ' STT 22 - UC xoá chưa mô tả chi tiết, ' + BA),
    ('T', None, 'Kiểm tra icon Xoá theo từng trạng thái gói',
     'ĐK: Có gói ở các trạng thái Nháp / Đã phát hành / Đang kinh doanh / Ngừng kinh doanh\n1. Kiểm tra icon 🗑 từng dòng',
     'Theo bảng trạng thái: gói Đang kinh doanh tuyệt đối không được xoá; Nháp được xoá; Đã phát hành/Ngừng kinh doanh chỉ xoá khi chưa phát sinh giao dịch',
     '', 'Bảng Trạng thái gói cước - ' + DT + '. SRS UC danh sách không nêu icon disable hay chặn khi click - ' + BA),
    ('T', 'Link + Thêm gói cước', 'Kiểm tra hiển thị link + Thêm gói cước',
     'ĐK: Mở rộng 1 dòng cha\n1. Kiểm tra góc dưới bên trái bảng con', 'Hiển thị text màu đỏ "+ Thêm gói cước"', '', L1 + ' STT 23'),
    ('T', None, 'Kiểm tra click + Thêm gói cước tại bảng con',
     'ĐK: Mở rộng loại gói "Plus OA Business"\n1. Click "+ Thêm gói cước"',
     '- Điều hướng đến form Tạo gói cước mới\n- Trường Loại gói cước tự gán sẵn "Plus OA Business"\n- Danh sách tính năng hiển thị theo loại gói đó',
     '', L1 + ' STT 23; ' + L2 + ' STT 13 Th1'),

    ('G', 'Phân trang'),
    ('T', 'Chọn số bản ghi/trang', 'Kiểm tra giá trị mặc định số bản ghi/trang',
     '1. Kiểm tra dropdown số bản ghi', 'Mặc định hiển thị "10 dòng", mỗi trang tối đa 10 loại gói cước (dòng cha)', '', L1 + ' STT 24'),
    ('T', None, 'Kiểm tra danh sách giá trị dropdown số bản ghi',
     '1. Click dropdown số bản ghi', 'Hiển thị các giá trị: 10, 15, 20, 25', '', L1 + ' STT 24'),
    ('T', None, 'Kiểm tra thay đổi số bản ghi/trang',
     'ĐK: Đang ở trang 2\n1. Chọn 20 dòng', '- Tải lại dữ liệu, tự động quay về trang 1\n- Hiển thị tối đa 20 loại gói cước/trang', '',
     L1 + ' STT 24'),
    ('T', None, 'Kiểm tra số bản ghi/trang chỉ tính dòng cha',
     'ĐK: Có 11 loại gói cước, mỗi loại có nhiều gói con, chọn 10 dòng\n1. Mở rộng các dòng cha\n2. Kiểm tra trang 1',
     'Trang 1 hiển thị 10 loại gói cước kèm toàn bộ gói con; loại gói thứ 11 ở trang 2', '', L1 + ' STT 24 - ' + BVA),
    ('T', 'Thông tin hiển thị', 'Kiểm tra text thông tin số bản ghi',
     'ĐK: Có 112 loại gói cước, 10 dòng/trang\n1. Kiểm tra text chân trang', 'Hiển thị: "Hiển thị 1–10 trong tổng số 112 kết quả"', '', L1 + ' STT 25'),
    ('T', None, 'Kiểm tra text thông tin ở trang cuối',
     'ĐK: Có 112 loại gói cước, 10 dòng/trang\n1. Chuyển đến trang cuối', 'Hiển thị: "Hiển thị 111–112 trong tổng số 112 kết quả"', '', L1 + ' STT 25 - ' + BVA),
    ('T', 'Điều hướng phân trang', 'Kiểm tra nút ← khi ở trang đầu',
     '1. Đang ở trang 1\n2. Kiểm tra nút ←', 'Nút ← bị vô hiệu hoá', '', L1 + ' STT 26 - ' + BVA),
    ('T', None, 'Kiểm tra nút → khi ở trang cuối',
     '1. Chuyển đến trang cuối\n2. Kiểm tra nút →', 'Nút → bị vô hiệu hoá', '', L1 + ' STT 26 - ' + BVA),
    ('T', None, 'Kiểm tra click số trang',
     '1. Click số trang 2', '- Hiển thị dữ liệu trang 2, nối tiếp trang 1\n- Số trang 2 active nền/chữ đỏ', '', L1 + ' STT 26'),
    ('T', None, 'Kiểm tra click nút → và ←',
     '1. Đang ở trang 1, click →\n2. Click ←', '1. Chuyển sang trang 2\n2. Quay lại trang 1', '', L1 + ' STT 26'),
    ('T', None, 'Kiểm tra phân trang khi số loại gói ≤ số bản ghi/trang',
     'ĐK: Có 10 loại gói cước, chọn 10 dòng\n1. Kiểm tra phân trang', 'Chỉ có 1 trang, nút ← và → đều bị vô hiệu hoá', '', L1 + ' STT 26 - ' + BVA),
    ('T', None, 'Kiểm tra hiển thị "..." khi nhiều trang',
     'ĐK: Có 15 trang\n1. Kiểm tra dãy số trang', 'Hiển thị 1, 2, 3, ..., 15 theo design', '', L1 + ' STT 26'),

    ('G', 'Kiểm tra ngoại lệ & phi chức năng'),
    ('T', 'Lỗi mạng', 'Kiểm tra tải danh sách khi mất kết nối mạng',
     '1. Ngắt kết nối mạng\n2. Truy cập màn hình Quản lý gói cước',
     'Hiển thị toast "Thất bại. Vui lòng kiểm tra lại kết nối." và cho phép người dùng thử lại', '', L1 + ' Exception 2b'),
    ('T', None, 'Kiểm tra thử lại sau khi có mạng trở lại',
     'ĐK: Đang hiển thị toast lỗi mạng\n1. Bật lại mạng\n2. Thực hiện thử lại', 'Danh sách tải thành công, hiển thị đúng dữ liệu', '', L1 + ' Exception 2b'),
    ('T', 'Lỗi hệ thống', 'Kiểm tra tải danh sách khi API lỗi hệ thống',
     'ĐK: API danh sách trả lỗi 500\n1. Truy cập màn hình Quản lý gói cước',
     'Hiển thị toast "Hệ thống bận. Vui lòng thử lại sau." kèm mã lỗi tương ứng, cho phép thử lại', '', L1 + ' Exception 2c'),
    ('T', 'Phân quyền', 'Kiểm tra truy cập khi tài khoản không có quyền xem phân hệ Gói cước',
     'ĐK: Tài khoản Admin không có quyền phân hệ Gói cước\n1. Đăng nhập CMS\n2. Kiểm tra menu / truy cập trực tiếp URL màn hình',
     'Không hiển thị menu Quản lý gói cước; truy cập URL trực tiếp bị chặn', '',
     L1 + ' Pre-condition 2, NFR 3.1 - SRS chưa nêu hành vi khi không có quyền, ' + BA),
    ('T', 'Dữ liệu', 'Kiểm tra dữ liệu danh sách khớp với CSDL',
     '1. Mở rộng các dòng cha\n2. Đối chiếu Mã gói, Chu kỳ, Giá, Kênh bán, Loại hình, Trạng thái với DB',
     'Dữ liệu hiển thị khớp CSDL; xem danh sách không làm thay đổi dữ liệu', '', L1 + ' Post-condition'),
    ('T', 'Hiệu năng', 'Kiểm tra thời gian tải danh sách',
     'ĐK: Có ≥ 100 loại gói cước\n1. Truy cập màn hình Quản lý gói cước\n2. Đo thời gian phản hồi API', 'API phản hồi < 500ms', '', 'NFR 1.1'),

    # =====================================================================
    ('S', 'UC2: (CMS admin) Chức năng Tạo mới gói cước'),
    ('P', 'Pre-condition: \nBước 1: Admin đăng nhập thành công vào CMS với quyền Quản lý gói cước\n'
          'Bước 2: Hệ thống có ít nhất 01 Loại gói cước trạng thái Đang hoạt động\n'
          'Bước 3: Click menu Quản lý gói cước > mở rộng 1 loại gói > click "+ Thêm gói cước"\n'),

    ('G', 'Kiểm tra gui UI/UX'),
    ('T', 'Kiểm tra UI', 'Kiểm tra hiển thị giao diện',
     '1. Vào màn Tạo gói cước mới\n2. Check hiển thị',
     'Hiển thị màn Tạo gói cước mới đúng design gồm:\n+ Icon Back, tiêu đề "Tạo gói cước mới", button Lưu\n'
     '+ Khối Thông tin cơ bản: Mã gói cước, Tag, Mô tả, Chu kỳ, Đơn vị, Giá gốc, Đơn vị tính\n'
     '+ Khối Thuộc tính: Loại hình gói, Kênh bán, Bật/tắt trạng thái và các trường phụ thuộc\n'
     '+ Khối Danh sách tính năng theo loại gói', '', L2 + ' - Mô tả màn hình'),
    ('T', None, 'Kiểm tra tổng thể giao diện màn hình',
     'Kiểm tra về bố cục, font chữ, chính tả, màu chữ', UI_OVERALL, '', ''),
    ('T', None, 'Kiểm tra khi nhấn Tab',
     '1. Thực hiện nhấn nút Tab ở bàn phím máy tính\n2. Check hiển thị',
     'Con trỏ di chuyển lần lượt theo thứ tự: Từ trái qua phải, từ trên xuống dưới', '', ''),
    ('T', None, 'Kiểm tra khi nhấn Shift-tab',
     '1. Thực hiện nhấn nút Shift-Tab ở bàn phím máy tính\n2. Check hiển thị',
     'Con trỏ di chuyển ngược lại theo thứ tự: từ dưới lên trên, từ phải qua trái', '', ''),
    ('T', None, 'Kiểm tra giao diện khi thu nhỏ, phóng to',
     '1. Thực hiện zoom in, zoom out > check hiển thị', 'Hiển thị màn hình phóng to, thu nhỏ không bị xô lệch, vỡ form', '', ''),
    ('T', None, 'Kiểm tra tiêu đề', '1. Kiểm tra text tiêu đề', 'Hiển thị tiêu đề text là "Tạo gói cước mới"', '', 'Theo design'),
    ('T', None, 'Kiểm tra dấu * các trường bắt buộc',
     '1. Kiểm tra label các trường',
     'Hiển thị dấu * đỏ tại: Mã gói cước, Chu kỳ, Đơn vị, Giá gốc, Đơn vị tính, Loại hình gói, Kênh bán, Bật/tắt trạng thái, Loại gói cước, Tham số', '',
     L2 + ' - Design có * tại Mô tả và Tag nhưng SRS ghi Bắt buộc = Không - ' + BA),
    ('T', None, 'Kiểm tra giá trị mặc định khi mở form',
     '1. Kiểm tra giá trị mặc định các trường',
     '- Mã gói, Mô tả, Chu kỳ, Giá gốc, Tag, Kênh bán: rỗng\n- Đơn vị: Ngày; Đơn vị tính: VNĐ\n- Loại hình gói: Gói chính\n'
     '- Bật/tắt trạng thái: Thủ công; Trạng thái kinh doanh: Đang kinh doanh\n- Số lượng đăng ký giới hạn: rỗng', '',
     L2 + ' - cột Giá trị mặc định. Design đang tick sẵn "Tự động" - ' + BA),
    ('T', None, 'Kiểm tra button Lưu', '1. Kiểm tra hiển thị button Lưu', 'Hiển thị button "Lưu" góc phải trên, trạng thái enable', '', L2 + ' Basic flow B5'),

    ('G', 'Kiểm tra validate'),
    # ---- Mã gói cước
    ('T', 'Kiểm tra trường Mã gói cước', 'Kiểm tra hiển thị mặc định', '1. Kiểm tra hiển thị',
     'Hiển thị trường Mã gói cước ban đầu mặc định trống', '', L2 + ' STT 1'),
    ('T', None, 'Kiểm tra để trống', '1. Để trống Mã gói cước\n2. Nhập đủ các trường còn lại hợp lệ\n3. Click Lưu',
     'Hiển thị lỗi inline: "Vui lòng nhập thông tin", không lưu gói cước', '', L2 + ' STT 1'),
    ('T', None, 'Kiểm tra nhập toàn dấu cách', '1. Nhập toàn ký tự space\n2. Click Lưu',
     'Hiển thị lỗi inline: "Vui lòng nhập thông tin"', '"     "', L2 + ' STT 1 - SRS chưa nêu trim, ' + BA),
    ('T', None, 'Kiểm tra tự động chuyển chữ thường thành chữ hoa', '1. Nhập "oaplus30"',
     'Trường tự động hiển thị "OAPLUS30"', 'oaplus30', L2 + ' STT 1'),
    ('T', None, 'Kiểm tra tự động bỏ dấu tiếng Việt', '1. Nhập "gói cước ưu đãi"',
     'Trường tự động hiển thị dạng viết hoa không dấu: "GOI CUOC UU DAI"', 'gói cước ưu đãi',
     L2 + ' STT 1 - SRS chưa nêu có cho phép khoảng trắng trong mã không, ' + BA),
    ('T', None, 'Kiểm tra nhập ký tự đặc biệt', '1. Nhập "OA_PLUS-30@#"\n2. Check hiển thị',
     'Hệ thống xử lý theo rule ký tự của mã gói', 'OA_PLUS-30@#', L2 + ' STT 1 - SRS chưa quy định tập ký tự cho phép, ' + BA),
    ('T', None, 'Kiểm tra nhập 49 ký tự', '1. Nhập 49 ký tự\n2. Check hiển thị', 'Hiển thị đủ 49 ký tự vừa nhập, không báo lỗi', 'Chuỗi 49 ký tự',
     L2 + ' STT 1 - ' + BVA),
    ('T', None, 'Kiểm tra nhập 50 ký tự', '1. Nhập 50 ký tự\n2. Check hiển thị', 'Hiển thị đủ 50 ký tự vừa nhập, không báo lỗi', 'Chuỗi 50 ký tự',
     L2 + ' STT 1 - ' + BVA),
    ('T', None, 'Kiểm tra nhập 51 ký tự', '1. Nhập 51 ký tự\n2. Check hiển thị', 'Chặn nhập ký tự thứ 51, chỉ cho phép 50 ký tự', 'Chuỗi 51 ký tự',
     L2 + ' STT 1 - ' + BVA),
    ('T', None, 'Kiểm tra paste chuỗi vượt 50 ký tự', 'ĐK: Đã copy chuỗi 60 ký tự\n1. Paste vào trường Mã gói cước',
     'Chỉ giữ 50 ký tự đầu', 'Chuỗi 60 ký tự', L2 + ' STT 1 - ' + BVA),
    ('T', None, 'Kiểm tra nhập mã trùng với gói cước đang tồn tại', 'ĐK: Đã có gói mã "OAPLUS30" trạng thái Nháp\n1. Nhập "OAPLUS30"\n2. Nhập đủ trường khác\n3. Click Lưu',
     'Hiển thị lỗi inline: "Mã gói đã được sử dụng", không lưu gói cước', 'OAPLUS30', L2 + ' STT 1, BR04 - ' + EP),
    ('T', None, 'Kiểm tra trùng mã với gói ở trạng thái Đang kinh doanh / Ngừng kinh doanh / Đã phát hành',
     'ĐK: Có gói mã A (Đang kinh doanh), B (Ngừng kinh doanh), C (Đã phát hành)\n1. Lần lượt nhập mã A, B, C\n2. Click Lưu',
     'Cả 3 trường hợp đều hiển thị lỗi inline: "Mã gói đã được sử dụng"', '', L2 + ' BR04 - ' + EP),
    ('T', None, 'Kiểm tra mã trùng với gói cước trạng thái Đã xoá',
     'ĐK: Gói mã "OAPLUS60" đã bị xoá\n1. Nhập "OAPLUS60"\n2. Nhập đủ trường khác\n3. Click Lưu',
     'Cho phép lưu, tạo gói cước thành công', 'OAPLUS60', L2 + ' BR04 - ' + EP),
    ('T', None, 'Kiểm tra mã trùng với gói thuộc loại gói khác', 'ĐK: Mã "OAPLUS30" đã tồn tại ở loại gói A\n1. Tạo gói trong loại gói B với mã "OAPLUS30"\n2. Click Lưu',
     'Hiển thị lỗi inline: "Mã gói đã được sử dụng" (mã duy nhất toàn hệ thống)', '', L2 + ' BR04'),
    ('T', None, 'Kiểm tra mã trùng khi khác chữ hoa/thường', 'ĐK: Mã "OAPLUS30" đã tồn tại\n1. Nhập "oaplus30"\n2. Click Lưu',
     'Mã tự chuyển thành "OAPLUS30" và báo lỗi "Mã gói đã được sử dụng"', 'oaplus30', L2 + ' STT 1, BR04'),
    ('T', None, 'Kiểm tra copy/paste dữ liệu', '1. Copy chuỗi hợp lệ từ vùng khác\n2. Paste vào Mã gói cước',
     'Paste dữ liệu thành công, áp dụng rule viết hoa/không dấu', '', ''),
    # ---- Mô tả
    ('T', 'Kiểm tra trường Mô tả gói cước', 'Kiểm tra hiển thị mặc định', '1. Kiểm tra hiển thị',
     'Hiển thị trường Mô tả dạng textarea, mặc định trống', '', L2 + ' STT 2'),
    ('T', None, 'Kiểm tra để trống Mô tả', '1. Để trống Mô tả\n2. Nhập đủ các trường bắt buộc khác\n3. Click Lưu',
     'Cho phép lưu thành công (trường không bắt buộc)', '',
     L2 + ' STT 2 - Mâu thuẫn SRS (Bắt buộc = Không) và design (có *) - ' + BA),
    ('T', None, 'Kiểm tra nhập 499 ký tự', '1. Nhập 499 ký tự', 'Hiển thị đủ dữ liệu vừa nhập', 'Chuỗi 499 ký tự', L2 + ' STT 2 - ' + BVA),
    ('T', None, 'Kiểm tra nhập 500 ký tự', '1. Nhập 500 ký tự', 'Hiển thị đủ dữ liệu vừa nhập', 'Chuỗi 500 ký tự', L2 + ' STT 2 - ' + BVA),
    ('T', None, 'Kiểm tra nhập 501 ký tự', '1. Nhập 501 ký tự', 'Chặn nhập ký tự thứ 501, chỉ cho phép 500 ký tự', 'Chuỗi 501 ký tự',
     L2 + ' STT 2 - ' + BVA),
    ('T', None, 'Kiểm tra nhập tất cả loại ký tự', '1. Nhập chuỗi gồm chữ, số, ký tự đặc biệt, tiếng Việt có dấu, emoji\n2. Click Lưu',
     'Cho phép nhập và lưu đúng dữ liệu', 'Gói OA 30 ngày - ưu đãi 50% @#$ 😀', L2 + ' STT 2'),
    ('T', None, 'Kiểm tra định dạng html gạch đầu dòng', '1. Nhập mô tả có gạch đầu dòng (định dạng html)\n2. Lưu và xem chi tiết',
     'Mô tả hiển thị đúng định dạng gạch đầu dòng', '<ul><li>Quyền lợi 1</li></ul>', L2 + ' STT 2'),
    ('T', None, 'Kiểm tra nhập mã script', '1. Nhập "<script>alert(1)</script>"\n2. Lưu và xem chi tiết',
     'Không thực thi script, hiển thị dạng text', '<script>alert(1)</script>', L2 + ' STT 2 - bảo mật XSS'),
    # ---- Chu kỳ
    ('T', 'Kiểm tra trường Chu kỳ', 'Kiểm tra để trống', '1. Để trống Chu kỳ\n2. Click Lưu',
     'Hiển thị lỗi inline: "Vui lòng nhập thông tin"', '', L2 + ' STT 3'),
    ('T', None, 'Kiểm tra nhập 0', '1. Nhập 0\n2. Click Lưu', 'Không cho phép lưu, chu kỳ phải là số nguyên dương > 0', '0',
     L2 + ' STT 3 - ' + BVA + '. SRS chưa nêu message lỗi, ' + BA),
    ('T', None, 'Kiểm tra nhập 1', '1. Nhập 1\n2. Nhập đủ trường khác\n3. Click Lưu', 'Cho phép lưu thành công', '1', L2 + ' STT 3 - ' + BVA),
    ('T', None, 'Kiểm tra nhập số âm', '1. Nhập -1', 'Chặn không cho nhập dấu "-"', '-1', L2 + ' STT 3 - ' + EP),
    ('T', None, 'Kiểm tra nhập số thập phân', '1. Nhập 1.5', 'Chặn không cho nhập (chỉ cho số nguyên)', '1.5', L2 + ' STT 3 INT - ' + EP),
    ('T', None, 'Kiểm tra nhập chữ và ký tự đặc biệt', '1. Nhập "abc@#"', 'Chặn không cho nhập', 'abc@#', L2 + ' STT 3 - ' + EP),
    ('T', None, 'Kiểm tra nhập giá trị lớn', '1. Nhập 2147483647\n2. Nhập 2147483648',
     'Chặn/báo lỗi khi vượt giới hạn INT', '2147483647 / 2147483648', L2 + ' STT 3 INT - ' + BVA + '. SRS chưa nêu max chu kỳ, ' + BA),
    ('T', None, 'Kiểm tra trùng chu kỳ cùng đơn vị với gói khác cùng loại gói',
     'ĐK: Loại gói A đã có gói 30 Ngày\n1. Tạo gói thuộc loại gói A: Chu kỳ 30, Đơn vị Ngày\n2. Click Lưu',
     'Hiển thị lỗi: "Đã có gói cùng chu kì thuộc cùng loại gói", không lưu', '30 Ngày', L2 + ' STT 3, BR06'),
    ('T', None, 'Kiểm tra trùng chu kỳ sau quy đổi Tháng = Ngày',
     'ĐK: Loại gói A đã có gói 30 Ngày\n1. Tạo gói thuộc loại gói A: Chu kỳ 1, Đơn vị Tháng\n2. Click Lưu',
     'Hiển thị lỗi: "Đã có gói cùng chu kì thuộc cùng loại gói" (1 tháng = 30 ngày)', '1 Tháng', L2 + ' BR05, BR06 - ' + EP),
    ('T', None, 'Kiểm tra trùng chu kỳ sau quy đổi Tuần = Ngày',
     'ĐK: Loại gói A đã có gói 14 Ngày\n1. Tạo gói thuộc loại gói A: Chu kỳ 2, Đơn vị Tuần\n2. Click Lưu',
     'Hiển thị lỗi: "Đã có gói cùng chu kì thuộc cùng loại gói" (2 tuần = 14 ngày)', '2 Tuần', L2 + ' BR05, BR06 - ' + EP),
    ('T', None, 'Kiểm tra trùng chu kỳ sau quy đổi Năm = Tháng',
     'ĐK: Loại gói A đã có gói 12 Tháng\n1. Tạo gói thuộc loại gói A: Chu kỳ 1, Đơn vị Năm\n2. Click Lưu',
     'Hiển thị lỗi: "Đã có gói cùng chu kì thuộc cùng loại gói" (1 năm = 360 ngày = 12 tháng)', '1 Năm', L2 + ' BR05, BR06 - ' + EP),
    ('T', None, 'Kiểm tra chu kỳ lệch 1 ngày so với gói đã có',
     'ĐK: Loại gói A đã có gói 1 Tháng (30 ngày)\n1. Tạo gói 29 Ngày, Lưu\n2. Tạo gói 31 Ngày, Lưu',
     'Cả 2 gói đều lưu thành công', '29 Ngày / 31 Ngày', L2 + ' BR05, BR06 - ' + BVA),
    ('T', None, 'Kiểm tra trùng chu kỳ với gói ở loại gói khác',
     'ĐK: Loại gói A đã có gói 30 Ngày\n1. Tạo gói thuộc loại gói B: 30 Ngày\n2. Click Lưu', 'Cho phép lưu thành công', '', L2 + ' BR06 - ' + EP),
    ('T', None, 'Kiểm tra trùng chu kỳ với gói cùng loại gói ở các trạng thái',
     'ĐK: Loại gói A có gói 30 Ngày lần lượt ở trạng thái Nháp / Đã phát hành / Đang kinh doanh / Ngừng kinh doanh\n1. Tạo gói 30 Ngày thuộc loại gói A\n2. Click Lưu',
     'Tất cả trường hợp đều báo lỗi "Đã có gói cùng chu kì thuộc cùng loại gói"', '', L2 + ' BR06 - ' + EP),
    ('T', None, 'Kiểm tra trùng chu kỳ với gói cùng loại gói trạng thái Đã xoá',
     'ĐK: Loại gói A có gói 30 Ngày đã bị xoá\n1. Tạo gói 30 Ngày thuộc loại gói A\n2. Click Lưu', 'Cho phép lưu thành công', '', L2 + ' BR06 - ' + EP),
    # ---- Đơn vị
    ('T', 'Kiểm tra trường Đơn vị (chu kỳ)', 'Kiểm tra giá trị mặc định', '1. Kiểm tra dropdown Đơn vị', 'Mặc định chọn "Ngày"', '', L2 + ' STT 4'),
    ('T', None, 'Kiểm tra danh sách giá trị', '1. Click dropdown Đơn vị', 'Hiển thị 4 giá trị: Ngày, Tuần, Tháng, Năm', '', L2 + ' STT 4'),
    ('T', None, 'Kiểm tra chọn giá trị', '1. Chọn "Tháng"', 'Hiển thị "Tháng", đóng dropdown; chỉ chọn được 1 giá trị', '', L2 + ' STT 4 - ' + EP),
    # ---- Giá gốc
    ('T', 'Kiểm tra trường Giá gốc', 'Kiểm tra để trống', '1. Để trống Giá gốc\n2. Click Lưu', 'Hiển thị lỗi inline: "Vui lòng nhập thông tin"', '', L2 + ' STT 5'),
    ('T', None, 'Kiểm tra tự động format dấu phân cách hàng nghìn', '1. Nhập 1119000', 'Hiển thị "1.119.000"', '1119000', L2 + ' STT 5'),
    ('T', None, 'Kiểm tra nhập 0', '1. Nhập 0\n2. Click Lưu', 'Không cho phép lưu, giá gốc phải > 0', '0',
     L2 + ' STT 5 - ' + BVA + '. Dữ liệu cần lưu ghi original_price ≥ 0, mâu thuẫn STT 5 (> 0) - ' + BA),
    ('T', None, 'Kiểm tra nhập 1', '1. Nhập 1\n2. Nhập đủ trường khác\n3. Click Lưu', 'Cho phép lưu thành công', '1', L2 + ' STT 5 - ' + BVA),
    ('T', None, 'Kiểm tra nhập số âm', '1. Nhập -1000', 'Chặn không cho nhập dấu "-"', '-1000', L2 + ' STT 5 - ' + EP),
    ('T', None, 'Kiểm tra nhập số thập phân', '1. Nhập 1000,5', 'Chặn không cho nhập phần thập phân (số tiền nguyên)', '1000,5',
     L2 + ' STT 5 - DECIMAL(15,2) nhưng mô tả "số tiền nguyên dương", ' + BA),
    ('T', None, 'Kiểm tra nhập chữ và ký tự đặc biệt', '1. Nhập "abc@"', 'Chặn không cho nhập', 'abc@', L2 + ' STT 5 - ' + EP),
    ('T', None, 'Kiểm tra nhập 13 chữ số', '1. Nhập 9999999999999', 'Hiển thị "9.999.999.999.999", cho phép lưu', '9999999999999',
     L2 + ' STT 5 DECIMAL(15,2) - ' + BVA),
    ('T', None, 'Kiểm tra nhập 14 chữ số', '1. Nhập 99999999999999', 'Chặn nhập chữ số thứ 14', '99999999999999',
     L2 + ' STT 5 DECIMAL(15,2) - ' + BVA + ', SRS chưa nêu max, ' + BA),
    # ---- Đơn vị tính
    ('T', 'Kiểm tra trường Đơn vị tính (tiền)', 'Kiểm tra giá trị mặc định và không cho sửa', '1. Kiểm tra trường Đơn vị tính\n2. Click vào trường',
     'Hiển thị "VNĐ" dạng read-only (nền xám), không sửa được', '', L2 + ' STT 6'),
    # ---- Loại hình gói
    ('T', 'Kiểm tra trường Loại hình gói', 'Kiểm tra giá trị mặc định', '1. Kiểm tra Loại hình gói', 'Mặc định "Gói chính"', '', L2 + ' STT 7'),
    ('T', None, 'Kiểm tra danh sách lựa chọn', '1. Click dropdown Loại hình gói', 'Hiển thị 2 lựa chọn: Gói chính, Gói add-on', '', L2 + ' STT 7'),
    ('T', None, 'Kiểm tra chọn Gói add-on và lưu', '1. Chọn "Gói add-on"\n2. Nhập đủ trường khác\n3. Click Lưu',
     'Lưu thành công, danh sách hiển thị Loại hình = Add-on', '', L2 + ' STT 7 - ' + EP),
    # ---- Tag
    ('T', 'Kiểm tra trường Tag', 'Kiểm tra để trống Tag', '1. Để trống Tag\n2. Nhập đủ trường bắt buộc khác\n3. Click Lưu',
     'Cho phép lưu thành công (trường không bắt buộc)', '', L2 + ' STT 8 - Mâu thuẫn SRS (Bắt buộc = Không) và design (có *) - ' + BA),
    ('T', None, 'Kiểm tra nhập 50 ký tự', '1. Nhập 50 ký tự', 'Hiển thị đủ 50 ký tự', 'Chuỗi 50 ký tự', L2 + ' STT 8 - ' + BVA),
    ('T', None, 'Kiểm tra nhập 51 ký tự', '1. Nhập 51 ký tự', 'Chặn nhập ký tự thứ 51', 'Chuỗi 51 ký tự',
     L2 + ' STT 8 - ' + BVA + '. Kiểu VARCHAR(100) nhưng rule chặn 50 ký tự - ' + BA),
    ('T', None, 'Kiểm tra nhập tất cả loại ký tự', '1. Nhập "Giảm 50% khi ra mắt! 🔥"\n2. Lưu', 'Cho phép nhập và lưu đúng dữ liệu', 'Giảm 50% khi ra mắt! 🔥', L2 + ' STT 8'),
    # ---- Kênh phân phối
    ('T', 'Kiểm tra trường Kênh bán (phân phối)', 'Kiểm tra danh sách lựa chọn', '1. Click trường Kênh bán',
     'Hiển thị 2 lựa chọn: Miniapp gói cước Tammi, Web OA', '', L2 + ' STT 9'),
    ('T', None, 'Kiểm tra không chọn kênh nào', '1. Không chọn Kênh bán\n2. Click Lưu', 'Hiển thị lỗi bắt buộc, không lưu gói cước', '',
     L2 + ' STT 9 - SRS chưa nêu message lỗi, ' + BA),
    ('T', None, 'Kiểm tra chọn 1 kênh', '1. Chọn "Web OA"\n2. Nhập đủ trường khác\n3. Click Lưu', 'Lưu thành công, distribution_channels = ["WEB_OA"]', '',
     L2 + ' STT 9 - ' + EP),
    ('T', None, 'Kiểm tra chọn nhiều kênh', '1. Chọn "Web OA" và "Miniapp gói cước Tammi"\n2. Click Lưu',
     'Lưu thành công, distribution_channels = ["WEB_OA", "MINIAPP_TAMMI"]', '', L2 + ' STT 9 - ' + EP),
    ('T', None, 'Kiểm tra bỏ chọn kênh đã chọn', '1. Chọn "Web OA"\n2. Bỏ chọn "Web OA"', 'Trường Kênh bán trở về rỗng', '', L2 + ' STT 9'),
    # ---- Bật/tắt trạng thái
    ('T', 'Kiểm tra trường Bật/tắt trạng thái', 'Kiểm tra chỉ chọn được 1 trong 2 lựa chọn',
     '1. Chọn "Thủ công"\n2. Chọn "Tự động"', 'Chỉ 1 lựa chọn được tick tại 1 thời điểm; chọn Tự động thì Thủ công tự bỏ tick', '',
     L2 + ' STT 10 - ' + EP),
    ('T', None, 'Kiểm tra hiển thị trường khi chọn Thủ công',
     '1. Chọn "Thủ công"\n2. Kiểm tra các trường phụ thuộc',
     '- Hiển thị trường Trạng thái kinh doanh (Đang kinh doanh / Ngừng kinh doanh)\n- Ẩn/không bắt buộc Thời gian bắt đầu, Thời gian kết thúc', '',
     DT + '. MÂU THUẪN: BR02 và bảng field ghi Thủ công -> bắt buộc thời gian, Tự động -> chọn trạng thái KD; '
     'nhưng bảng Trạng thái gói cước, Dữ liệu cần lưu và design thể hiện ngược lại. TC viết theo design + bảng trạng thái - ' + BA),
    ('T', None, 'Kiểm tra hiển thị trường khi chọn Tự động',
     '1. Chọn "Tự động"\n2. Kiểm tra các trường phụ thuộc',
     '- Hiển thị Thời gian bắt đầu *, Thời gian kết thúc *\n- Ẩn trường Trạng thái kinh doanh', '',
     DT + '. Xem mâu thuẫn BR02 tại TC trên - ' + BA),
    ('T', None, 'Kiểm tra chuyển Tự động -> Thủ công sau khi đã nhập thời gian',
     '1. Chọn Tự động, nhập Thời gian bắt đầu/kết thúc\n2. Chuyển sang Thủ công\n3. Click Lưu',
     'Lưu thành công, không validate thời gian; start_time/end_time không lưu', '', DT + ' - ' + BA),
    # ---- Trạng thái kinh doanh
    ('T', 'Kiểm tra trường Trạng thái kinh doanh', 'Kiểm tra giá trị mặc định và lựa chọn',
     'ĐK: Bật/tắt trạng thái = Thủ công\n1. Kiểm tra trường Trạng thái kinh doanh\n2. Click dropdown',
     '1. Mặc định "Đang kinh doanh"\n2. Hiển thị 2 lựa chọn: Đang kinh doanh, Ngừng kinh doanh', '',
     L2 + ' - trường Trạng thái kinh doanh (không có trong design) - ' + BA),
    ('T', None, 'Kiểm tra lưu với trạng thái kinh doanh Ngừng kinh doanh',
     'ĐK: Thủ công\n1. Chọn "Ngừng kinh doanh"\n2. Nhập đủ trường khác\n3. Click Lưu',
     'Lưu thành công, gói trạng thái Nháp, Sale_status = PENDING', '', L2 + ' BR01 - ' + EP),
    # ---- Thời gian
    ('T', 'Kiểm tra trường Thời gian bắt đầu', 'Kiểm tra giá trị mặc định', 'ĐK: Bật/tắt trạng thái = Tự động\n1. Kiểm tra Thời gian bắt đầu',
     'Mặc định ngày hiện tại', '', L2 + ' STT 11 - Mặc định "Ngày hiện tại" nhưng rule yêu cầu > thời điểm hiện tại -> giá trị mặc định luôn không hợp lệ, ' + BA),
    ('T', None, 'Kiểm tra định dạng hiển thị', 'ĐK: Tự động\n1. Chọn thời gian bắt đầu từ date picker',
     'Hiển thị định dạng DD/MM/YYYY HH:mm:ss', '25/09/2026 08:00:00', L2 + ' STT 11 - Design chỉ hiển thị DD/MM/YYYY - ' + BA),
    ('T', None, 'Kiểm tra để trống khi Tự động', 'ĐK: Tự động\n1. Xoá Thời gian bắt đầu\n2. Click Lưu',
     'Hiển thị lỗi inline: "Vui lòng nhập thông tin"', '', L2 + ' STT 11 - ' + DT),
    ('T', None, 'Kiểm tra thời gian bắt đầu nhỏ hơn hiện tại', 'ĐK: Tự động\n1. Chọn thời gian bắt đầu = hiện tại - 1 phút\n2. Click Lưu',
     'Không cho phép lưu / không cho chọn thời điểm quá khứ', 'Hiện tại - 1 phút', L2 + ' STT 11 - ' + BVA + ', SRS chưa nêu message, ' + BA),
    ('T', None, 'Kiểm tra thời gian bắt đầu bằng hiện tại', 'ĐK: Tự động\n1. Chọn thời gian bắt đầu = thời điểm hiện tại\n2. Click Lưu',
     'Không cho phép lưu (yêu cầu > hiện tại)', 'Hiện tại', L2 + ' STT 11 - ' + BVA),
    ('T', None, 'Kiểm tra thời gian bắt đầu lớn hơn hiện tại', 'ĐK: Tự động\n1. Chọn thời gian bắt đầu = hiện tại + 1 phút, kết thúc hợp lệ\n2. Click Lưu',
     'Lưu thành công', 'Hiện tại + 1 phút', L2 + ' STT 11 - ' + BVA),
    ('T', 'Kiểm tra trường Thời gian kết thúc', 'Kiểm tra giá trị mặc định', 'ĐK: Tự động\n1. Kiểm tra Thời gian kết thúc',
     'Mặc định rỗng', '', L2 + ' STT 12 - Design đang hiển thị sẵn 11/09/2026 - ' + BA),
    ('T', None, 'Kiểm tra để trống khi Tự động', 'ĐK: Tự động\n1. Để trống Thời gian kết thúc\n2. Click Lưu',
     'Hiển thị lỗi inline: "Vui lòng nhập thông tin"', '', L2 + ' STT 12 - ' + DT),
    ('T', None, 'Kiểm tra thời gian kết thúc nhỏ hơn thời gian bắt đầu', 'ĐK: Tự động, bắt đầu 01/10/2026 08:00:00\n1. Chọn kết thúc 01/10/2026 07:59:59\n2. Click Lưu',
     'Không cho phép lưu, báo lỗi thời gian kết thúc phải > thời gian bắt đầu', '', L2 + ' STT 12 - ' + BVA + ', SRS chưa nêu message, ' + BA),
    ('T', None, 'Kiểm tra thời gian kết thúc bằng thời gian bắt đầu', 'ĐK: Tự động, bắt đầu 01/10/2026 08:00:00\n1. Chọn kết thúc 01/10/2026 08:00:00\n2. Click Lưu',
     'Không cho phép lưu', '', L2 + ' STT 12 - ' + BVA),
    ('T', None, 'Kiểm tra thời gian kết thúc lớn hơn thời gian bắt đầu 1 giây', 'ĐK: Tự động, bắt đầu 01/10/2026 08:00:00\n1. Chọn kết thúc 01/10/2026 08:00:01\n2. Click Lưu',
     'Lưu thành công', '', L2 + ' STT 12 - ' + BVA),
    ('T', None, 'Kiểm tra nhập tay sai định dạng ngày', 'ĐK: Tự động\n1. Nhập tay "31/02/2026" hoặc "abc"',
     'Không nhận giá trị không hợp lệ, báo lỗi định dạng', '31/02/2026', L2 + ' STT 11, 12 - ' + EP),
    # ---- Số lượng đăng ký giới hạn
    ('T', 'Kiểm tra trường Số lượng đăng ký giới hạn', 'Kiểm tra để trống', '1. Để trống\n2. Nhập đủ trường khác\n3. Click Lưu',
     'Lưu thành công, max_purchase_quantity = null (không giới hạn)', '', L2 + ' - trường không có STT, không có trong design - ' + BA),
    ('T', None, 'Kiểm tra nhập 0', '1. Nhập 0\n2. Click Lưu', 'Lưu thành công, hiểu là không giới hạn', '0', BVA),
    ('T', None, 'Kiểm tra nhập 1', '1. Nhập 1\n2. Click Lưu', 'Lưu thành công, mỗi user chỉ đăng ký được 1 lần', '1', BVA),
    ('T', None, 'Kiểm tra nhập số âm, thập phân, chữ', '1. Lần lượt nhập -1, 1.5, "abc"', 'Chặn không cho nhập', '-1 / 1.5 / abc', EP),
    # ---- Loại gói cước
    ('T', 'Kiểm tra trường Loại gói cước', 'Kiểm tra tự gán khi vào từ dòng cha',
     '1. Tại danh sách, mở rộng loại gói "Plus OA Business"\n2. Click "+ Thêm gói cước"',
     'Trường Loại gói cước hiển thị "Plus OA Business"', '', L2 + ' STT 13 Th1'),
    ('T', None, 'Kiểm tra để trống khi vào từ button Thêm gói cước chung',
     '1. Click button "Thêm gói cước" góc phải trên màn danh sách\n2. Kiểm tra Loại gói cước',
     '- Trường Loại gói cước rỗng\n- Khối Danh sách tính năng chưa hiển thị tính năng', '', L2 + ' STT 13 Th2'),
    ('T', None, 'Kiểm tra danh sách loại gói có thể chọn',
     'ĐK: Vào từ button Thêm gói cước chung\n1. Click trường Loại gói cước',
     'Hiển thị danh sách loại gói cước trạng thái Đang hoạt động, không có loại gói Đã xoá', '', L2 + ' STT 13, Pre-condition 2'),
    ('T', None, 'Kiểm tra để trống loại gói khi lưu', 'ĐK: Vào từ button Thêm gói cước chung\n1. Không chọn Loại gói cước\n2. Click Lưu',
     'Hiển thị lỗi bắt buộc, không lưu', '', L2 + ' STT 13 - SRS chưa nêu message, ' + BA),
    ('T', None, 'Kiểm tra đổi loại gói cước', '1. Chọn loại gói A\n2. Đổi sang loại gói B',
     'Danh sách tính năng thay đổi theo loại gói B, tham số đã nhập của loại gói A bị xoá', '', L2 + ' STT 13 - ' + BA),
    ('T', None, 'Kiểm tra sửa Loại gói cước khi vào từ dòng cha', 'ĐK: Vào từ "+ Thêm gói cước" dòng cha\n1. Click trường Loại gói cước',
     'Trường hiển thị read-only (nền xám) theo design, không đổi được', '', L2 + ' STT 13 - Design nền xám - ' + BA),
    # ---- Danh sách tính năng / tham số
    ('T', 'Kiểm tra Danh sách tính năng', 'Kiểm tra các cột danh sách tính năng', '1. Kiểm tra bảng Danh sách tính năng',
     'Hiển thị các cột: STT, Mã tính năng, Tên tính năng, Nhóm tính năng, Tên tham số', '', L2 + ' STT 14-18'),
    ('T', None, 'Kiểm tra danh sách tính năng theo loại gói', '1. Đối chiếu danh sách tính năng với cấu hình loại gói tại Quản lý loại gói cước',
     'Hiển thị đủ tất cả tính năng thuộc loại gói, sắp xếp tăng dần theo STT hiển thị', '', L2 + ' - Danh sách tính năng'),
    ('T', None, 'Kiểm tra các trường thông tin tính năng read-only', '1. Click vào Mã tính năng, Nhóm tính năng, Tên tính năng, Mô tả',
     'Không cho phép chỉnh sửa', '', L2 + ' STT 14-17'),
    ('T', None, 'Kiểm tra hiển thị Mô tả tính năng', '1. Kiểm tra Mô tả tính năng có nội dung dài', 'Hiển thị full mô tả, không cắt', '',
     L2 + ' STT 17 - Design không có cột Mô tả - ' + BA),
    ('T', None, 'Kiểm tra cuộn ngang khi tính năng có nhiều tham số', '1. Cuộn ngang bảng tính năng', 'Hiển thị đủ các ô tham số, không vỡ layout', '', 'Theo design'),
    ('T', 'Kiểm tra trường Tham số', 'Kiểm tra label ô tham số', '1. Kiểm tra label các ô tham số',
     'Label = Tên tham số + Đơn vị tính, VD "Số cộng đồng (ĐVT: Cộng đồng) *"', '', L2 + ' STT 18'),
    ('T', None, 'Kiểm tra thứ tự tham số trong 1 tính năng', 'ĐK: Tính năng có nhiều tham số\n1. Kiểm tra thứ tự', 'Tham số sắp xếp theo tên A-Z', '', L2 + ' STT 18'),
    ('T', None, 'Kiểm tra tính năng không có tham số', 'ĐK: Loại gói có tính năng không có tham số\n1. Kiểm tra dòng tính năng đó',
     'Không hiển thị ô nhập tham số', '', L2 + ' - Danh sách tính năng'),
    ('T', None, 'Kiểm tra để trống tham số', '1. Để trống 1 ô tham số\n2. Click Lưu', 'Hiển thị lỗi inline: "Vui lòng nhập thông tin" tại ô trống, không lưu', '',
     L2 + ' STT 18, BR03'),
    ('T', None, 'Kiểm tra tham số loại Tiêu hao / Giới hạn đồng thời / Mã đối tác', '1. Nhập giá trị hợp lệ theo rule tham số\n2. Click Lưu',
     'Lưu thành công, quota_value lưu đúng giá trị', '11', L2 + ' STT 18 Th1 - ' + EP + '. Rule chi tiết theo Backlog-Gói cước Tammi [Tổng đài]'),
    ('T', None, 'Kiểm tra tham số loại On/off', '1. Chọn giá trị Có/Không cho tham số on/off\n2. Click Lưu',
     'Lưu thành công, quota_value = CÓ/KHÔNG', '', L2 + ' STT 18 Th2 - ' + EP + '. SRS chưa nêu dạng control, ' + BA),
    ('T', None, 'Kiểm tra nhập tham số không hợp lệ', '1. Nhập chữ, số âm, số vượt DECIMAL(12,2) vào ô tham số',
     'Chặn không cho nhập / báo lỗi theo rule tham số', 'abc / -1 / 10000000000.00', L2 + ' STT 18 - ' + BVA),

    ('G', 'Kiểm tra chức năng'),
    ('T', 'Lưu gói cước', 'Kiểm tra tạo mới gói cước thành công với dữ liệu hợp lệ',
     '1. Nhập đủ các trường bắt buộc hợp lệ\n2. Nhập đủ tham số tính năng\n3. Click Lưu',
     '- Hiển thị popup: icon thành công, tiêu đề "Thêm mới gói cước thành công", nội dung "Bạn đã thêm mới gói cước [Mã gói cước vừa tạo]", button Đóng, icon X\n'
     '- Gói cước được lưu vào CSDL', 'Mã: AUTO_GC_<timestamp>', L2 + ' Basic flow, Popup thông báo'),
    ('T', None, 'Kiểm tra trạng thái gói sau khi tạo', '1. Tạo gói thành công\n2. Kiểm tra gói trên danh sách', 'Gói cước có trạng thái Nháp (DRAFT)', '',
     L2 + ' BR01 - ' + ST),
    ('T', None, 'Kiểm tra dữ liệu gói cước lưu vào CSDL', '1. Tạo gói thành công\n2. Kiểm tra bản ghi plan trong DB',
     'Lưu đúng: plan_type_id, plan_code, description, billing_cycle_value/unit, original_price, currency = VND, plan_role, marketing_tag, distribution_channels, activation_mode, start_time/end_time hoặc Sale_status, is_renew = FALSE, status = DRAFT, created_by/at, updated_by/at',
     '', L2 + ' - c. Dữ liệu cần lưu'),
    ('T', None, 'Kiểm tra dữ liệu quyền lợi (tính năng + tham số) lưu vào CSDL', '1. Tạo gói thành công\n2. Kiểm tra bảng quyền lợi',
     'Mỗi tham số sinh 1 bản ghi: plan_id, feature_id, parameter_id, quota_value đúng giá trị đã nhập', '', L2 + ' - Bản ghi quyền lợi gói cước'),
    ('T', None, 'Kiểm tra lưu thiếu nhiều trường bắt buộc', '1. Để trống tất cả trường\n2. Click Lưu',
     'Hiển thị lỗi inline tại tất cả trường bắt buộc cùng lúc, focus về trường lỗi đầu tiên', '', L2 + ' Exception 5a'),
    ('T', None, 'Kiểm tra click button Lưu liên tục', '1. Nhập dữ liệu hợp lệ\n2. Click Lưu liên tục nhiều lần',
     'Chỉ tạo 1 gói cước, không tạo bản ghi trùng', '', 'NFR 1.3 - chống gửi trùng'),
    ('T', None, 'Kiểm tra gói mới hiển thị trên danh sách', '1. Tạo gói thành công\n2. Quay lại danh sách, mở rộng loại gói tương ứng',
     '- Gói mới hiển thị trong bảng con đúng loại gói, đúng vị trí theo chu kỳ\n- Badge số lượng tăng 1\n- Người cập nhật = Admin tạo', '', L1 + ' STT 9; ' + L2),
    ('T', None, 'Kiểm tra lưu vết audit', '1. Tạo gói thành công\n2. Kiểm tra log kiểm toán', 'Ghi log: người tạo, thời gian, IP, giá trị mới', '', 'NFR 3.3'),
    ('T', 'Popup thông báo thành công', 'Kiểm tra click button Đóng', '1. Tạo gói thành công\n2. Click Đóng',
     'Đóng popup, chuyển hướng về màn hình Danh sách gói cước', '',
     L2 + ' Popup STT 3 - Basic flow B7 ghi điều hướng về màn Chi tiết gói cước, mâu thuẫn - ' + BA),
    ('T', None, 'Kiểm tra click icon X', '1. Tạo gói thành công\n2. Click icon X góc trên', 'Tương tự button Đóng', '', L2 + ' Popup STT 4'),
    ('T', 'Button Back', 'Kiểm tra click Back khi đã nhập dữ liệu', '1. Nhập một số trường\n2. Click icon Back (←)',
     'Hiển thị popup xác nhận: tiêu đề "Huỷ tạo mới gói cước", nội dung "Các thông tin đã nhập sẽ không được lưu. Bạn có chắc chắn muốn thoát?", button Quay lại, Xác nhận',
     '', L2 + ' AF01, Popup confirm huỷ'),
    ('T', None, 'Kiểm tra click Back khi chưa nhập dữ liệu', '1. Không nhập gì\n2. Click icon Back',
     'Hiển thị popup xác nhận huỷ (AF01 áp dụng tại bất kỳ bước nào)', '', L2 + ' AF01 - ' + BA),
    ('T', None, 'Kiểm tra click Xác nhận trên popup huỷ', '1. Nhập dữ liệu\n2. Click Back\n3. Click Xác nhận',
     'Đóng popup, quay về Danh sách gói cước, không lưu dữ liệu, không phát sinh bản ghi mới', '', L2 + ' AF01 - ' + ST),
    ('T', None, 'Kiểm tra click Quay lại trên popup huỷ', '1. Nhập dữ liệu\n2. Click Back\n3. Click Quay lại',
     'Đóng popup, ở lại form, dữ liệu đã nhập được giữ nguyên', '', L2 + ' AF01 - ' + ST),
    ('T', None, 'Kiểm tra dùng nút Back của trình duyệt', '1. Nhập dữ liệu\n2. Click Back của trình duyệt',
     'Xử lý tương tự icon Back (hiển thị popup xác nhận huỷ)', '', 'SRS chưa mô tả - ' + BA),
    ('T', 'Lỗi mạng / hệ thống', 'Kiểm tra lưu khi mất mạng', '1. Nhập dữ liệu hợp lệ\n2. Ngắt mạng\n3. Click Lưu',
     'Hiển thị toast "Thất bại. Vui lòng kiểm tra lại kết nối.", giữ dữ liệu trên form, cho phép thử lại', '', L2 + ' Exception 7a'),
    ('T', None, 'Kiểm tra lưu khi API lỗi hệ thống', 'ĐK: API tạo gói trả lỗi 500\n1. Click Lưu',
     'Hiển thị toast "Hệ thống bận. Vui lòng thử lại sau." kèm mã lỗi, cho phép thử lại', '', L2 + ' Exception 7b'),
    ('T', None, 'Kiểm tra tranh chấp: 2 admin cùng tạo gói trùng mã', 'ĐK: Admin A và B cùng mở form\n1. Cả 2 nhập mã "OAPLUS90"\n2. A click Lưu, sau đó B click Lưu',
     '- Admin A tạo thành công\n- Admin B nhận lỗi "Mã gói đã được sử dụng"', '', L2 + ' BR04 - ' + ST + ' (tranh chấp)'),
    ('T', None, 'Kiểm tra tranh chấp: loại gói bị xoá khi đang tạo gói', 'ĐK: Đang mở form tạo gói thuộc loại gói A\n1. Admin khác xoá loại gói A\n2. Click Lưu',
     'Không cho phép lưu, hiển thị thông báo lỗi', '', 'Pre-condition 2 - SRS chưa mô tả, ' + BA),
    ('T', 'Phân quyền', 'Kiểm tra tạo gói khi không có quyền Quản lý gói cước', 'ĐK: Tài khoản không có quyền\n1. Truy cập trực tiếp URL tạo gói cước',
     'Bị chặn truy cập', '', L2 + ' Pre-condition 1, NFR 3.1 - ' + BA),
]


TECHNIQUES = [
    {
        'title': '1. BẢNG QUYẾT ĐỊNH - Hiển thị thông tin dòng cha theo Loại dịch vụ (UC1 STT 11, 12)',
        'header': ['Điều kiện / Thành phần', 'R1', 'R2', 'R3'],
        'rows': [
            ['Loại dịch vụ = OA', 'Y', 'N', 'Y'],
            ['Chuỗi hiển thị > 20 ký tự', 'N', '-', 'Y'],
            ['Loại hình OA áp dụng', 'Hiện đầy đủ', 'Ẩn', 'Hiện 20 ký tự + "…"'],
            ['Danh mục OA áp dụng', 'Hiện đầy đủ', 'Ẩn', 'Hiện 20 ký tự + "…"'],
        ],
    },
    {
        'title': '2. BẢNG QUYẾT ĐỊNH - Trường phụ thuộc "Bật/tắt trạng thái" (UC2 STT 10-12) - theo design + bảng Trạng thái gói cước, BR02 đang ngược -> BA confirm',
        'header': ['Điều kiện / Thành phần', 'Thủ công', 'Tự động'],
        'rows': [
            ['Trạng thái kinh doanh', 'Hiện, bắt buộc (mặc định Đang kinh doanh)', 'Ẩn'],
            ['Thời gian bắt đầu', 'Ẩn / không bắt buộc', 'Hiện, bắt buộc, > hiện tại'],
            ['Thời gian kết thúc', 'Ẩn / không bắt buộc', 'Hiện, bắt buộc, > Thời gian bắt đầu'],
            ['Dữ liệu lưu', 'Sale_status', 'start_time, end_time'],
        ],
    },
    {
        'title': '3. BẢNG QUYẾT ĐỊNH - Validate trùng Mã gói / Chu kỳ (UC2 BR04, BR06)',
        'header': ['Gói đã tồn tại', 'Cùng loại gói?', 'Trạng thái gói đã tồn tại', 'Kết quả'],
        'rows': [
            ['Trùng mã', 'Bất kỳ', 'Nháp / Đã phát hành / Đang KD / Ngừng KD', 'Lỗi "Mã gói đã được sử dụng"'],
            ['Trùng mã', 'Bất kỳ', 'Đã xoá', 'Cho phép lưu'],
            ['Trùng chu kỳ (quy đổi ngày)', 'Có', 'Nháp / Đã phát hành / Đang KD / Ngừng KD', 'Lỗi "Đã có gói cùng chu kì thuộc cùng loại gói"'],
            ['Trùng chu kỳ (quy đổi ngày)', 'Có', 'Đã xoá', 'Cho phép lưu'],
            ['Trùng chu kỳ (quy đổi ngày)', 'Không', 'Bất kỳ', 'Cho phép lưu'],
        ],
    },
    {
        'title': '4. PHÂN VÙNG TƯƠNG ĐƯƠNG - Quy đổi chu kỳ (BR05: 1 tuần = 7, 1 tháng = 30, 1 năm = 360 ngày)',
        'header': ['Gói đã có', 'Gói tạo mới', 'Quy đổi (ngày)', 'Kết quả'],
        'rows': [
            ['30 Ngày', '1 Tháng', '30 = 30', 'Trùng -> lỗi'],
            ['14 Ngày', '2 Tuần', '14 = 14', 'Trùng -> lỗi'],
            ['12 Tháng', '1 Năm', '360 = 360', 'Trùng -> lỗi'],
            ['1 Tháng', '29 Ngày / 31 Ngày', '30 ≠ 29 / 31', 'Hợp lệ'],
        ],
    },
    {
        'title': '5. PHÂN TÍCH GIÁ TRỊ BIÊN',
        'header': ['Ràng buộc', 'Dưới biên', 'Tại biên', 'Trên biên'],
        'rows': [
            ['Mã gói cước tối đa 50 ký tự', '49 (hợp lệ)', '50 (hợp lệ)', '51 (bị chặn)'],
            ['Mô tả tối đa 500 ký tự', '499 (hợp lệ)', '500 (hợp lệ)', '501 (bị chặn)'],
            ['Tag tối đa 50 ký tự', '49', '50 (hợp lệ)', '51 (bị chặn)'],
            ['Chu kỳ > 0', '0 (lỗi)', '1 (hợp lệ)', '2 (hợp lệ)'],
            ['Giá gốc > 0, DECIMAL(15,2)', '0 (lỗi)', '1 (hợp lệ) / 13 chữ số (hợp lệ)', '14 chữ số (bị chặn)'],
            ['Thời gian bắt đầu > hiện tại', 'Hiện tại - 1 phút (lỗi)', 'Hiện tại (lỗi)', 'Hiện tại + 1 phút (hợp lệ)'],
            ['Thời gian kết thúc > bắt đầu', 'Bắt đầu - 1s (lỗi)', 'Bằng bắt đầu (lỗi)', 'Bắt đầu + 1s (hợp lệ)'],
            ['Số lượng đăng ký giới hạn (0/null = không giới hạn)', '-1 (bị chặn)', '0 (không giới hạn)', '1 (giới hạn 1 lần)'],
            ['Text dòng cha cắt khi > 20 ký tự', '19', '20 (hiện đủ)', '21 (cắt "…")'],
            ['Phân trang 10 dòng/trang', '10 loại gói (1 trang)', '11 loại gói (2 trang)', '112 loại gói (trang cuối 111-112)'],
            ['Badge số lượng gói', '-', '0', '1..n (không tính Đã xoá)'],
        ],
    },
    {
        'title': '6. SƠ ĐỒ CHUYỂN TRẠNG THÁI - Gói cước (bảng Trạng thái gói cước)',
        'header': ['Trạng thái hiện tại', 'Sự kiện', 'Trạng thái kế tiếp', 'TC liên quan'],
        'rows': [
            ['(chưa có)', 'Tạo mới thành công (UC2)', 'Nháp', 'UC2 - Kiểm tra trạng thái gói sau khi tạo'],
            ['(form đang nhập)', 'Back -> Xác nhận', 'Không tạo bản ghi', 'UC2 - Popup huỷ Xác nhận'],
            ['(form đang nhập)', 'Back -> Quay lại', 'Giữ form', 'UC2 - Popup huỷ Quay lại'],
            ['Nháp', 'Phát hành, hiện tại < thời gian bắt đầu', 'Đã phát hành', 'UC1 - hiển thị pill trạng thái'],
            ['Đã phát hành', 'Tự động: hiện tại >= thời gian bắt đầu', 'Đang kinh doanh', 'UC1 - trạng thái tự cập nhật'],
            ['Đang kinh doanh', 'Hiện tại >= thời gian kết thúc / chuyển thủ công', 'Ngừng kinh doanh', 'UC1 - pill Ngừng kinh doanh'],
            ['Nháp / Đã phát hành / Ngừng KD (chưa có giao dịch)', 'Xoá', 'Đã xoá (ẩn khỏi danh sách)', 'UC1 - không hiển thị gói Đã xoá, badge'],
            ['Đang kinh doanh', 'Xoá (KHÔNG hợp lệ)', 'Giữ nguyên', 'UC1 - icon xoá theo trạng thái'],
            ['Loại gói: Đang hoạt động', 'Xoá loại gói', 'Đã xoá (ẩn dòng cha)', 'UC1 - loại gói bị xoá biến mất'],
            ['Dòng cha: Thu gọn', 'Click ⌄', 'Mở rộng', 'UC1 - Nút Đóng/Mở rộng'],
            ['Dòng cha: Mở rộng', 'Click ⌃ / F5', 'Thu gọn', 'UC1 - Nút Đóng/Mở rộng'],
        ],
    },
]
