# -*- coding: utf-8 -*-
"""TC Quản lý gói cước (CMS admin) — UC3 Xem chi tiết gói cước, UC4 Ban hành (Phát hành) gói cước.

Nguồn: SRS "Xây dựng module gói cước" - mục Qly gói cước (UC xem chi tiết gói cước, UC Ban hành gói cước,
bảng Trạng thái gói cước) + ảnh nhúng trong SRS: sơ đồ "Luồng ban hành gói cước", 5 biến thể popup
"Phát hành gói cước?". Màn Chi tiết gói cước không có ảnh trong SRS -> viết theo bảng mô tả màn hình.
Khuôn format: sheet "Quanlykho" của file TC dự án. Dựng bằng build_quanlykho_format.py.
"""


ROWS = [
    # =====================================================================
    ('S',
     'UC3: (CMS admin) Chức năng Xem chi tiết gói cước'),
    ('P',
     'Pre-condition: \nBước 1: Admin đăng nhập thành công vào hệ thống CMS\nBước 2: Click menu Quản lý gói cước > mở rộng 1 loại gói cước\nBước 3: Click icon (i) tại cột Thao tác của 1 gói cước\n'),
    ('G',
     'Kiểm tra gui UI/UX'),
    ('T',
     'Kiểm tra UI',
     'Kiểm tra hiển thị giao diện mặc định',
     '1. Kiểm tra hiển thị màn Chi tiết gói cước',
     '1. Hiển thị màn hình gồm:\n+ Thanh tiêu đề: nút Quay lại, tiêu đề, trạng thái gói, các button thao tác\n+ Khối Thông tin cơ bản\n+ Khối Thuộc tính\n+ Khối Danh sách tính năng theo loại gói',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước - Mô tả màn hình. SRS không có ảnh màn Chi tiết, chưa đối chiếu Figma'),
    ('T',
     None,
     'Kiểm tra tổng thể giao diện màn hình',
     '1. Kiểm tra về bố cục, font chữ, chính tả, màu chữ',
     '1. \n- Các label, có độ dài, rộng và khoảng cách bằng nhau, không xô lệch\n- Các label sử dụng cùng 1 loại font, cỡ chữ, căn lề\n- Kiểm tra tất cả lỗi về chính tả, cấu trúc câu, ngữ pháp trên màn hình\n- Form được bố trí hợp lý và dễ sử dụng',
     '',
     ''),
    ('T',
     None,
     'Kiểm tra thứ tự di chuyển trỏ trên màn hình khi nhấn phím Tab',
     '1. Nhấn Tab liên tục',
     '1. Con trỏ di chuyển lần lượt qua các button thao tác theo thứ tự: Từ trái qua phải, từ trên xuống dưới; không dừng tại các trường read-only có thể nhập',
     '',
     ''),
    ('T',
     None,
     'Kiểm tra thứ tự con trỏ di chuyển ngược lại trên màn hình khi nhấn Shift-Tab',
     '1. Nhấn phím Shift-Tab liên tục',
     '1. Con trỏ di chuyển ngược lại theo thứ tự: từ dưới lên trên, từ phải qua trái',
     '',
     ''),
    ('T',
     None,
     'Kiểm tra giao diện khi thu nhỏ, phóng to',
     '1. Trên màn hình chức năng\n2. Nhấn tổ hợp phím Ctrl -\n3. Nhấn tổ hợp phím Ctrl +',
     '3. Màn hình thu nhỏ, phóng to tương ứng và không bị vỡ giao diện',
     '',
     ''),
    ('G',
     'Thanh tiêu đề (Header)'),
    ('T',
     'Nút Quay lại',
     'Kiểm tra hiển thị nút Quay lại',
     '1. Kiểm tra góc trái thanh tiêu đề',
     '1. Hiển thị icon mũi tên (←) viền tròn',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 1'),
    ('T',
     None,
     'Kiểm tra click nút Quay lại',
     '1. Click nút Quay lại (←)',
     '1. Quay lại màn hình Quản lý gói cước',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 1, AF_01'),
    ('T',
     None,
     'Kiểm tra click Back của trình duyệt',
     '1. Click Back trên trình duyệt',
     '1. Quay lại màn hình Quản lý gói cước',
     '',
     'SRS chỉ mô tả nút ← - Cần BA confirm'),
    ('T',
     'Tiêu đề trang',
     'Kiểm tra text tiêu đề trang',
     '1. Kiểm tra tiêu đề',
     '1. Hiển thị tiêu đề: "Chi tiết gói cước"',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 2'),
    ('T',
     'Trạng thái gói cước',
     'Kiểm tra hiển thị trạng thái Nháp',
     'ĐK: Gói ở trạng thái Nháp\n1. Kiểm tra trạng thái trên thanh tiêu đề',
     '1. Hiển thị trạng thái "Nháp"',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước - Trạng thái gói cước - Kỹ thuật: Phân vùng tương đương'),
    ('T',
     None,
     'Kiểm tra hiển thị trạng thái Đã phát hành',
     'ĐK: Gói ở trạng thái Đã phát hành\n1. Kiểm tra trạng thái',
     '1. Hiển thị trạng thái "Đã phát hành"',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước - Kỹ thuật: Phân vùng tương đương'),
    ('T',
     None,
     'Kiểm tra hiển thị trạng thái Đang kinh doanh',
     'ĐK: Gói ở trạng thái Đang kinh doanh\n1. Kiểm tra trạng thái',
     '1. Hiển thị trạng thái "Đang kinh doanh"',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước - Kỹ thuật: Phân vùng tương đương'),
    ('T',
     None,
     'Kiểm tra hiển thị trạng thái Ngừng kinh doanh',
     'ĐK: Gói ở trạng thái Ngừng kinh doanh\n1. Kiểm tra trạng thái',
     '1. Hiển thị trạng thái "Ngừng kinh doanh"',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước - Kỹ thuật: Phân vùng tương đương'),
    ('T',
     None,
     'Kiểm tra trạng thái trên màn chi tiết khớp với danh sách',
     '1. Ghi nhận trạng thái gói tại danh sách\n2. Mở chi tiết gói đó',
     '2. Trạng thái trên màn chi tiết giống cột Trạng thái tại danh sách',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước - SRS chưa nêu dạng hiển thị (text hay status pill màu) - Cần BA confirm'),
    ('T',
     'Button Chỉnh sửa',
     'Kiểm tra hiển thị button Chỉnh sửa ở mọi trạng thái',
     'ĐK: Lần lượt mở gói Nháp / Đã phát hành / Đang kinh doanh / Ngừng kinh doanh\n1. Kiểm tra button Chỉnh sửa',
     '1. Button "Chỉnh sửa" nền đen bo góc, góc phải, enable ở cả 4 trạng thái',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 3 - Kỹ thuật: Bảng quyết định'),
    ('T',
     None,
     'Kiểm tra click button Chỉnh sửa',
     '1. Click button Chỉnh sửa',
     '1. Điều hướng sang màn Chỉnh sửa gói cước, hiển thị đúng dữ liệu của gói đang xem',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 3'),
    ('T',
     'Button Xoá',
     'Kiểm tra hiển thị button Xoá',
     'ĐK: Lần lượt mở gói ở 4 trạng thái\n1. Kiểm tra button Xoá',
     '1. Button Xoá enable ở tất cả trạng thái',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước - Kỹ thuật: Bảng quyết định. Mâu thuẫn: mô tả màn chi tiết ghi "Enable tại tất cả trạng thái" nhưng bảng Trạng thái gói cước ghi Đang kinh doanh tuyệt đối không được xoá - Cần BA confirm'),
    ('T',
     None,
     'Kiểm tra click button Xoá',
     'ĐK: Gói ở trạng thái Nháp\n1. Click button Xoá',
     '1. Hiển thị popup xác nhận xoá theo UC Xoá gói cước',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước - UC xoá chưa mô tả chi tiết, Cần BA confirm'),
    ('T',
     None,
     'Kiểm tra xoá gói Đang kinh doanh',
     'ĐK: Gói ở trạng thái Đang kinh doanh\n1. Click button Xoá\n2. Xác nhận xoá',
     '2. Hệ thống chặn không cho xoá, gói giữ nguyên trạng thái Đang kinh doanh',
     '',
     'Bảng Trạng thái gói cước STT 3 - Kỹ thuật: Sơ đồ chuyển trạng thái (chuyển không hợp lệ) - Cần BA confirm'),
    ('T',
     'Button Phát hành',
     'Kiểm tra hiển thị button Phát hành khi gói ở trạng thái Nháp',
     'ĐK: Gói ở trạng thái Nháp\n1. Kiểm tra thanh tiêu đề',
     '1. Hiển thị button "Phát hành", trạng thái enable',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước BR_02; Mục QL gói cước - UC Ban hành gói cước BR_01 - Kỹ thuật: Bảng quyết định'),
    ('T',
     None,
     'Kiểm tra ẩn button Phát hành khi gói ở trạng thái Đã phát hành',
     'ĐK: Gói ở trạng thái Đã phát hành\n1. Kiểm tra thanh tiêu đề',
     '1. Không hiển thị button Phát hành',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước BR_02 - Kỹ thuật: Bảng quyết định'),
    ('T',
     None,
     'Kiểm tra ẩn button Phát hành khi gói ở trạng thái Đang kinh doanh',
     'ĐK: Gói ở trạng thái Đang kinh doanh\n1. Kiểm tra thanh tiêu đề',
     '1. Không hiển thị button Phát hành',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước BR_02 - Kỹ thuật: Bảng quyết định'),
    ('T',
     None,
     'Kiểm tra ẩn button Phát hành khi gói ở trạng thái Ngừng kinh doanh',
     'ĐK: Gói ở trạng thái Ngừng kinh doanh\n1. Kiểm tra thanh tiêu đề',
     '1. Không hiển thị button Phát hành',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước BR_02 - Kỹ thuật: Bảng quyết định'),
    ('T',
     None,
     'Kiểm tra click button Phát hành',
     'ĐK: Gói ở trạng thái Nháp\n1. Click button Phát hành',
     '1. Hiển thị popup xác nhận phát hành theo UC Ban hành gói cước',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước - Phát hành'),
    ('G',
     'Khối Thông tin cơ bản'),
    ('T',
     'Chế độ chỉ đọc',
     'Kiểm tra toàn bộ trường ở chế độ chỉ đọc',
     '1. Lần lượt click và thử nhập vào tất cả các trường trên màn chi tiết',
     '1. \n- Tất cả trường nền xám nhạt, disabled\n- Không cho phép nhập, chọn, thêm hoặc xoá dữ liệu',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước BR_01'),
    ('T',
     None,
     'Kiểm tra không thay đổi dữ liệu khi xem chi tiết',
     '1. Ghi nhận updated_at, updated_by của gói trong DB\n2. Mở màn chi tiết, thao tác cuộn/click các trường\n3. Kiểm tra lại DB',
     '3. Không có bản ghi nào thay đổi (updated_at, updated_by giữ nguyên)',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước Post-condition'),
    ('T',
     'Mã gói cước',
     'Kiểm tra hiển thị Mã gói cước',
     '1. Kiểm tra trường Mã gói cước',
     '1. Label "Mã gói cước *", giá trị text in hoa đúng mã đã tạo',
     'OAPLUS30',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 4'),
    ('T',
     'Tag',
     'Kiểm tra hiển thị Tag có dữ liệu',
     'ĐK: Gói có Tag "tammi"\n1. Kiểm tra trường Tag',
     '1. Hiển thị "tammi"',
     'tammi',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 5 - Kỹ thuật: Phân vùng tương đương'),
    ('T',
     None,
     'Kiểm tra hiển thị Tag không có dữ liệu',
     'ĐK: Gói tạo không nhập Tag\n1. Kiểm tra trường Tag',
     '1. Trường Tag hiển thị rỗng, không lỗi layout',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 5 - Kỹ thuật: Phân vùng tương đương. SRS chưa nêu hiển thị rỗng hay "---", Cần BA confirm'),
    ('T',
     'Mô tả',
     'Kiểm tra hiển thị Mô tả',
     '1. Kiểm tra trường Mô tả',
     '1. Hiển thị đúng nội dung mô tả đã nhập, giữ định dạng gạch đầu dòng',
     'oa plus 30 NGÀY',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 6 - Màn chi tiết có * nhưng UC2 ghi Mô tả không bắt buộc - Cần BA confirm'),
    ('T',
     None,
     'Kiểm tra hiển thị Mô tả dài 500 ký tự',
     'ĐK: Gói có mô tả 500 ký tự\n1. Kiểm tra trường Mô tả',
     '1. Hiển thị đủ 500 ký tự (có thanh cuộn nếu vượt khung), không vỡ layout',
     'Chuỗi 500 ký tự',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 6 - Kỹ thuật: Phân tích giá trị biên'),
    ('T',
     'Chu kỳ & Đơn vị',
     'Kiểm tra hiển thị Chu kỳ và Đơn vị',
     '1. Kiểm tra trường Chu kỳ, Đơn vị',
     '1. Hiển thị đúng giá trị và đơn vị đã lưu khi tạo',
     '30 - Ngày',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 7, 8'),
    ('T',
     None,
     'Kiểm tra Đơn vị hiển thị đúng đơn vị đã chọn, không quy đổi',
     'ĐK: Có gói 2 Tuần, 12 Tháng, 1 Năm\n1. Lần lượt mở chi tiết',
     '1. Hiển thị đúng: 2 - Tuần, 12 - Tháng, 1 - Năm',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 8 - Kỹ thuật: Phân vùng tương đương'),
    ('T',
     'Giá gốc',
     'Kiểm tra hiển thị Giá gốc',
     '1. Kiểm tra trường Giá gốc',
     '1. Hiển thị số tiền có dấu chấm phân cách hàng nghìn',
     '1.119.000',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 9'),
    ('T',
     None,
     'Kiểm tra hiển thị giá gốc giá trị lớn',
     'ĐK: Gói có giá 9.999.999.999.999\n1. Kiểm tra Giá gốc',
     '1. Hiển thị đủ "9.999.999.999.999", không vỡ layout',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 9 - Kỹ thuật: Phân tích giá trị biên'),
    ('T',
     'Đơn vị tính',
     'Kiểm tra hiển thị Đơn vị tính',
     '1. Kiểm tra trường Đơn vị tính',
     '1. Hiển thị "VNĐ"',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 10'),
    ('T',
     'Người cập nhật',
     'Kiểm tra hiển thị Người cập nhật',
     '1. Kiểm tra trường Người cập nhật',
     '1. Hiển thị họ tên Admin cập nhật gói gần nhất',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước - Người cập nhật'),
    ('T',
     'Thời gian cập nhật',
     'Kiểm tra hiển thị Thời gian cập nhật',
     '1. Kiểm tra trường Thời gian cập nhật',
     '1. Hiển thị thời gian cập nhật gần nhất, định dạng DD/MM/YYYY HH:mm:ss',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước - SRS chưa nêu định dạng, lấy theo cột danh sách - Cần BA confirm'),
    ('T',
     None,
     'Kiểm tra Người/Thời gian cập nhật sau khi phát hành',
     '1. Admin B phát hành gói Nháp\n2. Kiểm tra màn chi tiết',
     '2. Người cập nhật = Admin B, Thời gian cập nhật = thời điểm phát hành',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Bước 4.2'),
    ('G',
     'Khối Thuộc tính'),
    ('T',
     'Loại hình gói',
     'Kiểm tra hiển thị Loại hình gói = Gói chính',
     'ĐK: Gói là Gói chính\n1. Kiểm tra Loại hình gói',
     '1. Radio "Gói chính" được chọn, "Gói add-on" không chọn, cả 2 disabled',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 11 - Kỹ thuật: Phân vùng tương đương'),
    ('T',
     None,
     'Kiểm tra hiển thị Loại hình gói = Gói add-on',
     'ĐK: Gói là Gói add-on\n1. Kiểm tra Loại hình gói',
     '1. Radio "Gói add-on" được chọn, disabled',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 11 - Kỹ thuật: Phân vùng tương đương'),
    ('T',
     'Kênh bán',
     'Kiểm tra hiển thị Kênh bán 1 kênh',
     'ĐK: Gói chỉ có kênh Web OA\n1. Kiểm tra Kênh bán',
     '1. Checkbox "Web OA" được tích, "Miniapp gói cước TAMMI" không tích, disabled',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 12 - Kỹ thuật: Phân vùng tương đương'),
    ('T',
     None,
     'Kiểm tra hiển thị Kênh bán 2 kênh',
     'ĐK: Gói có cả 2 kênh\n1. Kiểm tra Kênh bán',
     '1. Cả 2 checkbox được tích, disabled',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 12 - Kỹ thuật: Phân vùng tương đương'),
    ('T',
     'Bật/tắt trạng thái',
     'Kiểm tra hiển thị khi Bật/tắt trạng thái = Tự động',
     'ĐK: Gói có Bật/tắt trạng thái = Tự động\n1. Kiểm tra khối Thuộc tính',
     '1. \n- "Tự động" được chọn, disabled\n- Hiển thị Thời gian bắt đầu, Thời gian kết thúc\n- Không hiển thị Trạng thái kinh doanh',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 13-15 - Kỹ thuật: Bảng quyết định'),
    ('T',
     None,
     'Kiểm tra hiển thị khi Bật/tắt trạng thái = Thủ công',
     'ĐK: Gói có Bật/tắt trạng thái = Thủ công\n1. Kiểm tra khối Thuộc tính',
     '1. \n- "Thủ công" được chọn, disabled\n- Hiển thị Trạng thái kinh doanh\n- Không hiển thị Thời gian bắt đầu, kết thúc',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 13 - Kỹ thuật: Bảng quyết định'),
    ('T',
     'Thời gian bắt đầu / kết thúc',
     'Kiểm tra định dạng Thời gian bắt đầu, kết thúc',
     'ĐK: Tự động\n1. Kiểm tra Thời gian bắt đầu, kết thúc',
     '1. Hiển thị đúng thời gian đã lưu, định dạng DD/MM/YYYY hh:mm:ss',
     '01/10/2026 08:00:00',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 14, 15 - giá trị mẫu SRS "11/09/2026" thiếu giờ - Cần BA confirm'),
    ('T',
     'Trạng thái kinh doanh',
     'Kiểm tra hiển thị Trạng thái kinh doanh',
     'ĐK: Thủ công, lần lượt gói có Trạng thái kinh doanh = Đang kinh doanh / Ngừng kinh doanh\n1. Kiểm tra trường',
     '1. Hiển thị đúng giá trị đã lưu: "Đang kinh doanh" / "Ngừng kinh doanh"',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước - Kỹ thuật: Phân vùng tương đương. SRS ghi component "Read-only Date Input" (sai kiểu) - Cần BA confirm'),
    ('T',
     'Số lượng đăng ký giới hạn',
     'Kiểm tra hiển thị Số lượng đăng ký giới hạn có giá trị',
     'ĐK: Gói có giới hạn 1\n1. Kiểm tra trường',
     '1. Hiển thị "1"',
     '1',
     'Mục QL gói cước - UC xem chi tiết gói cước - Kỹ thuật: Phân vùng tương đương'),
    ('T',
     None,
     'Kiểm tra hiển thị Số lượng đăng ký giới hạn khi không giới hạn',
     'ĐK: Gói có giới hạn = null hoặc 0\n1. Kiểm tra trường',
     '1. Hiển thị rỗng / "0" theo quy ước không giới hạn',
     '0 / null',
     'Mục QL gói cước - UC xem chi tiết gói cước - Kỹ thuật: Phân tích giá trị biên. SRS chưa nêu cách hiển thị khi không giới hạn, Cần BA confirm'),
    ('G',
     'Khối Danh sách tính năng theo loại gói'),
    ('T',
     'Loại gói cước',
     'Kiểm tra hiển thị Loại gói cước',
     '1. Kiểm tra trường Loại gói cước',
     '1. Hiển thị tên loại gói cước cha, nền xám nhạt',
     'Plus OA Business',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 16'),
    ('T',
     'Bảng tính năng',
     'Kiểm tra các cột bảng tính năng',
     '1. Kiểm tra header bảng',
     '1. Hiển thị các cột: STT, Mã tính năng, Tên tính năng, Nhóm tính năng, Tham số, Mô tả, Đánh dấu hiển thị',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 17-23. Cột Mô tả, Đánh dấu hiển thị không có ở màn Tạo mới - Cần BA confirm'),
    ('T',
     None,
     'Kiểm tra danh sách tính năng khớp cấu hình loại gói',
     '1. Đối chiếu danh sách tính năng với cấu hình loại gói tại Quản lý loại gói cước',
     '1. Hiển thị đủ tính năng thuộc loại gói, không thừa, không thiếu',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước - Danh sách tính năng'),
    ('T',
     'Cột STT',
     'Kiểm tra cột STT',
     '1. Kiểm tra cột STT',
     '1. Số thứ tự tăng dần 1, 2, 3..., căn giữa',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 17'),
    ('T',
     'Cột Mã tính năng',
     'Kiểm tra cột Mã tính năng',
     '1. Kiểm tra cột Mã tính năng',
     '1. Hiển thị mã tính năng, căn trái',
     'TM30',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 18'),
    ('T',
     'Cột Tên tính năng',
     'Kiểm tra hiển thị cột Tên tính năng',
     '1. Kiểm tra cột Tên tính năng',
     '1. Text màu xanh lam dạng hyperlink, căn trái',
     'Sách nói',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 19'),
    ('T',
     None,
     'Kiểm tra click Tên tính năng',
     '1. Click vào Tên tính năng',
     '1. Điều hướng đến màn Chi tiết tính năng tương ứng',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 19 - SRS chưa nêu đích của link, Cần BA confirm'),
    ('T',
     'Cột Nhóm tính năng',
     'Kiểm tra cột Nhóm tính năng',
     '1. Kiểm tra cột Nhóm tính năng',
     '1. Hiển thị tên nhóm tính năng',
     'Cộng đồng',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 20'),
    ('T',
     'Cột Tham số',
     'Kiểm tra hiển thị tham số',
     '1. Kiểm tra cột Tham số',
     '1. Mỗi tham số là 1 ô con: Tên tham số + (ĐVT: đơn vị) + giá trị bên dưới, read-only',
     'Số cộng đồng (ĐVT: Cộng đồng) *: 11',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 21'),
    ('T',
     None,
     'Kiểm tra giá trị tham số khớp dữ liệu đã lưu',
     '1. Đối chiếu giá trị tham số với bảng quyền lợi (quota_value) trong DB',
     '1. Giá trị hiển thị khớp DB',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 21'),
    ('T',
     None,
     'Kiểm tra tham số loại On/off',
     'ĐK: Tính năng có tham số On/off\n1. Kiểm tra ô tham số',
     '1. Hiển thị giá trị Có/Không đúng dữ liệu đã lưu',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 21 - Kỹ thuật: Phân vùng tương đương. SRS chưa nêu dạng hiển thị, Cần BA confirm'),
    ('T',
     None,
     'Kiểm tra tính năng có nhiều tham số',
     'ĐK: Tính năng có ≥ 3 tham số\n1. Kiểm tra dòng tính năng, cuộn ngang',
     '1. Hiển thị đủ các ô tham số, không vỡ layout',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 21'),
    ('T',
     'Cột Mô tả',
     'Kiểm tra mô tả ngắn ≤ 2 hàng',
     'ĐK: Mô tả tính năng hiển thị trong 2 hàng\n1. Kiểm tra cột Mô tả',
     '1. Hiển thị đầy đủ, không có "…"',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 22 - Kỹ thuật: Phân tích giá trị biên'),
    ('T',
     None,
     'Kiểm tra mô tả dài hơn 2 hàng',
     'ĐK: Mô tả tính năng dài hơn 2 hàng\n1. Kiểm tra cột Mô tả',
     '1. Hiển thị tối đa 2 hàng, phần còn lại thay bằng "…"',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 22 - Kỹ thuật: Phân tích giá trị biên'),
    ('T',
     None,
     'Kiểm tra tooltip khi hover mô tả',
     'ĐK: Mô tả dài hơn 2 hàng\n1. Hover vào ô Mô tả',
     '1. Hiển thị tooltip chứa toàn bộ mô tả',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 22'),
    ('T',
     'Đánh dấu hiển thị',
     'Kiểm tra tính năng được đánh dấu hiển thị',
     'ĐK: Tính năng có cờ hiển thị = true\n1. Kiểm tra dòng tính năng',
     '1. Tickbox được tích, dòng tính năng hiển thị bình thường',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 23 - Kỹ thuật: Bảng quyết định'),
    ('T',
     None,
     'Kiểm tra tính năng không được đánh dấu hiển thị',
     'ĐK: Tính năng có cờ hiển thị = false\n1. Kiểm tra dòng tính năng',
     '1. Tickbox không tích, dòng tính năng hiển thị ở trạng thái disable',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước STT 23 - Kỹ thuật: Bảng quyết định. Nguồn cờ: is_display của PLAN_TYPE_FEATURE - Cần BA confirm'),
    ('G',
     'Kiểm tra ngoại lệ & phi chức năng'),
    ('T',
     'Lỗi mạng',
     'Kiểm tra mở chi tiết khi mất mạng',
     '1. Ngắt mạng\n2. Click icon (i) tại 1 gói cước',
     '2. Hiển thị toast "Thất bại. Vui lòng kiểm tra lại kết nối." và cho phép thử lại',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước Exception 2a'),
    ('T',
     'Lỗi hệ thống',
     'Kiểm tra mở chi tiết khi API lỗi hệ thống',
     'ĐK: API chi tiết trả lỗi 500\n1. Click icon (i)',
     '1. Hiển thị toast "Hệ thống bận. Vui lòng thử lại sau." kèm mã lỗi, cho phép thử lại',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước Exception 2b'),
    ('T',
     'Gói không tồn tại',
     'Kiểm tra mở chi tiết gói đã bị xoá',
     'ĐK: Đang ở danh sách, admin khác xoá gói A\n1. Click icon (i) của gói A (hoặc mở URL chi tiết của gói A)',
     '1. Không hiển thị dữ liệu gói, báo gói không tồn tại / quay về danh sách',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước Pre-condition 2 - SRS chưa mô tả, Cần BA confirm'),
    ('T',
     'Dữ liệu',
     'Kiểm tra toàn bộ dữ liệu khớp CSDL',
     '1. Mở chi tiết 1 gói\n2. Đối chiếu từng trường với bản ghi plan và bảng quyền lợi',
     '2. Toàn bộ dữ liệu khớp CSDL',
     '',
     'Mục QL gói cước - UC xem chi tiết gói cước Basic flow B2'),
    ('T',
     'Phân quyền',
     'Kiểm tra truy cập URL chi tiết khi không có quyền',
     'ĐK: Tài khoản không có quyền phân hệ Gói cước\n1. Mở trực tiếp URL chi tiết gói',
     '1. Bị chặn truy cập',
     '',
     'NFR 3.1 - Cần BA confirm'),
    # =====================================================================
    ('S',
     'UC4: (CMS admin) Chức năng Ban hành (Phát hành) gói cước'),
    ('P',
     'Pre-condition: \nBước 1: Admin đăng nhập CMS, có quyền quản lý, phát hành gói cước\nBước 2: Gói cước đang ở trạng thái Nháp, thông tin và tham số tính năng đã cấu hình hợp lệ\nBước 3: Mở màn Chi tiết gói cước của gói đó\n'),
    ('G',
     'Kiểm tra gui UI/UX popup'),
    ('T',
     'Kiểm tra UI',
     'Kiểm tra giao diện chung của popup phát hành',
     '1. Click button Phát hành\n2. Kiểm tra popup',
     '2. Hiển thị popup:\n+ Icon cảnh báo (!)\n+ Tiêu đề: "Phát hành gói cước?"\n+ Icon X góc trên bên phải\n+ Nội dung thông báo có {Mã gói} in đậm\n+ Button phụ (viền) bên trái, button "Xác nhận" (nền đen) bên phải',
     '',
     'Mục QL gói cước - UC Ban hành gói cước - Mô tả màn hình. Mâu thuẫn: bảng SRS ghi tiêu đề "Xác nhận phát hành gói cước", nội dung chứa [Tên gói + Mã gói], nút "Hủy"; design ghi "Phát hành gói cước?", chỉ {Mã gói}, nút "Sửa ngày..." thay cho Hủy - Cần BA confirm'),
    ('T',
     None,
     'Kiểm tra tổng thể giao diện popup',
     '1. Kiểm tra về bố cục, font chữ, chính tả, màu chữ',
     '1. \n- Các label, có độ dài, rộng và khoảng cách bằng nhau, không xô lệch\n- Các label sử dụng cùng 1 loại font, cỡ chữ, căn lề\n- Kiểm tra tất cả lỗi về chính tả, cấu trúc câu, ngữ pháp trên màn hình\n- Form được bố trí hợp lý và dễ sử dụng',
     '',
     ''),
    ('T',
     None,
     'Kiểm tra popup là modal',
     'ĐK: Popup đang hiển thị\n1. Click vào vùng màn chi tiết phía sau popup',
     '1. Không thao tác được màn phía sau; popup không đóng',
     '',
     'SRS chưa nêu click ra ngoài có đóng popup không - Cần BA confirm'),
    ('G',
     'Luồng Bật/tắt trạng thái = Tự động'),
    ('T',
     'TH1.1: Hiện tại < Thời gian bắt đầu',
     'Kiểm tra popup khi thời gian hiện tại < thời gian bắt đầu',
     'ĐK: Tự động, bắt đầu = hiện tại + 1 ngày, kết thúc = hiện tại + 30 ngày\n1. Click Phát hành',
     '1. Hiển thị popup:\n+ Icon cảnh báo (!)\n+ Tiêu đề: "Phát hành gói cước?"\n+ Icon X góc trên bên phải\n+ Nội dung: "Gói cước của bạn sẽ chuyển trạng thái sang Đã phát hành, người mua có thể nhìn thấy gói cước khi đến thời gian bắt đầu. Bạn có chắc chắn muốn phát hành gói cước {Mã gói} không?"\n+ Button "Sửa ngày bắt đầu", "Xác nhận"',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Bước 2 TH1.1 - Kỹ thuật: Bảng quyết định'),
    ('T',
     None,
     'Kiểm tra Xác nhận phát hành khi hiện tại < thời gian bắt đầu',
     'ĐK: Như TC trên\n1. Click Phát hành\n2. Click Xác nhận',
     '2. \n- Đóng popup, hiển thị toast "Phát hành gói cước thành công"\n- Ở lại màn chi tiết, trạng thái gói = "Đã phát hành"\n- Ẩn button Phát hành',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Bước 4 TH1.1 - Kỹ thuật: Sơ đồ chuyển trạng thái (Nháp → Đã phát hành)'),
    ('T',
     None,
     'Kiểm tra gói Đã phát hành chưa hiển thị trên kênh bán',
     'ĐK: Gói vừa chuyển Đã phát hành\n1. Mở giao diện mua gói trên kênh đã cấu hình (Web OA / Miniapp)',
     '1. Gói chưa hiển thị cho người mua',
     '',
     'Bảng Trạng thái gói cước STT 2'),
    ('T',
     None,
     'Kiểm tra click "Sửa ngày bắt đầu"',
     'ĐK: Như TH1.1\n1. Click Phát hành\n2. Click "Sửa ngày bắt đầu"',
     '2. Điều hướng đến màn Chỉnh sửa gói cước; trạng thái gói vẫn là Nháp',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Exception 3a - SRS chưa nêu có focus sẵn vào trường Thời gian bắt đầu không, Cần BA confirm'),
    ('T',
     None,
     'Kiểm tra biên: thời gian bắt đầu = hiện tại + 1 phút',
     'ĐK: Tự động, bắt đầu = hiện tại + 1 phút\n1. Click Phát hành\n2. Click Xác nhận ngay',
     '2. Popup nội dung TH1.1, gói chuyển "Đã phát hành"',
     'Bắt đầu = hiện tại + 1 phút',
     'Mục QL gói cước - UC Ban hành gói cước TH1.1 - Kỹ thuật: Phân tích giá trị biên'),
    ('T',
     'Chuyển trạng thái tự động (scheduler)',
     'Kiểm tra gói Đã phát hành tự chuyển Đang kinh doanh khi đến thời gian bắt đầu',
     'ĐK: Gói Đã phát hành, Tự động, bắt đầu = hiện tại + 2 phút\n1. Chờ qua thời gian bắt đầu\n2. Tải lại màn chi tiết và danh sách',
     '2. \n- Trạng thái gói = "Đang kinh doanh"\n- Gói hiển thị trên giao diện mua của các kênh đã cấu hình',
     '',
     'Bảng Trạng thái gói cước STT 2, 3 - Kỹ thuật: Sơ đồ chuyển trạng thái. SRS chưa nêu chu kỳ quét của hệ thống, Cần BA confirm'),
    ('T',
     None,
     'Kiểm tra gói Đang kinh doanh tự chuyển Ngừng kinh doanh khi đến thời gian kết thúc',
     'ĐK: Gói Đang kinh doanh, Tự động, kết thúc = hiện tại + 2 phút\n1. Chờ qua thời gian kết thúc\n2. Tải lại màn chi tiết',
     '2. \n- Trạng thái gói = "Ngừng kinh doanh"\n- Gói không còn hiển thị để mua mới; thuê bao cũ vẫn giữ quyền lợi',
     '',
     'Bảng Trạng thái gói cước STT 4 - Kỹ thuật: Sơ đồ chuyển trạng thái'),
    ('T',
     'TH1.2: Hiện tại ≥ Thời gian bắt đầu',
     'Kiểm tra popup khi thời gian hiện tại ≥ thời gian bắt đầu',
     'ĐK: Tự động, bắt đầu = hiện tại - 1 ngày, kết thúc = hiện tại + 30 ngày\n1. Click Phát hành',
     '1. Hiển thị popup:\n+ Icon cảnh báo (!)\n+ Tiêu đề: "Phát hành gói cước?"\n+ Icon X góc trên bên phải\n+ Nội dung: "Gói cước của bạn đã đến thời gian bắt đầu nên trạng thái sẽ chuyển sang Đang kinh doanh vì vậy người mua có thể nhìn thấy gói cước. Bạn có chắc chắn muốn phát hành gói cước {Mã gói} không?"\n+ Button "Sửa ngày bắt đầu", "Xác nhận"',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Bước 2 TH1.2 - Kỹ thuật: Bảng quyết định'),
    ('T',
     None,
     'Kiểm tra Xác nhận phát hành khi hiện tại ≥ thời gian bắt đầu',
     'ĐK: Như TC trên\n1. Click Phát hành\n2. Click Xác nhận',
     '2. \n- Đóng popup, toast "Phát hành gói cước thành công"\n- Trạng thái gói = "Đang kinh doanh"\n- Ẩn button Phát hành',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Bước 4 TH1.2 - Kỹ thuật: Sơ đồ chuyển trạng thái (Nháp → Đang kinh doanh)'),
    ('T',
     None,
     'Kiểm tra gói Đang kinh doanh xuất hiện ngay trên kênh bán',
     'ĐK: Gói vừa phát hành sang Đang kinh doanh, kênh bán = Web OA\n1. Mở giao diện mua gói trên Web OA\n2. Mở giao diện mua gói trên Miniapp',
     '1. Gói hiển thị ngay trên Web OA\n2. Không hiển thị trên Miniapp (không thuộc kênh cấu hình)',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Post-condition 2 - Kỹ thuật: Phân vùng tương đương'),
    ('T',
     None,
     'Kiểm tra biên: thời gian bắt đầu = đúng thời điểm hiện tại',
     'ĐK: Tự động, thời gian bắt đầu trùng thời điểm click Phát hành\n1. Click Phát hành',
     '1. Popup nội dung TH1.2 (hiện tại ≥ bắt đầu), xác nhận thì gói chuyển "Đang kinh doanh"',
     '',
     'Mục QL gói cước - UC Ban hành gói cước TH1.2 - Kỹ thuật: Phân tích giá trị biên'),
    ('T',
     None,
     'Kiểm tra click "Sửa ngày bắt đầu" tại popup TH1.2',
     'ĐK: Như TH1.2\n1. Click Phát hành\n2. Click "Sửa ngày bắt đầu"',
     '2. Điều hướng đến màn Chỉnh sửa gói cước; trạng thái vẫn Nháp',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Exception 3a'),
    ('T',
     'TH1.3: Hiện tại ≥ Thời gian kết thúc',
     'Kiểm tra popup khi thời gian hiện tại ≥ thời gian kết thúc',
     'ĐK: Tự động, bắt đầu = hiện tại - 30 ngày, kết thúc = hiện tại - 1 ngày\n1. Click Phát hành',
     '1. Hiển thị popup:\n+ Icon cảnh báo (!)\n+ Tiêu đề: "Phát hành gói cước?"\n+ Icon X góc trên bên phải\n+ Nội dung: "Gói cước của bạn đã đến thời gian kết thúc nên trạng thái sẽ chuyển sang Ngừng kinh doanh vì vậy người mua sẽ không nhìn thấy gói cước. Bạn có chắc chắn muốn phát hành gói cước {Mã gói} không?"\n+ Button "Sửa ngày kết thúc", "Xác nhận"',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Bước 2 TH1.3 - Kỹ thuật: Bảng quyết định. Điều kiện TH1.2 (≥ bắt đầu) và TH1.3 (≥ kết thúc) chồng lấn - SRS chưa nêu TH1.3 được ưu tiên, Cần BA confirm'),
    ('T',
     None,
     'Kiểm tra Xác nhận phát hành khi hiện tại ≥ thời gian kết thúc',
     'ĐK: Như TC trên\n1. Click Phát hành\n2. Click Xác nhận',
     '2. \n- Đóng popup, toast "Phát hành gói cước thành công"\n- Trạng thái gói = "Ngừng kinh doanh"\n- Gói không hiển thị trên kênh bán',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Bước 4 TH1.3 - Kỹ thuật: Sơ đồ chuyển trạng thái (Nháp → Ngừng kinh doanh). Bảng trạng thái chỉ ghi Ngừng KD chuyển từ Đang KD/Đã phát hành, thiếu Nháp - Cần BA confirm'),
    ('T',
     None,
     'Kiểm tra click "Sửa ngày kết thúc"',
     'ĐK: Như TH1.3\n1. Click Phát hành\n2. Click "Sửa ngày kết thúc"',
     '2. Điều hướng đến màn Chỉnh sửa gói cước; trạng thái vẫn Nháp',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Exception 3a'),
    ('T',
     None,
     'Kiểm tra biên: thời gian kết thúc = đúng thời điểm hiện tại',
     'ĐK: Tự động, thời gian kết thúc trùng thời điểm click Phát hành\n1. Click Phát hành',
     '1. Popup nội dung TH1.3, xác nhận thì gói chuyển "Ngừng kinh doanh"',
     '',
     'Mục QL gói cước - UC Ban hành gói cước TH1.3 - Kỹ thuật: Phân tích giá trị biên'),
    ('T',
     None,
     'Kiểm tra biên: thời gian kết thúc = hiện tại + 1 phút',
     'ĐK: Tự động, bắt đầu đã qua, kết thúc = hiện tại + 1 phút\n1. Click Phát hành',
     '1. Popup nội dung TH1.2 (chưa đến thời gian kết thúc), xác nhận thì gói chuyển "Đang kinh doanh"',
     '',
     'Mục QL gói cước - UC Ban hành gói cước TH1.2/TH1.3 - Kỹ thuật: Phân tích giá trị biên'),
    ('T',
     'Mốc thời gian đổi khi popup đang mở',
     'Kiểm tra trạng thái khi đến thời gian bắt đầu trong lúc popup TH1.1 đang mở',
     'ĐK: Tự động, bắt đầu = hiện tại + 1 phút\n1. Click Phát hành (popup TH1.1)\n2. Chờ qua thời gian bắt đầu\n3. Click Xác nhận',
     '3. Gói chuyển trạng thái theo thời điểm xác nhận (Đang kinh doanh), không kẹt ở Đã phát hành',
     '',
     'Mục QL gói cước - UC Ban hành gói cước - SRS chưa nêu so thời gian tại lúc mở popup hay lúc xác nhận - Cần BA confirm'),
    ('G',
     'Luồng Bật/tắt trạng thái = Thủ công'),
    ('T',
     'Th2.1: Trạng thái KD = Đang kinh doanh',
     'Kiểm tra popup khi trạng thái kinh doanh = Đang kinh doanh',
     'ĐK: Thủ công, Trạng thái kinh doanh = Đang kinh doanh\n1. Click Phát hành',
     '1. Hiển thị popup:\n+ Icon cảnh báo (!)\n+ Tiêu đề: "Phát hành gói cước?"\n+ Icon X góc trên bên phải\n+ Nội dung: "Trạng thái kinh doanh của gói cước là Đang kinh doanh vì vậy người mua có thể nhìn thấy. Bạn có chắc chắn muốn phát hành gói cước {Mã gói} không?"\n+ Button "Sửa trạng thái kinh doanh", "Xác nhận"',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Bước 2 Th2.1 - Kỹ thuật: Bảng quyết định'),
    ('T',
     None,
     'Kiểm tra Xác nhận phát hành khi trạng thái KD = Đang kinh doanh',
     'ĐK: Như TC trên\n1. Click Phát hành\n2. Click Xác nhận',
     '2. \n- Đóng popup, toast "Phát hành gói cước thành công"\n- Trạng thái gói = "Đang kinh doanh"\n- Gói hiển thị ngay trên kênh bán đã cấu hình',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Bước 4 Th2.1 - Kỹ thuật: Sơ đồ chuyển trạng thái (Nháp → Đang kinh doanh)'),
    ('T',
     None,
     'Kiểm tra click "Sửa trạng thái kinh doanh" (Th2.1)',
     'ĐK: Như Th2.1\n1. Click Phát hành\n2. Click "Sửa trạng thái kinh doanh"',
     '2. Điều hướng đến màn Chỉnh sửa gói cước; trạng thái vẫn Nháp',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Exception 3a'),
    ('T',
     'Th2.2: Trạng thái KD = Ngừng kinh doanh',
     'Kiểm tra popup khi trạng thái kinh doanh = Ngừng kinh doanh',
     'ĐK: Thủ công, Trạng thái kinh doanh = Ngừng kinh doanh\n1. Click Phát hành',
     '1. Hiển thị popup:\n+ Icon cảnh báo (!)\n+ Tiêu đề: "Phát hành gói cước?"\n+ Icon X góc trên bên phải\n+ Nội dung: "Trạng thái kinh doanh gói cước là Ngừng kinh doanh vì vậy người mua sẽ không nhìn thấy. Bạn có chắc chắn muốn phát hành gói cước {Mã gói} không?"\n+ Button "Sửa trạng thái kinh doanh", "Xác nhận"',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Bước 2 Th2.2 - Kỹ thuật: Bảng quyết định'),
    ('T',
     None,
     'Kiểm tra Xác nhận phát hành khi trạng thái KD = Ngừng kinh doanh',
     'ĐK: Như TC trên\n1. Click Phát hành\n2. Click Xác nhận',
     '2. \n- Đóng popup, toast "Phát hành gói cước thành công"\n- Trạng thái gói = "Ngừng kinh doanh"\n- Gói không hiển thị trên kênh bán',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Bước 4 Th2.2 - Kỹ thuật: Sơ đồ chuyển trạng thái (Nháp → Ngừng kinh doanh)'),
    ('T',
     None,
     'Kiểm tra click "Sửa trạng thái kinh doanh" (Th2.2)',
     'ĐK: Như Th2.2\n1. Click Phát hành\n2. Click "Sửa trạng thái kinh doanh"',
     '2. Điều hướng đến màn Chỉnh sửa gói cước; trạng thái vẫn Nháp',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Exception 3a'),
    ('T',
     'Thủ công không phụ thuộc thời gian',
     'Kiểm tra phát hành Thủ công không xét thời gian',
     'ĐK: Thủ công, Trạng thái KD = Đang kinh doanh (gói không có thời gian bắt đầu/kết thúc)\n1. Click Phát hành\n2. Xác nhận',
     '2. Chỉ căn cứ Trạng thái kinh doanh: gói chuyển "Đang kinh doanh", không hiển thị popup theo thời gian',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Bước 2 Th2 - Kỹ thuật: Phân vùng tương đương'),
    ('G',
     'Huỷ / đóng popup'),
    ('T',
     'Icon X',
     'Kiểm tra click icon X trên popup',
     '1. Click Phát hành\n2. Click icon X',
     '2. \n- Đóng popup, ở lại màn chi tiết\n- Trạng thái gói giữ nguyên "Nháp", không lưu thay đổi\n- Button Phát hành vẫn hiển thị',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Exception 3b, AF_01 - Kỹ thuật: Sơ đồ chuyển trạng thái'),
    ('T',
     None,
     'Kiểm tra icon X ở cả 5 biến thể popup',
     'ĐK: Lần lượt tạo gói theo TH1.1, TH1.2, TH1.3, Th2.1, Th2.2\n1. Click Phát hành\n2. Click icon X',
     '2. Cả 5 trường hợp đều đóng popup, gói giữ trạng thái Nháp',
     '',
     'Mục QL gói cước - UC Ban hành gói cước AF_01 - Kỹ thuật: Bảng quyết định'),
    ('T',
     'Button Hủy',
     'Kiểm tra button Hủy trên popup',
     '1. Click Phát hành\n2. Click Hủy',
     '2. Đóng popup, gói giữ trạng thái Nháp',
     '',
     'Mục QL gói cước - UC Ban hành gói cước STT 4, AF_01 - Design không có nút Hủy (thay bằng nút "Sửa ngày..."), nếu design đúng thì TC này N/A - Cần BA confirm'),
    ('T',
     'Phím Esc',
     'Kiểm tra nhấn phím Esc khi popup đang mở',
     '1. Click Phát hành\n2. Nhấn Esc',
     '2. Đóng popup, gói giữ trạng thái Nháp',
     '',
     'SRS chưa mô tả - Cần BA confirm'),
    ('T',
     None,
     'Kiểm tra mở lại popup sau khi huỷ',
     '1. Click Phát hành\n2. Click X\n3. Click Phát hành lần nữa',
     '3. Popup hiển thị lại đúng nội dung theo trường hợp của gói',
     '',
     'Mục QL gói cước - UC Ban hành gói cước AF_01'),
    ('G',
     'Kiểm tra chức năng'),
    ('T',
     'Lưu dữ liệu',
     'Kiểm tra dữ liệu lưu sau khi phát hành',
     '1. Phát hành thành công 1 gói\n2. Kiểm tra bản ghi plan trong DB',
     '2. \n- status = trạng thái mới đúng rule\n- updated_by = Admin phát hành\n- updated_at = thời điểm xác nhận\n- Các trường khác không đổi',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Bước 4.2'),
    ('T',
     None,
     'Kiểm tra danh sách cập nhật sau khi phát hành',
     '1. Phát hành thành công 1 gói\n2. Quay lại màn Quản lý gói cước',
     '2. Cột Trạng thái, Thời gian cập nhật, Người cập nhật của gói hiển thị giá trị mới',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Post-condition 1'),
    ('T',
     None,
     'Kiểm tra lưu vết audit khi phát hành',
     '1. Phát hành 1 gói\n2. Kiểm tra log kiểm toán',
     '2. Ghi log: người thao tác, thời gian, IP, trạng thái cũ (Nháp) → mới',
     '',
     'NFR 3.3'),
    ('T',
     'Chống thao tác trùng',
     'Kiểm tra click Xác nhận liên tục',
     '1. Click Phát hành\n2. Click Xác nhận liên tục nhiều lần',
     '2. Chỉ gửi 1 yêu cầu, gói chuyển trạng thái 1 lần, chỉ 1 toast thành công',
     '',
     'NFR 1.3'),
    ('T',
     'Toast thông báo',
     'Kiểm tra toast thành công',
     '1. Phát hành thành công\n2. Kiểm tra toast',
     '2. Hiển thị toast "Phát hành gói cước thành công", tự ẩn sau vài giây',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Bước 4.3'),
    ('T',
     'Chuyển trạng thái không hợp lệ',
     'Kiểm tra không thể phát hành lại gói đã phát hành',
     'ĐK: Gói ở trạng thái Đã phát hành / Đang kinh doanh / Ngừng kinh doanh\n1. Mở chi tiết gói\n2. Gọi API phát hành trực tiếp với plan_id của gói',
     '1. Không hiển thị button Phát hành\n2. API trả lỗi, trạng thái gói không đổi',
     '',
     'Mục QL gói cước - UC Ban hành gói cước BR_01 - Kỹ thuật: Sơ đồ chuyển trạng thái (chuyển không hợp lệ)'),
    ('T',
     None,
     'Kiểm tra phát hành gói đã bị xoá',
     'ĐK: Admin A đang mở chi tiết gói Nháp; Admin B xoá gói\n1. Admin A click Phát hành > Xác nhận',
     '1. Không cho phép phát hành, hiển thị thông báo lỗi; gói giữ Đã xoá',
     '',
     'Kỹ thuật: Sơ đồ chuyển trạng thái (tranh chấp) - SRS chưa mô tả, Cần BA confirm'),
    ('T',
     'Tranh chấp',
     'Kiểm tra 2 admin cùng phát hành 1 gói',
     'ĐK: Admin A và B cùng mở chi tiết 1 gói Nháp\n1. A click Phát hành > Xác nhận\n2. B click Phát hành > Xác nhận',
     '1. A phát hành thành công, toast "Phát hành gói cước thành công"\n2. B nhận thông báo lỗi, không phát sinh chuyển trạng thái lần 2',
     '',
     'Kỹ thuật: Sơ đồ chuyển trạng thái (tranh chấp) - Cần BA confirm'),
    ('T',
     None,
     'Kiểm tra phát hành khi dữ liệu gói vừa bị admin khác sửa',
     'ĐK: A mở chi tiết gói (Thủ công, Đang KD); B sửa gói thành Thủ công, Ngừng KD\n1. A click Phát hành > Xác nhận',
     '1. Hệ thống xử lý theo dữ liệu mới nhất trong DB (gói chuyển Ngừng kinh doanh) hoặc yêu cầu A tải lại trang',
     '',
     'Kỹ thuật: Sơ đồ chuyển trạng thái (tranh chấp) - Cần BA confirm'),
    ('T',
     'Dữ liệu chưa hợp lệ',
     'Kiểm tra phát hành gói thiếu tham số tính năng',
     'ĐK: Loại gói vừa được thêm tính năng mới sau khi gói Nháp đã tạo (gói thiếu tham số tính năng đó)\n1. Click Phát hành > Xác nhận',
     '1. Chặn phát hành, báo gói chưa cấu hình đủ tham số',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Pre-condition 3 - SRS chưa nêu validate khi phát hành, Cần BA confirm'),
    ('T',
     'Lỗi mạng',
     'Kiểm tra Xác nhận khi mất mạng',
     '1. Click Phát hành\n2. Ngắt mạng\n3. Click Xác nhận',
     '3. \n- Hiển thị toast "Thất bại. Vui lòng kiểm tra lại kết nối."\n- Gói giữ Nháp, cho phép click lại',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Exception 4a'),
    ('T',
     None,
     'Kiểm tra phát hành lại sau khi có mạng',
     'ĐK: Vừa gặp lỗi mạng\n1. Bật mạng\n2. Click lại Phát hành > Xác nhận',
     '2. Phát hành thành công, toast "Phát hành gói cước thành công"',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Exception 4a'),
    ('T',
     'Lỗi hệ thống',
     'Kiểm tra Xác nhận khi API lỗi hệ thống',
     'ĐK: API phát hành trả lỗi 500\n1. Click Phát hành > Xác nhận',
     '1. \n- Hiển thị toast "Hệ thống bận. Vui lòng thử lại sau." kèm mã lỗi\n- Gói giữ Nháp, cho phép click lại',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Exception 4b'),
    ('T',
     'Phân quyền',
     'Kiểm tra admin không có quyền phát hành',
     'ĐK: Tài khoản chỉ có quyền xem gói cước\n1. Mở chi tiết gói Nháp',
     '1. Không hiển thị button Phát hành / gọi API bị từ chối',
     '',
     'Mục QL gói cước - UC Ban hành gói cước Pre-condition 1, NFR 3.1 - Cần BA confirm'),
    ('T',
     'Hậu phát hành',
     'Kiểm tra hạn chế chỉnh sửa sau khi gói Đã phát hành',
     'ĐK: Gói vừa chuyển Đã phát hành\n1. Click Chỉnh sửa\n2. Thử sửa Mã gói, Loại gói, Tham số',
     '2. Không cho sửa Mã gói, Loại gói, Tham số',
     '',
     'Bảng Trạng thái gói cước STT 2 - thuộc UC Chỉnh sửa, kiểm tra hệ quả của phát hành'),
    ('T',
     None,
     'Kiểm tra hạn chế chỉnh sửa sau khi gói Đang kinh doanh',
     'ĐK: Gói vừa chuyển Đang kinh doanh\n1. Click Chỉnh sửa\n2. Thử sửa Mã gói, Chu kỳ, Loại hình',
     '2. Không cho sửa Mã gói, Chu kỳ, Loại hình',
     '',
     'Bảng Trạng thái gói cước STT 3'),
]


TECHNIQUES = [{'title': '1. BẢNG QUYẾT ĐỊNH - Button trên màn Chi tiết theo trạng thái gói (UC3 STT 3, BR_02)',
  'header': ['Thành phần / Trạng thái', 'Nháp', 'Đã phát hành', 'Đang kinh doanh', 'Ngừng kinh doanh'],
  'rows': [['Button Chỉnh sửa', 'Hiện, enable', 'Hiện, enable', 'Hiện, enable', 'Hiện, enable'],
           ['Button Xoá (SRS màn chi tiết)', 'Enable', 'Enable', 'Enable', 'Enable'],
           ['Xoá (bảng Trạng thái gói)',
            'Được xoá',
            'Chỉ khi chưa có giao dịch',
            'KHÔNG được xoá',
            'Chỉ khi chưa có giao dịch'],
           ['Button Phát hành', 'Hiện', 'Ẩn', 'Ẩn', 'Ẩn']]},
 {'title': '2. BẢNG QUYẾT ĐỊNH - Trường hiển thị theo Bật/tắt trạng thái (UC3 STT 13-15)',
  'header': ['Thành phần', 'Tự động', 'Thủ công'],
  'rows': [['Thời gian bắt đầu', 'Hiện', 'Ẩn'],
           ['Thời gian kết thúc', 'Hiện', 'Ẩn'],
           ['Trạng thái kinh doanh', 'Ẩn', 'Hiện']]},
 {'title': '3. BẢNG QUYẾT ĐỊNH - Phát hành gói cước (UC4 Bước 2, 4)',
  'header': ['Điều kiện / Kết quả', 'TH1.1', 'TH1.2', 'TH1.3', 'Th2.1', 'Th2.2'],
  'rows': [['Bật/tắt trạng thái', 'Tự động', 'Tự động', 'Tự động', 'Thủ công', 'Thủ công'],
           ['Hiện tại so với Bắt đầu', '< Bắt đầu', '≥ Bắt đầu', '≥ Bắt đầu', '-', '-'],
           ['Hiện tại so với Kết thúc', '< Kết thúc', '< Kết thúc', '≥ Kết thúc', '-', '-'],
           ['Trạng thái kinh doanh', '-', '-', '-', 'Đang KD', 'Ngừng KD'],
           ['Button phụ trên popup',
            'Sửa ngày bắt đầu',
            'Sửa ngày bắt đầu',
            'Sửa ngày kết thúc',
            'Sửa trạng thái KD',
            'Sửa trạng thái KD'],
           ['Trạng thái sau Xác nhận',
            'Đã phát hành',
            'Đang kinh doanh',
            'Ngừng kinh doanh',
            'Đang kinh doanh',
            'Ngừng kinh doanh'],
           ['Hiển thị trên kênh bán', 'Không (tới giờ bắt đầu mới hiện)', 'Có', 'Không', 'Có', 'Không']]},
 {'title': '4. PHÂN TÍCH GIÁ TRỊ BIÊN - Mốc thời gian khi phát hành (Tự động)',
  'header': ['Mốc', 'Dưới biên', 'Tại biên', 'Trên biên'],
  'rows': [['Thời gian bắt đầu',
            'Hiện tại = Bắt đầu - 1 phút -> TH1.1 Đã phát hành',
            'Hiện tại = Bắt đầu -> TH1.2 Đang KD',
            'Hiện tại = Bắt đầu + 1 ngày -> TH1.2 Đang KD'],
           ['Thời gian kết thúc',
            'Hiện tại = Kết thúc - 1 phút -> TH1.2 Đang KD',
            'Hiện tại = Kết thúc -> TH1.3 Ngừng KD',
            'Hiện tại = Kết thúc + 1 ngày -> TH1.3 Ngừng KD'],
           ['Mô tả tính năng (UC3 STT 22)', '≤ 2 hàng -> hiện đủ', '2 hàng -> hiện đủ', '> 2 hàng -> "…" + tooltip'],
           ['Giới hạn đăng ký (UC3)', '-', '0/null -> không giới hạn', '1 -> giới hạn 1 lần']]},
 {'title': '5. SƠ ĐỒ CHUYỂN TRẠNG THÁI - Gói cước khi phát hành & sau phát hành',
  'header': ['Trạng thái hiện tại', 'Sự kiện', 'Trạng thái kế tiếp', 'Hợp lệ?'],
  'rows': [['Nháp', 'Phát hành - TH1.1', 'Đã phát hành', 'Hợp lệ'],
           ['Nháp', 'Phát hành - TH1.2 / Th2.1', 'Đang kinh doanh', 'Hợp lệ'],
           ['Nháp', 'Phát hành - TH1.3 / Th2.2', 'Ngừng kinh doanh', 'Hợp lệ (bảng trạng thái chưa ghi, BA confirm)'],
           ['Nháp', 'Popup: X / Hủy / Esc', 'Nháp', 'Giữ nguyên'],
           ['Nháp', 'Popup: Sửa ngày bắt đầu/kết thúc/trạng thái KD', 'Nháp (sang màn Chỉnh sửa)', 'Giữ nguyên'],
           ['Nháp', 'Xác nhận khi lỗi mạng/hệ thống', 'Nháp', 'Giữ nguyên'],
           ['Đã phát hành', 'Hệ thống quét: hiện tại ≥ bắt đầu', 'Đang kinh doanh', 'Hợp lệ'],
           ['Đang kinh doanh', 'Hệ thống quét: hiện tại ≥ kết thúc', 'Ngừng kinh doanh', 'Hợp lệ'],
           ['Đã phát hành / Đang KD / Ngừng KD',
            'Phát hành',
            '(không đổi)',
            'KHÔNG hợp lệ - không có button, API từ chối'],
           ['Đang kinh doanh', 'Xoá', '(không đổi)', 'KHÔNG hợp lệ'],
           ['Đã xoá', 'Phát hành (admin khác đã xoá)', '(không đổi)', 'KHÔNG hợp lệ - tranh chấp'],
           ['Nháp', '2 admin cùng Xác nhận', 'Chuyển 1 lần', 'Tranh chấp - lần 2 bị từ chối']]}]
