# -*- coding: utf-8 -*-
# ('S', title) | ('P', text) | ('T', func, purpose, steps, expected, data, note)

ROWS = [
 ('S','Điểm vào màn hình Chi tiết hoàn tiền'),
 ('P','Pre-condition: \nBước 1: Người dùng đăng nhập thành công vào hệ thống bằng tài khoản đã eKYC và đã khai báo tài khoản ngân hàng\nBước 2: Người dùng click vào icon Đơn hàng trên navigation\nBước 3: Có đơn hàng đã gửi yêu cầu Trả hàng/Hoàn tiền (đơn hàng ở trạng thái Trả hàng)'),

 ('T','Điều hướng vào màn Chi tiết hoàn tiền','Check điều hướng sau khi gửi yêu cầu trả hàng/hoàn tiền thành công',
  '1. Tại màn Yêu cầu trả hàng/hoàn tiền nhập đầy đủ thông tin\n2. Click button Gửi yêu cầu',
  'Hệ thống hiển thị toast message gửi yêu cầu thành công và điều hướng sang màn hình Chi tiết hoàn tiền','','Luồng màn hình mục 1.3.4'),
 ('T',None,'Check điều hướng từ card đơn hàng tại tab Trả hàng',
  '1. Vào màn Danh sách đơn hàng\n2. Click tab Trả hàng\n3. Click vào dòng trạng thái Yêu cầu trả hàng/hoàn tiền đang chờ xử lý',
  'Hệ thống điều hướng sang màn hình Chi tiết hoàn tiền của đơn hàng tương ứng','','Mục 1.3.1 STT 16'),
 ('T',None,'Check điều hướng từ màn Chi tiết đơn hàng trạng thái Trả hàng',
  '1. Click vào 1 item đơn hàng tại tab Trả hàng\n2. Click vào vùng Mô tả trạng thái yêu cầu trả hàng/hoàn tiền',
  'Hệ thống điều hướng sang màn hình Chi tiết hoàn tiền','','Mục 1.3.2.6 STT 9'),
 ('T',None,'Check điều hướng từ CTA Chi tiết hoàn tiền tại tab Đã huỷ',
  'ĐK: Đơn hàng đã thanh toán và bị huỷ\n1. Click tab Đã huỷ\n2. Click button Chi tiết hoàn tiền',
  'Hệ thống điều hướng sang màn hình Chi tiết hoàn tiền','','Mục 1.3.1 STT 10'),
 ('T',None,'Check hiển thị màn Chi tiết hoàn tiền với từng trạng thái yêu cầu',
  'Lần lượt mở màn Chi tiết hoàn tiền với các trạng thái:\n1. Chờ phê duyệt\n2. Đã phê duyệt - chờ chọn phương thức trả hàng\n3. Đã lấy hàng - chờ hoàn tiền\n4. Hoàn tiền thành công\n5. Hoàn tiền thất bại\n6. Từ chối hoàn tiền',
  'Mỗi trạng thái hiển thị đúng banner mô tả, tag trạng thái, tiến trình hoàn tiền và các CTA tương ứng theo design','6 đơn hàng ở 6 trạng thái khác nhau','Kỹ thuật: Sơ đồ chuyển trạng thái (State Transition) - TC bao quát'),

 ('S','Màn hình Chi tiết hoàn tiền'),
 ('P','Pre-condition: \nBước 1: Người dùng đăng nhập thành công vào hệ thống bằng tài khoản đã eKYC và đã khai báo tài khoản ngân hàng\nBước 2: Người dùng click vào icon Đơn hàng trên navigation\nBước 3: Click tab Trả hàng, chọn 1 đơn hàng có yêu cầu Trả hàng/Hoàn tiền\nBước 4: Điều hướng vào màn hình Chi tiết hoàn tiền'),

 ('T','Giao diện tổng quan','Kiểm tra giao diện tổng quan màn hình Chi tiết hoàn tiền',
  '1. Kiểm tra title của màn hình\n2. Kiểm tra hiển thị đầy đủ thông tin của các label trên màn hình',
  '1. Hiển thị title: Chi tiết hoàn tiền, icon Back, icon ... và icon X\n2. Hiển thị đầy đủ các vùng theo design:\n+ Thông tin tiền hoàn\n+ Tiến trình hoàn tiền\n+ Button Huỷ yêu cầu (theo trạng thái)\n+ Chọn phương thức trả hàng (theo trạng thái)\n+ Bạn cần hỗ trợ\n+ Thông tin sản phẩm','',''),
 ('T',None,'Kiểm tra hiển thị giao diện màn Chi tiết hoàn tiền',
  '1. Kiểm tra về bố cục\n2. Kiểm tra font chữ, cỡ chữ, màu chữ\n3. Kiểm tra chính tả.',
  '1. Bố cục\n- Các label, tag, button được bố trí thẳng hàng, có độ dài, độ rộng, và khoảng cách bằng nhau, không xô lệch.\n- Form được bố trí hợp lý và dễ sử dụng.\n2. Font chữ, màu chữ\n- Các label, text sử dụng cùng 1 loại font chữ, cỡ chữ\n- Màu chữ: giống như giao diện Figma\n3. Chính tả: Không có lỗi về chính tả, cấu trúc câu, ngữ pháp trên màn hình.','',''),
 ('T',None,'Kiểm tra dữ liệu khi màn hình để chế độ sáng',
  '1. Người dùng cài đặt chế độ sáng trên máy\n2. Kiểm tra giao diện của màn hình',
  'Dữ liệu hiển thị bình thường, rõ nét và không vỡ giao diện','',''),
 ('T',None,'Kiểm tra dữ liệu khi màn hình để chế độ tối',
  '1. Người dùng cài đặt chế độ tối trên máy\n2. Kiểm tra giao diện của màn hình',
  'Dữ liệu hiển thị bình thường, rõ nét và không vỡ giao diện','',''),
 ('T',None,'Kiểm tra hiển thị khi thay đổi cỡ chữ hệ thống lớn nhất',
  '1. Cài đặt cỡ chữ lớn nhất trên thiết bị\n2. Mở màn Chi tiết hoàn tiền',
  'Các label, tag, button hiển thị đầy đủ nội dung, không bị cắt chữ, không vỡ giao diện','',''),
 ('T',None,'Check khi click icon Back',
  '1. Click icon Back',
  'Hệ thống quay về màn hình trước đó (Chi tiết đơn hàng/Danh sách đơn hàng)','',''),
 ('T',None,'Check khi click icon X',
  '1. Click icon X trên header',
  'Hệ thống đóng màn Chi tiết hoàn tiền và quay về màn hình trước đó','',''),

 ('T','Thông tin tiền hoàn','Check hiển thị banner mô tả khi yêu cầu đang chờ phê duyệt',
  'ĐK: Yêu cầu trả hàng/hoàn tiền đang chờ xử lý\n1. Check vùng Thông tin tiền hoàn',
  'Hiển thị banner thông báo yêu cầu đang chờ phê duyệt kèm thời gian xử lý dự kiến 24h kể từ khi gửi yêu cầu','','Mục 1.3.2.6 STT 9'),
 ('T',None,'Check hiển thị banner mô tả khi yêu cầu đã được phê duyệt',
  'ĐK: Nhà bán/Admin đã phê duyệt yêu cầu\n1. Check vùng Thông tin tiền hoàn',
  'Hiển thị banner: "Yêu cầu trả hàng/hoàn tiền của bạn đã được phê duyệt. Thêm thông tin trả hàng để tiến hành Trả hàng và Hoàn tiền."','',''),
 ('T',None,'Check hiển thị banner mô tả khi đã hoàn tiền thành công',
  'ĐK: Hệ thống hoàn tiền thành công\n1. Check vùng Thông tin tiền hoàn',
  'Hiển thị banner: "Hệ thống Vipo F2C đã hoàn tất xử lý hoàn tiền cho đơn hàng của bạn. Bạn vui lòng liên hệ ngân hàng phát hành để kiểm tra lịch trình giao dịch cụ thể."','',''),
 ('T',None,'Check hiển thị banner mô tả khi yêu cầu bị từ chối',
  'ĐK: Nhà bán/Admin từ chối yêu cầu\n1. Check vùng Thông tin tiền hoàn',
  'Hiển thị banner từ chối kèm lý do từ chối của Sàn/Nhà bán','',''),
 ('T',None,'Check hiển thị banner mô tả khi hoàn tiền thất bại',
  'ĐK: Hệ thống hoàn tiền cho Buyer thất bại\n1. Check vùng Thông tin tiền hoàn',
  'Hiển thị banner hoàn tiền thất bại kèm lý do thất bại','','Mục 1.3.2.6 STT 9'),
 ('T',None,'Check hiển thị số tiền hoàn',
  '1. Check vùng Số tiền hoàn',
  'Hiển thị label Số tiền hoàn và số tiền hoàn của đơn hàng, định dạng có dấu chấm ngăn cách hàng nghìn kèm hậu tố đ (VD: 125.000 đ)','Đơn hàng 125.000 đ',''),
 ('T',None,'Check hiển thị tag trạng thái hoàn tiền',
  'Lần lượt mở đơn ở các trạng thái: chờ phê duyệt, chờ trả hàng, chờ hoàn tiền, hoàn tiền thành công, hoàn tiền thất bại\n1. Check tag trạng thái dưới số tiền hoàn',
  'Hiển thị đúng tag trạng thái tương ứng với trạng thái hiện tại của yêu cầu theo design (VD: Chờ trả hàng)','','Kỹ thuật: Phân vùng tương đương theo trạng thái'),
 ('T',None,'Check hiển thị tài khoản nhận tiền hoàn khi thanh toán bằng mã QR',
  'ĐK: Đơn hàng thanh toán bằng QR chuyển khoản\n1. Check thông tin tài khoản tại vùng Thông tin tiền hoàn',
  'Hiển thị tên ngân hàng và 4 số cuối tài khoản ngân hàng liên kết mà người mua đã chọn (VD: Viettinbank *1092)','',''),
 ('T',None,'Check hiển thị tài khoản nhận tiền hoàn khi thanh toán qua Zalopay',
  'ĐK: Đơn hàng thanh toán qua Zalopay\n1. Check thông tin tài khoản tại vùng Thông tin tiền hoàn',
  'Hiển thị TKNH thanh toán qua Zalopay','','SRS ghi: phát triển sau khi tích hợp xong Zalopay - dự kiến N/A phase này'),
 ('T',None,'Check khi click Xem chi tiết tiền hoàn',
  '1. Click vào icon mũi tên/Xem chi tiết tiền hoàn cạnh số tiền hoàn',
  'Hiển thị bottom sheet Chi tiết hoàn tiền gồm:\n+ Title: Chi tiết hoàn tiền\n+ Tổng số tiền hoàn\n+ Giá sản phẩm sau khuyến mãi\n+ Voucher giảm giá\n+ Số tiền hoàn nhận được\n+ Button Đã hiểu','',''),
 ('T',None,'Check số tiền tại bottom sheet Chi tiết hoàn tiền',
  'ĐK: Đơn hàng giá sau khuyến mãi 145.000 đ, voucher giảm 20.000 đ\n1. Click Xem chi tiết tiền hoàn\n2. Đối chiếu các dòng tiền',
  'Giá sản phẩm sau khuyến mãi: 145.000 đ\nVoucher giảm giá: -20.000 đ\nSố tiền hoàn nhận được: 125.000 đ = 145.000 - 20.000','Giá 145.000 đ - Voucher 20.000 đ','Kỹ thuật: Kiểm tra công thức tính tiền hoàn'),
 ('T',None,'Check bottom sheet Chi tiết hoàn tiền với đơn hàng không dùng voucher',
  'ĐK: Đơn hàng không áp dụng voucher\n1. Click Xem chi tiết tiền hoàn',
  'Dòng Voucher giảm giá hiển thị 0 đ hoặc ẩn theo design, Số tiền hoàn nhận được = Giá sản phẩm sau khuyến mãi','Đơn không voucher','Kỹ thuật: Phân vùng tương đương (có/không voucher)'),
 ('T',None,'Check khi click button Đã hiểu tại bottom sheet Chi tiết hoàn tiền',
  '1. Click Xem chi tiết tiền hoàn\n2. Click button Đã hiểu',
  'Đóng bottom sheet, quay lại màn Chi tiết hoàn tiền','',''),
 ('T',None,'Check khi đóng bottom sheet Chi tiết hoàn tiền bằng thao tác vuốt',
  '1. Click Xem chi tiết tiền hoàn\n2. Vuốt xuống hoặc click vùng ngoài bottom sheet',
  'Đóng bottom sheet, không làm thay đổi dữ liệu yêu cầu','',''),

 ('T','Tiến trình hoàn tiền','Check hiển thị tiến trình khi yêu cầu được phê duyệt',
  'ĐK: Yêu cầu đã được Nhà bán/Admin phê duyệt, ĐVVC chưa lấy hàng\n1. Check vùng Tiến trình hoàn tiền',
  'Hiển thị 3 mốc: Chấp nhận hoàn tiền (có ngày, tick xanh) - Trả hàng cho người bán (---) - Đã hoàn tiền (---)','','Kỹ thuật: Sơ đồ chuyển trạng thái'),
 ('T',None,'Check hiển thị tiến trình khi ĐVVC đã lấy hàng hoàn thành công',
  'ĐK: ĐVVC lấy hàng hoàn thành công\n1. Check vùng Tiến trình hoàn tiền',
  'Mốc Trả hàng cho người bán chuyển sang trạng thái hoàn thành và hiển thị ngày, mốc Đã hoàn tiền vẫn hiển thị ---','','Kỹ thuật: Sơ đồ chuyển trạng thái'),
 ('T',None,'Check hiển thị tiến trình khi hoàn tiền thành công',
  'ĐK: Hệ thống hoàn tiền cho Buyer thành công\n1. Check vùng Tiến trình hoàn tiền',
  'Cả 3 mốc Chấp nhận hoàn tiền - Trả hàng cho người bán - Đã hoàn tiền đều hoàn thành và hiển thị ngày','','Kỹ thuật: Sơ đồ chuyển trạng thái'),
 ('T',None,'Check hiển thị tiến trình khi hoàn tiền thất bại',
  'ĐK: Hệ thống hoàn tiền cho Buyer thất bại\n1. Check vùng Tiến trình hoàn tiền',
  'Mốc thứ 3 hiển thị Hoàn tiền thất bại với màu đỏ kèm ngày, 2 mốc trước giữ trạng thái hoàn thành','','Kỹ thuật: Sơ đồ chuyển trạng thái'),
 ('T',None,'Check hiển thị tiến trình khi yêu cầu bị từ chối',
  'ĐK: Nhà bán/Admin từ chối yêu cầu\n1. Check vùng Tiến trình hoàn tiền',
  'Hiển thị mốc Từ chối hoàn tiền màu đỏ kèm ngày, không hiển thị các mốc trả hàng và hoàn tiền','','Kỹ thuật: Sơ đồ chuyển trạng thái'),
 ('T',None,'Check format thời gian tại tiến trình hoàn tiền',
  '1. Check ngày hiển thị tại các mốc của tiến trình hoàn tiền',
  'Thời gian hiển thị đúng format DD/MM (VD: 19/01)','Ngày phê duyệt 19/01/2026','Mục 1.3.4 STT 3'),
 ('T',None,'Check hiển thị mốc chưa đạt tới',
  'ĐK: Yêu cầu mới được phê duyệt\n1. Check các mốc chưa hoàn thành',
  'Các mốc chưa hoàn thành hiển thị icon xám và dấu --- thay cho ngày','',''),
 ('T',None,'Check cập nhật tiến trình khi trạng thái thay đổi từ hệ thống',
  '1. Mở màn Chi tiết hoàn tiền ở trạng thái Chờ trả hàng\n2. Nhà bán/ĐVVC cập nhật lấy hàng thành công\n3. Kéo xuống để làm mới màn hình',
  'Tiến trình hoàn tiền và tag trạng thái cập nhật theo trạng thái mới nhất','','Kỹ thuật: Sơ đồ chuyển trạng thái'),

 ('T','Button Huỷ yêu cầu','Check hiển thị button Huỷ yêu cầu khi yêu cầu đang chờ phê duyệt',
  'ĐK: Yêu cầu đang chờ xử lý, chưa bàn giao hàng cho ĐVVC\n1. Check button Huỷ yêu cầu',
  'Hiển thị button Huỷ yêu cầu','','Kỹ thuật: Bảng quyết định (hiển thị CTA theo trạng thái)'),
 ('T',None,'Check hiển thị button Huỷ yêu cầu khi đã phê duyệt nhưng chưa bàn giao hàng',
  'ĐK: Yêu cầu đã được phê duyệt, ĐVVC chưa lấy hàng\n1. Check button Huỷ yêu cầu',
  'Hiển thị button Huỷ yêu cầu','','Kỹ thuật: Bảng quyết định'),
 ('T',None,'Check ẩn button Huỷ yêu cầu sau khi ĐVVC đã lấy hàng',
  'ĐK: ĐVVC đã lấy hàng hoàn thành công\n1. Check button Huỷ yêu cầu',
  'Không hiển thị button Huỷ yêu cầu','','Mục 1.3.4 STT 4 - Kỹ thuật: Bảng quyết định'),
 ('T',None,'Check ẩn button Huỷ yêu cầu khi hoàn tiền thành công',
  'ĐK: Yêu cầu đã hoàn tiền thành công\n1. Check button Huỷ yêu cầu',
  'Không hiển thị button Huỷ yêu cầu','','Kỹ thuật: Bảng quyết định'),
 ('T',None,'Check ẩn button Huỷ yêu cầu khi yêu cầu bị từ chối',
  'ĐK: Yêu cầu bị Nhà bán/Admin từ chối\n1. Check button Huỷ yêu cầu',
  'Không hiển thị button Huỷ yêu cầu','','Kỹ thuật: Bảng quyết định'),
 ('T',None,'Check khi click button Huỷ yêu cầu',
  '1. Click button Huỷ yêu cầu',
  'Hiển thị popup gồm:\n+ Nội dung: Bạn có chắc muốn huỷ Yêu cầu trả hàng/hoàn tiền\n+ Button Huỷ\n+ Button Đồng ý','',''),
 ('T',None,'Check khi click button Huỷ tại popup xác nhận',
  '1. Click button Huỷ yêu cầu\n2. Click button Huỷ tại popup',
  'Đóng popup, giữ nguyên yêu cầu trả hàng/hoàn tiền và trạng thái đơn hàng','',''),
 ('T',None,'Check khi click vùng ngoài popup xác nhận huỷ yêu cầu',
  '1. Click button Huỷ yêu cầu\n2. Click vùng bên ngoài popup',
  'Đóng popup, không thực hiện huỷ yêu cầu','','BA confirm popup có cho đóng bằng click outside hay không'),
 ('T',None,'Check khi click button Đồng ý để huỷ yêu cầu',
  '1. Click button Huỷ yêu cầu\n2. Click button Đồng ý',
  'Hệ thống huỷ yêu cầu, điều hướng về màn hình Chi tiết đơn hàng và hiển thị bottom sheet: Yêu cầu trả hàng/hoàn tiền đã được huỷ thành công','',''),
 ('T',None,'Check nội dung bottom sheet sau khi huỷ yêu cầu lần 1',
  'ĐK: Đơn hàng huỷ yêu cầu lần 1\n1. Huỷ yêu cầu thành công\n2. Check nội dung bottom sheet',
  'Hiển thị:\n+ Bạn đã gửi Yêu cầu trả hàng/hoàn tiền lần đầu vào [DD/MM/YYYY]\n+ Bạn còn được Yêu cầu trả hàng/hoàn tiền 1 lần nữa, thời gian trễ nhất vào [DD/MM/YYYY]\n+ Đơn hàng của bạn sẽ được chuyển về trạng thái Đã giao\n+ Button Đã hiểu','',''),
 ('T',None,'Check ngày trễ nhất hiển thị tại bottom sheet sau khi huỷ',
  'ĐK: ĐVVC giao hàng thành công ngày 20/09/2026\n1. Huỷ yêu cầu thành công\n2. Check ngày trễ nhất có thể gửi yêu cầu',
  'Hiển thị ngày = ngày giao hàng thành công + 5 ngày (25/09/2026), format DD/MM/YYYY','Ngày giao: 20/09/2026','Kỹ thuật: Phân tích giá trị biên (mốc 5 ngày)'),
 ('T',None,'Check khi click button Đã hiểu tại bottom sheet huỷ yêu cầu',
  '1. Huỷ yêu cầu thành công\n2. Click button Đã hiểu',
  'Đóng bottom sheet, hiển thị màn hình Chi tiết đơn hàng','',''),
 ('T',None,'Check trạng thái đơn hàng sau khi huỷ yêu cầu',
  '1. Huỷ yêu cầu thành công\n2. Quay về màn Danh sách đơn hàng',
  'Đơn hàng chuyển về trạng thái Đã giao, hiển thị tại tab Đã giao và không còn tại tab Trả hàng','','Kỹ thuật: Sơ đồ chuyển trạng thái'),
 ('T',None,'Check nội dung hiển thị tại Chi tiết đơn hàng sau khi huỷ yêu cầu lần 1',
  '1. Huỷ yêu cầu thành công\n2. Vào màn Chi tiết đơn hàng',
  'Hiển thị: Yêu cầu trả hàng/hoàn tiền đã bị huỷ - Tag: Yêu cầu bị huỷ - Text: Bạn còn 1 lượt gửi yêu cầu, trễ nhất vào [DD/MM]','','Mục 1.3.1 STT 14'),
 ('T',None,'Check nội dung hiển thị sau khi huỷ yêu cầu lần 2',
  'ĐK: Đơn hàng đã huỷ yêu cầu 1 lần\n1. Gửi yêu cầu lần 2\n2. Huỷ yêu cầu lần 2\n3. Vào màn Chi tiết đơn hàng',
  'Hiển thị text: Bạn đã hết lượt gửi yêu cầu trả hàng/hoàn tiền, không cho phép gửi yêu cầu mới','','Kỹ thuật: Phân tích giá trị biên (số lượt 1-2-3)'),
 ('T',None,'Check huỷ yêu cầu khi mất kết nối mạng',
  '1. Ngắt kết nối mạng\n2. Click button Huỷ yêu cầu\n3. Click Đồng ý',
  'Hệ thống hiển thị thông báo lỗi kết nối, yêu cầu không bị huỷ, trạng thái đơn hàng giữ nguyên','',''),
 ('T',None,'Check huỷ yêu cầu khi API trả về lỗi',
  '1. Giả lập API huỷ yêu cầu trả về lỗi 500\n2. Click button Huỷ yêu cầu\n3. Click Đồng ý',
  'Hệ thống hiển thị thông báo lỗi thân thiện, không crash app, yêu cầu giữ nguyên trạng thái','',''),
 ('T',None,'Check huỷ yêu cầu khi ĐVVC vừa lấy hàng thành công',
  '1. Mở màn Chi tiết hoàn tiền khi chưa bàn giao hàng\n2. ĐVVC cập nhật đã lấy hàng thành công\n3. Click button Huỷ yêu cầu (chưa refresh màn hình)',
  'Hệ thống chặn huỷ, hiển thị thông báo yêu cầu đã chuyển trạng thái và làm mới lại màn hình','','Kỹ thuật: Sơ đồ chuyển trạng thái - trường hợp tranh chấp trạng thái'),

 ('T','Chọn phương thức trả hàng','Check ẩn vùng Chọn phương thức trả hàng khi yêu cầu chưa được phê duyệt',
  'ĐK: Yêu cầu đang chờ xử lý\n1. Check vùng Chọn phương thức trả hàng',
  'Không hiển thị vùng Chọn phương thức trả hàng','','Kỹ thuật: Bảng quyết định'),
 ('T',None,'Check hiển thị vùng Chọn phương thức trả hàng khi yêu cầu được phê duyệt',
  'ĐK: Nhà bán/Admin đã phê duyệt yêu cầu\n1. Check vùng Chọn phương thức trả hàng',
  'Hiển thị:\n+ Title: Chọn phương thức trả hàng\n+ Lựa chọn Đơn vị vận chuyển đến lấy hàng (mặc định được chọn)\n+ Lựa chọn Trả hàng tại bưu cục\n+ Button Xác nhận','',''),
 ('T',None,'Check lựa chọn mặc định của phương thức trả hàng',
  'ĐK: Yêu cầu vừa được phê duyệt\n1. Check radio button tại vùng Chọn phương thức trả hàng',
  'Mặc định chọn Đơn vị vận chuyển đến lấy hàng','','Mục 1.3.4 STT 5'),
 ('T',None,'Check hiển thị thông tin người gửi tại phương thức ĐVVC đến lấy hàng',
  '1. Check thông tin hiển thị trong ô Đơn vị vận chuyển đến lấy hàng',
  'Hiển thị: Tên người gửi | Số điện thoại | Địa chỉ lấy hàng và text Đơn sẽ được lấy trong 1-3 ngày kể từ [ngày]','',''),
 ('T',None,'Check thời gian dự kiến ĐVVC đến lấy hàng',
  'ĐK: Yêu cầu được phê duyệt ngày 11/08/2026\n1. Check text thời gian dự kiến lấy hàng',
  'Hiển thị: Đơn sẽ được lấy trong 1-3 ngày kể từ 11 Tháng 8 (tính từ ngày yêu cầu được phê duyệt)','Ngày phê duyệt: 11/08/2026','Mục 1.3.4 STT 5'),
 ('T',None,'Check khi chọn phương thức Trả hàng tại bưu cục',
  '1. Click chọn Trả hàng tại bưu cục',
  'Phase 1 chưa phát triển tính năng Trả hàng tại bưu cục','','SRS ghi phase 1 chưa làm - BA confirm hành vi: disable hay hiển thị thông báo'),
 ('T',None,'Check khi click vào địa chỉ lấy hàng',
  '1. Click vào vùng địa chỉ trong ô Đơn vị vận chuyển đến lấy hàng',
  'Hệ thống điều hướng sang màn hình thay đổi địa chỉ (luồng tương tự UC2 - Quản lý địa chỉ nhận hàng)','',''),
 ('T',None,'Check cập nhật địa chỉ lấy hàng sau khi thay đổi',
  '1. Click vào địa chỉ\n2. Chọn địa chỉ khác\n3. Xác nhận thay đổi',
  'Màn Chi tiết hoàn tiền cập nhật đúng tên người gửi, số điện thoại và địa chỉ vừa chọn','Địa chỉ 2 trong sổ địa chỉ',''),
 ('T',None,'Check khi click button Xác nhận phương thức trả hàng',
  '1. Giữ nguyên lựa chọn Đơn vị vận chuyển đến lấy hàng\n2. Click button Xác nhận',
  'Hệ thống ghi nhận phương thức trả hàng, hiển thị vùng Phương thức trả hàng kèm button Thay đổi và vùng Hướng dẫn trả hàng','',''),
 ('T',None,'Check hiển thị sau khi đã xác nhận phương thức trả hàng',
  'ĐK: Đã xác nhận phương thức trả hàng\n1. Check vùng Phương thức trả hàng',
  'Hiển thị: Đơn vị vận chuyển đến lấy hàng, tên người gửi, SĐT, địa chỉ, text Bạn sẽ được lấy trong 1-3 ngày kể từ [ngày] và button Thay đổi','',''),
 ('T',None,'Check không chọn phương thức trả hàng trong vòng 24h kể từ khi phê duyệt',
  'ĐK: Yêu cầu được phê duyệt, người dùng không chọn phương thức trả hàng quá 24h\n1. Mở lại màn Chi tiết hoàn tiền',
  'Yêu cầu trả hàng/hoàn tiền bị huỷ (tác nhân huỷ là Sàn), đơn hàng chuyển về trạng thái Đã giao và trừ 1 lượt yêu cầu','','Mục 1.3.1 STT 17 - Kỹ thuật: Phân tích giá trị biên (mốc 24h)'),
 ('T',None,'Check chọn phương thức trả hàng ngay trước mốc 24h',
  'ĐK: Yêu cầu được phê duyệt cách đây 23 giờ 55 phút\n1. Chọn phương thức trả hàng\n2. Click Xác nhận',
  'Hệ thống ghi nhận phương thức trả hàng thành công','Phê duyệt cách đây 23h55','Kỹ thuật: Phân tích giá trị biên (cận dưới mốc 24h)'),
 ('T',None,'Check hiển thị nhắc chọn phương thức trả hàng tại màn Danh sách đơn hàng',
  'ĐK: Yêu cầu đã được phê duyệt, chưa chọn phương thức trả hàng\n1. Vào tab Trả hàng tại màn Danh sách đơn hàng',
  'Card đơn hàng hiển thị: Bạn cần chọn phương thức trả hàng trễ nhất vào [DD/MM], onclick điều hướng màn Chi tiết hoàn tiền','','Mục 1.3.1 STT 17'),
 ('T',None,'Check hiển thị thông tin sau khi ĐVVC đã lấy hàng hoàn',
  'ĐK: ĐVVC đã lấy hàng hoàn thành công\n1. Check vùng Phương thức trả hàng',
  'Hiển thị: Đã lấy hàng hoàn trả lúc [HH:MM DD/MM/YYYY] kèm tên người gửi, SĐT và địa chỉ của người dùng','','Mục 1.3.4 STT 5'),
 ('T',None,'Check xác nhận phương thức trả hàng khi mất kết nối mạng',
  '1. Ngắt kết nối mạng\n2. Click button Xác nhận phương thức trả hàng',
  'Hệ thống hiển thị thông báo lỗi kết nối, không ghi nhận phương thức trả hàng, cho phép thao tác lại','',''),

 ('T','Button Thay đổi phương thức','Check ẩn button Thay đổi khi chưa chọn phương thức trả hàng',
  'ĐK: Yêu cầu đã phê duyệt, chưa xác nhận phương thức trả hàng\n1. Check button Thay đổi',
  'Không hiển thị button Thay đổi','','Kỹ thuật: Bảng quyết định'),
 ('T',None,'Check hiển thị button Thay đổi sau khi chọn phương thức trả hàng',
  'ĐK: Đã xác nhận phương thức trả hàng\n1. Check button Thay đổi',
  'Hiển thị button Thay đổi tại góc phải vùng Phương thức trả hàng','',''),
 ('T',None,'Check khi click button Thay đổi',
  '1. Click button Thay đổi',
  'Hiển thị bottom sheet Thay đổi phương thức trả hàng gồm:\n+ Title: Thay đổi phương thức trả hàng\n+ Lựa chọn Đơn vị vận chuyển đến lấy hàng (đang chọn)\n+ Lựa chọn Trả hàng tại bưu cục\n+ Button Xác nhận','',''),
 ('T',None,'Check khi thay đổi phương thức và click Xác nhận',
  '1. Click button Thay đổi\n2. Chọn phương thức khác\n3. Click button Xác nhận',
  'Hệ thống ghi nhận phương thức trả hàng mới và đóng bottom sheet','','Phụ thuộc phase 1 có mở Trả hàng tại bưu cục hay không'),
 ('T',None,'Check khi đóng bottom sheet Thay đổi phương thức mà không xác nhận',
  '1. Click button Thay đổi\n2. Vuốt xuống/click vùng ngoài để đóng bottom sheet',
  'Đóng bottom sheet, giữ nguyên phương thức trả hàng đã chọn trước đó','',''),
 ('T',None,'Check ẩn button Thay đổi sau khi ĐVVC đã lấy hàng',
  'ĐK: ĐVVC đã lấy hàng hoàn thành công\n1. Check button Thay đổi',
  'Không hiển thị button Thay đổi, không cho phép đổi phương thức trả hàng','','Kỹ thuật: Bảng quyết định'),

 ('T','Hướng dẫn trả hàng','Check hiển thị vùng Hướng dẫn trả hàng sau khi chọn phương thức',
  'ĐK: Đã xác nhận phương thức trả hàng\n1. Check vùng Hướng dẫn trả hàng',
  'Hiển thị 3 bước:\n1. Đóng gói sản phẩm - Đóng gói tất cả sản phẩm, phụ kiện, quà tặng đi kèm như ban đầu và chèn lót sản phẩm cẩn thận\n2. Ghi mã vận đơn dưới đây lên gói hàng + mã vận đơn + button Tải về file PDF phiếu vận đơn\n3. Chờ đơn vị vận chuyển lấy hàng','',''),
 ('T',None,'Check ẩn vùng Hướng dẫn trả hàng khi chưa chọn phương thức',
  'ĐK: Yêu cầu đã phê duyệt, chưa xác nhận phương thức trả hàng\n1. Check vùng Hướng dẫn trả hàng',
  'Không hiển thị vùng Hướng dẫn trả hàng','','Kỹ thuật: Bảng quyết định'),
 ('T',None,'Check hiển thị mã vận đơn',
  '1. Check mã vận đơn tại bước 2 của Hướng dẫn trả hàng',
  'Hiển thị đúng mã vận đơn của đơn trả hàng do ĐVVC cấp (VD: VPM56864346)','Mã vận đơn: VPM56864346',''),
 ('T',None,'Check khi click icon copy mã vận đơn',
  '1. Click icon copy cạnh mã vận đơn',
  'Hiển thị thông báo: Sao chép thành công','',''),
 ('T',None,'Check paste mã vận đơn sau khi sao chép',
  '1. Click icon copy mã vận đơn\n2. Paste dữ liệu ra vùng nhập khác',
  'Paste ra đúng mã vận đơn đã sao chép','',''),
 ('T',None,'Check khi click button Tải về file PDF phiếu vận đơn',
  '1. Click button Tải về file PDF phiếu vận đơn',
  'Hệ thống hiển thị file PDF phiếu vận đơn với thông tin đơn trả hàng đúng với mã vận đơn','','File PDF do E2 cung cấp'),
 ('T',None,'Check tải file PDF phiếu vận đơn khi mất kết nối mạng',
  '1. Ngắt kết nối mạng\n2. Click button Tải về file PDF phiếu vận đơn',
  'Hệ thống hiển thị thông báo lỗi kết nối, không crash app','',''),

 ('T','Bạn cần hỗ trợ','Check hiển thị vùng Bạn cần hỗ trợ',
  '1. Check vùng Bạn cần hỗ trợ',
  'Hiển thị: Bạn cần hỗ trợ - Liên hệ với Vipo F2C kèm icon tai nghe và icon mũi tên','',''),
 ('T',None,'Check khi click vào vùng Bạn cần hỗ trợ',
  '1. Click vào vùng Bạn cần hỗ trợ',
  'Hệ thống chuyển sang Zalo OA hỗ trợ khách hàng','',''),
 ('T',None,'Check khi thiết bị chưa cài ứng dụng Zalo',
  'ĐK: Thiết bị chưa cài Zalo\n1. Click vào vùng Bạn cần hỗ trợ',
  'Hệ thống mở Zalo OA trên trình duyệt hoặc hiển thị hướng dẫn, không crash app','',''),

 ('T','Thông tin sản phẩm','Check hiển thị thông tin sản phẩm tại màn Chi tiết hoàn tiền',
  '1. Check vùng thông tin sản phẩm',
  'Hiển thị: Ảnh sản phẩm, Tên sản phẩm, Số lượng sản phẩm, Tổng tiền đơn hàng và text Xem chi tiết','',''),
 ('T',None,'Check hiển thị ảnh sản phẩm theo SKU',
  'ĐK: Sản phẩm chỉ có 1 SKU\n1. Check ảnh sản phẩm',
  'Hiển thị ảnh của SKU đó; nếu SKU không có ảnh thì lấy ảnh sản phẩm','',''),
 ('T',None,'Check hiển thị tên sản phẩm dài hơn 1 dòng',
  'ĐK: Tên sản phẩm dài hơn 1 dòng\n1. Check hiển thị tên sản phẩm',
  'Hiển thị tối đa 1 dòng, tự động cắt ngắn và hiển thị dấu … ở cuối dòng thứ 1','Tên sản phẩm > 60 ký tự','Kỹ thuật: Phân tích giá trị biên (độ dài hiển thị)'),
 ('T',None,'Check khi click Xem chi tiết tại vùng thông tin sản phẩm',
  '1. Click text Xem chi tiết',
  'Hiển thị thông tin yêu cầu Trả hàng/Hoàn tiền gồm:\n+ Mã yêu cầu kèm icon copy\n+ Hoàn tiền vào\n+ Thời gian yêu cầu\n+ Lý do trả hàng/hoàn tiền','',''),
 ('T',None,'Check khi click icon copy mã yêu cầu',
  '1. Click Xem chi tiết\n2. Click icon copy cạnh Mã yêu cầu',
  'Hiển thị thông báo: Sao chép thành công','',''),
 ('T',None,'Check paste mã yêu cầu sau khi sao chép',
  '1. Click icon copy mã yêu cầu\n2. Paste dữ liệu ra vùng nhập khác',
  'Paste ra đúng mã yêu cầu đã sao chép','',''),
 ('T',None,'Check hiển thị thời gian yêu cầu',
  '1. Click Xem chi tiết\n2. Check Thời gian yêu cầu',
  'Hiển thị đúng thời gian người dùng gửi yêu cầu trả hàng/hoàn tiền theo format quy định','',''),
 ('T',None,'Check hiển thị tài khoản nhận tiền hoàn tại phần Xem chi tiết',
  '1. Click Xem chi tiết\n2. Check dòng Hoàn tiền vào',
  'Hiển thị đúng tài khoản ngân hàng người dùng đã chọn khi gửi yêu cầu','',''),
 ('T',None,'Check khi click vào Lý do trả hàng/hoàn tiền',
  '1. Click Xem chi tiết\n2. Click vào Lý do trả hàng/hoàn tiền',
  'Hiển thị bottom sheet Lý do trả hàng/hoàn tiền gồm:\n+ Title: Lý do trả hàng/hoàn tiền\n+ Lý do: [lý do đã chọn]\n+ Mô tả (nếu có)\n+ Hình ảnh/video đã đăng tải\n+ Button Đã hiểu','Lý do: Thiếu hàng',''),
 ('T',None,'Check hiển thị hình ảnh/video tại bottom sheet Lý do trả hàng/hoàn tiền',
  'ĐK: Yêu cầu gửi kèm 2 ảnh và 1 video\n1. Mở bottom sheet Lý do trả hàng/hoàn tiền',
  'Hiển thị đủ 2 ảnh và 1 video (video có icon play) đúng với nội dung đã gửi','2 ảnh + 1 video',''),
 ('T',None,'Check khi click vào ảnh tại bottom sheet Lý do trả hàng/hoàn tiền',
  '1. Mở bottom sheet Lý do trả hàng/hoàn tiền\n2. Click vào 1 ảnh',
  'Hiển thị ảnh ở chế độ toàn màn hình','',''),
 ('T',None,'Check khi click vào video tại bottom sheet Lý do trả hàng/hoàn tiền',
  '1. Mở bottom sheet Lý do trả hàng/hoàn tiền\n2. Click vào video',
  'Hiển thị màn hình phát video','',''),
 ('T',None,'Check hiển thị khi yêu cầu không có mô tả',
  'ĐK: Yêu cầu gửi không nhập trường Mô tả\n1. Mở bottom sheet Lý do trả hàng/hoàn tiền',
  'Hiển thị lý do và hình ảnh/video, phần Mô tả để trống hoặc ẩn theo design','Yêu cầu không có mô tả','Kỹ thuật: Phân vùng tương đương (có/không mô tả)'),
 ('T',None,'Check khi click button Đã hiểu tại bottom sheet Lý do trả hàng/hoàn tiền',
  '1. Mở bottom sheet Lý do trả hàng/hoàn tiền\n2. Click button Đã hiểu',
  'Đóng bottom sheet, quay lại màn Chi tiết hoàn tiền','',''),
 ('T',None,'Check thu gọn thông tin chi tiết yêu cầu',
  'ĐK: Đang mở phần Xem chi tiết\n1. Click lại vào Xem chi tiết/icon mũi tên',
  'Thu gọn phần thông tin chi tiết yêu cầu trả hàng/hoàn tiền','',''),

 ('T','Quy tắc thời gian hoàn tiền','Check thời gian hoàn tiền dự kiến sau khi ĐVVC lấy hàng thành công',
  'ĐK: ĐVVC lấy hàng hoàn thành công\n1. Vào tab Trả hàng tại màn Danh sách đơn hàng\n2. Check dòng trạng thái Chờ hoàn tiền',
  'Hiển thị: Chờ hoàn tiền [DD/MM/YYYY] - thời gian hoàn tiền dự kiến tối đa 10 ngày kể từ khi ĐVVC lấy hàng thành công','Ngày lấy hàng: 01/09/2026','Mục 1.3.1 STT 18 - Kỹ thuật: Phân tích giá trị biên (mốc 10 ngày)'),
 ('T',None,'Check hiển thị khi hoàn tiền thành công',
  'ĐK: Hệ thống hoàn tiền thành công\n1. Check màn Chi tiết hoàn tiền và card đơn hàng',
  'Hiển thị Hoàn tiền thành công kèm ngày giờ [DD/MM/YYYY - HH:MM] và số tiền hoàn','','Mục 1.3.1 STT 19'),
 ('T',None,'Check hiển thị khi hoàn tiền thất bại',
  'ĐK: Hệ thống hoàn tiền thất bại\n1. Check màn Chi tiết hoàn tiền và card đơn hàng',
  'Hiển thị Hoàn tiền thất bại kèm ngày giờ [DD/MM/YYYY - HH:MM] và lý do thất bại','','Mục 1.3.1 STT 20'),
 ('T',None,'Check trạng thái đơn hàng khi yêu cầu bị từ chối',
  'ĐK: Nhà bán/Admin từ chối yêu cầu\n1. Vào màn Danh sách đơn hàng',
  'Đơn hàng chuyển sang trạng thái Đã hoàn thành, hiển thị mô tả Yêu cầu trả hàng bị từ chối kèm lý do','','Mục 1.3.2.5 - Kỹ thuật: Sơ đồ chuyển trạng thái'),
 ('T',None,'Check tab hiển thị đơn hàng theo trạng thái hoàn tiền',
  '1. Kiểm tra vị trí hiển thị đơn hàng ở các trạng thái: Chờ xử lý, Chờ hoàn tiền, Hoàn tiền thành công, Hoàn tiền thất bại',
  'Đơn hàng hiển thị đúng tab theo quy định tại mục 1.3.1 STT 1 và STT 5','','Mục 1.3.1 STT 5 ghi tab Đã huỷ chứa Chờ hoàn tiền/Đã hoàn tiền/Hoàn tiền thất bại trong khi STT 1 ghi tab Trả hàng - cần BA confirm'),

 ('T','Kiểm thử kỹ thuật','Check dữ liệu hiển thị lấy từ API',
  '1. Mở màn Chi tiết hoàn tiền\n2. Đối chiếu dữ liệu hiển thị với response API',
  'Số tiền hoàn, trạng thái, tiến trình, tài khoản nhận tiền hoàn, mã yêu cầu, mã vận đơn hiển thị đúng dữ liệu từ API','','Bổ sung tên API và tên trường sau khi dev cung cấp'),
 ('T',None,'Check hiển thị khi API trả về lỗi khi mở màn Chi tiết hoàn tiền',
  '1. Giả lập API chi tiết hoàn tiền trả về lỗi 500\n2. Mở màn Chi tiết hoàn tiền',
  'Hệ thống hiển thị thông báo lỗi thân thiện và cho phép thử lại, không crash app','',''),
 ('T',None,'Check mở màn Chi tiết hoàn tiền khi mất kết nối mạng',
  '1. Ngắt kết nối mạng\n2. Mở màn Chi tiết hoàn tiền',
  'Hệ thống hiển thị thông báo không có kết nối mạng và nút thử lại','',''),
 ('T',None,'Check thời gian tải màn hình Chi tiết hoàn tiền',
  '1. Mở màn Chi tiết hoàn tiền\n2. Đo thời gian hiển thị đầy đủ dữ liệu',
  'Màn hình hiển thị đầy đủ dữ liệu trong vòng 3 giây, có loading trong lúc tải','',''),
 ('T',None,'Check xoay ngang màn hình',
  '1. Mở màn Chi tiết hoàn tiền\n2. Xoay ngang thiết bị',
  'Giao diện hiển thị đúng, không vỡ layout, dữ liệu không bị mất','',''),
 ('T',None,'Check chuyển app ra nền và quay lại',
  '1. Mở màn Chi tiết hoàn tiền\n2. Chuyển app ra nền 30 giây\n3. Quay lại app',
  'Màn hình giữ nguyên trạng thái và cập nhật dữ liệu mới nhất, không bị văng về trang chủ','',''),
 ('T',None,'Check hiển thị màn hình trên thiết bị màn hình nhỏ',
  '1. Mở màn Chi tiết hoàn tiền trên thiết bị màn hình nhỏ (VD: iPhone SE)',
  'Hiển thị đầy đủ các thành phần, không vỡ giao diện, cuộn được toàn bộ nội dung','',''),
 ('T',None,'Check hiển thị màn hình trên máy tính bảng',
  '1. Mở màn Chi tiết hoàn tiền trên tablet/iPad',
  'Hiển thị đầy đủ các thành phần theo design, không vỡ giao diện','',''),
]


TECHNIQUES = [{'title': '1. BẢNG QUYẾT ĐỊNH - Hiển thị thành phần trên màn Chi tiết hoàn tiền theo trạng thái yêu cầu', 'header': ['Thành phần / Trạng thái yêu cầu', 'Chờ phê duyệt', 'Đã phê duyệt\n(chưa chọn PT trả hàng)', 'Đã chọn PT trả hàng\n(chưa lấy hàng)', 'Đã lấy hàng\n(chờ hoàn tiền)', 'Hoàn tiền\nthành công/thất bại', 'Từ chối hoàn tiền'], 'rows': [['Banner mô tả trạng thái', 'Hiện', 'Hiện', 'Hiện', 'Hiện', 'Hiện', 'Hiện (kèm lý do từ chối)'], ['Số tiền hoàn + tag trạng thái', 'Hiện', 'Hiện', 'Hiện', 'Hiện', 'Hiện', 'Hiện'], ['Tiến trình hoàn tiền', 'Hiện', 'Mốc 1 hoàn thành', 'Mốc 1 hoàn thành', 'Mốc 1-2 hoàn thành', 'Đủ 3 mốc', 'Mốc Từ chối hoàn tiền'], ['Button Huỷ yêu cầu', 'Hiện', 'Hiện', 'Hiện', 'Ẩn', 'Ẩn', 'Ẩn'], ['Chọn phương thức trả hàng', 'Ẩn', 'Hiện', 'Ẩn (đã chuyển sang vùng Phương thức trả hàng)', 'Ẩn', 'Ẩn', 'Ẩn'], ['Button Thay đổi phương thức', 'Ẩn', 'Ẩn', 'Hiện', 'Ẩn', 'Ẩn', 'Ẩn'], ['Hướng dẫn trả hàng', 'Ẩn', 'Ẩn', 'Hiện', 'Hiện', 'Ẩn/Hiện theo design', 'Ẩn'], ['Bạn cần hỗ trợ', 'Hiện', 'Hiện', 'Hiện', 'Hiện', 'Hiện', 'Hiện'], ['Thông tin sản phẩm + Xem chi tiết', 'Hiện', 'Hiện', 'Hiện', 'Hiện', 'Hiện', 'Hiện']]},
 {'title': '2. SƠ ĐỒ CHUYỂN TRẠNG THÁI - Yêu cầu Trả hàng/Hoàn tiền', 'header': ['Trạng thái hiện tại', 'Sự kiện', 'Trạng thái kế tiếp', 'Trạng thái đơn hàng', 'Ghi chú quy tắc'], 'rows': [['(Chưa có yêu cầu)', 'Buyer gửi yêu cầu (trong 5 ngày kể từ giao thành công)', 'Chờ phê duyệt', 'Trả hàng', 'Tối đa 2 lượt/đơn'], ['Chờ phê duyệt', 'Buyer huỷ yêu cầu', 'Đã huỷ', 'Đã giao', 'Trừ 1 lượt'], ['Chờ phê duyệt', 'Nhà bán/Admin phê duyệt (dự kiến 24h)', 'Đã phê duyệt', 'Trả hàng', 'Buyer phải chọn PT trả hàng trong 24h'], ['Chờ phê duyệt', 'Nhà bán/Admin từ chối', 'Từ chối hoàn tiền', 'Đã hoàn thành', 'Hiển thị lý do từ chối, trừ 1 lượt'], ['Đã phê duyệt', 'Buyer chọn phương thức trả hàng + Xác nhận', 'Chờ ĐVVC lấy hàng', 'Trả hàng', 'ĐVVC lấy trong 1-3 ngày'], ['Đã phê duyệt', 'Quá 24h không chọn phương thức trả hàng', 'Đã huỷ (tác nhân: Sàn)', 'Đã giao', 'Trừ 1 lượt'], ['Đã phê duyệt', 'Buyer huỷ yêu cầu', 'Đã huỷ', 'Đã giao', 'Trừ 1 lượt'], ['Chờ ĐVVC lấy hàng', 'ĐVVC lấy hàng thành công', 'Chờ hoàn tiền', 'Trả hàng', 'Hoàn tiền tối đa 10 ngày'], ['Chờ hoàn tiền', 'Hệ thống hoàn tiền thành công', 'Hoàn tiền thành công', 'Trả hàng', 'Admin import trạng thái trên CMS'], ['Chờ hoàn tiền', 'Hệ thống hoàn tiền thất bại', 'Hoàn tiền thất bại', 'Trả hàng', 'Hiển thị lý do thất bại'], ['Đã huỷ / Từ chối (lượt 1)', 'Buyer gửi yêu cầu lần 2 (còn trong 5 ngày)', 'Chờ phê duyệt', 'Trả hàng', 'Hết lượt sau lần 2'], ['Đã huỷ / Từ chối (lượt 2)', 'Buyer bấm gửi yêu cầu', '(Bị chặn)', 'Đã giao/Đã hoàn thành', 'Hiển thị: Bạn đã hết lượt gửi yêu cầu']]},
 {'title': '3. PHÂN TÍCH GIÁ TRỊ BIÊN - Các mốc thời gian & số lượng', 'header': ['Ràng buộc', 'Dưới biên (hợp lệ)', 'Tại biên', 'Trên biên (không hợp lệ)', 'TC liên quan'], 'rows': [['Thời hạn gửi yêu cầu: 5 ngày kể từ ngày ĐVVC giao thành công', 'Ngày thứ 4', 'Đúng ngày thứ 5', 'Ngày thứ 6 - đơn chuyển Đã hoàn thành', 'Nhóm Quy tắc thời gian, Huỷ yêu cầu'], ['Thời hạn chọn phương thức trả hàng: 24h kể từ khi phê duyệt', '23h55', '24h00', 'Quá 24h - yêu cầu bị Sàn huỷ', 'Nhóm Chọn phương thức trả hàng'], ['Thời gian ĐVVC đến lấy hàng: 1-3 ngày kể từ ngày phê duyệt', 'Ngày 1', 'Ngày 3', 'Sau ngày 3 - cần cảnh báo/hỗ trợ', 'Nhóm Chọn phương thức trả hàng'], ['Thời gian hoàn tiền: tối đa 10 ngày kể từ khi lấy hàng thành công', 'Ngày 9', 'Ngày 10', 'Sau ngày 10 - liên hệ CSKH', 'Nhóm Quy tắc thời gian hoàn tiền'], ['Số lượt gửi yêu cầu: tối đa 2 lượt/đơn hàng', 'Lượt 1', 'Lượt 2', 'Lượt 3 - bị chặn', 'Nhóm Button Huỷ yêu cầu']]}]
