# -*- coding: utf-8 -*-
# ('S', title) section ; ('P', text) pre-condition ; ('T', func, purpose, steps, expected, data, note)

ROWS = [
 ('S','Điểm vào Yêu cầu trả hàng/hoàn tiền (Màn Danh sách/Chi tiết đơn hàng)'),
 ('P','Pre-condition: \nBước 1: Người dùng đăng nhập thành công vào hệ thống bằng tài khoản đã eKYC và đã khai báo tài khoản ngân hàng\nBước 2: Người dùng click vào icon Đơn hàng trên navigation\nBước 3: Có đơn hàng đã thanh toán, ĐVVC giao hàng thành công (trạng thái Đã giao), chưa quá 5 ngày kể từ ngày giao thành công'),

 ('T','Vùng Gửi yêu cầu trả hàng/hoàn tiền','Check hiển thị vùng Gửi yêu cầu trả hàng/hoàn tiền với đơn chưa gửi yêu cầu',
  'ĐK: Đơn hàng Đã giao, chưa gửi yêu cầu trả hàng/hoàn tiền\n1. Click vào 1 item đơn hàng tại tab Đã giao\n2. Check vùng Mô tả trạng thái yêu cầu trả hàng/hoàn tiền',
  'Hiển thị vùng thông tin gồm:\n+ Title: Gửi yêu cầu trả hàng/hoàn tiền\n+ Text: Gửi yêu cầu trễ nhất vào [DD/MM/YYYY]\n+ Icon mũi tên điều hướng','Đơn hàng Đã giao trong 5 ngày',''),
 ('T',None,'Check ngày trễ nhất được gửi yêu cầu',
  'ĐK: ĐVVC giao hàng thành công ngày 20/09/2026\n1. Click vào 1 item đơn hàng tại tab Đã giao\n2. Check ngày hiển thị tại text Gửi yêu cầu trễ nhất vào',
  'Hiển thị ngày = ngày ĐVVC giao hàng thành công + 5 ngày (25/09/2026), format DD/MM/YYYY','Ngày giao thành công: 20/09/2026',''),
 ('T',None,'Check khi click vào vùng Gửi yêu cầu trả hàng/hoàn tiền',
  '1. Click vào 1 item đơn hàng tại tab Đã giao\n2. Click vào vùng Gửi yêu cầu trả hàng/hoàn tiền',
  'Hệ thống điều hướng sang màn hình Yêu cầu trả hàng/hoàn tiền','',''),
 ('T',None,'Check hiển thị vùng yêu cầu trả hàng/hoàn tiền tại màn Danh sách đơn hàng',
  '1. Click tab Đã giao tại màn Danh sách đơn hàng\n2. Check card đơn hàng chưa gửi yêu cầu trả hàng/hoàn tiền',
  'Hiển thị text Gửi yêu cầu trả hàng/hoàn tiền kèm ngày gửi trễ nhất, onclick điều hướng sang màn Yêu cầu trả hàng/hoàn tiền','',''),
 ('T',None,'Check hiển thị khi đơn hàng đang ở trạng thái Đang giao',
  'ĐK: Đơn hàng Đang giao, người dùng chưa click Đã nhận hàng\n1. Click vào 1 item đơn hàng tại tab Đang giao\n2. Check vùng yêu cầu trả hàng/hoàn tiền',
  'Không hiển thị vùng Gửi yêu cầu trả hàng/hoàn tiền. Chỉ cho phép gửi yêu cầu khi đơn ở trạng thái Đã giao','',''),
 ('T',None,'Check hiển thị khi đơn hàng đã quá 5 ngày kể từ ngày giao thành công',
  'ĐK: Đơn hàng giao thành công quá 5 ngày, không phát sinh yêu cầu trả hàng/hoàn tiền\n1. Vào màn Danh sách đơn hàng\n2. Check trạng thái và CTA của đơn hàng',
  'Đơn hàng chuyển sang trạng thái Đã hoàn thành, hiển thị tại tab Đã hoàn thành, không còn vùng Gửi yêu cầu trả hàng/hoàn tiền','Đơn giao thành công 6 ngày trước',''),
 ('T',None,'Check hiển thị khi người dùng đã huỷ yêu cầu 1 lần',
  'ĐK: Đơn hàng đã gửi yêu cầu trả hàng/hoàn tiền 1 lần và người dùng đã huỷ yêu cầu\n1. Click vào 1 item đơn hàng\n2. Check vùng mô tả trạng thái yêu cầu trả hàng/hoàn tiền',
  'Hiển thị:\n+ Title: Yêu cầu trả hàng/hoàn tiền đã bị huỷ\n+ Tag: Yêu cầu bị huỷ\n+ Text: Bạn còn 1 lượt gửi yêu cầu, trễ nhất vào [DD/MM]\nOnclick điều hướng sang màn Yêu cầu trả hàng/hoàn tiền','',''),
 ('T',None,'Check hiển thị khi yêu cầu bị Sàn/Nhà bán từ chối 1 lần',
  'ĐK: Đơn hàng có yêu cầu trả hàng/hoàn tiền bị từ chối 1 lần\n1. Click vào 1 item đơn hàng\n2. Check vùng mô tả trạng thái yêu cầu trả hàng/hoàn tiền',
  'Hiển thị:\n+ Title: Yêu cầu trả hàng bị từ chối\n+ Tag: Từ chối hoàn tiền\n+ Lý do: [lý do từ chối của Sàn/Nhà bán]\n+ Text: Sàn/Nhà bán đã từ chối yêu cầu. Còn 1 lần trả hàng/hoàn tiền','',''),
 ('T',None,'Check hiển thị khi người dùng đã hết lượt gửi yêu cầu',
  'ĐK: Đơn hàng đã gửi yêu cầu trả hàng/hoàn tiền 2 lần và đều bị huỷ/từ chối\n1. Click vào 1 item đơn hàng\n2. Check vùng mô tả trạng thái yêu cầu trả hàng/hoàn tiền',
  'Hiển thị:\n+ Title: Yêu cầu trả hàng/hoàn tiền đã bị huỷ\n+ Tag: Yêu cầu bị huỷ\n+ Text: Bạn đã hết lượt gửi yêu cầu trả hàng/hoàn tiền\nHệ thống không cho phép gửi yêu cầu mới','',''),
 ('T',None,'Check khi click vào vùng yêu cầu khi đã hết lượt gửi yêu cầu',
  'ĐK: Đơn hàng đã hết lượt gửi yêu cầu trả hàng/hoàn tiền\n1. Click vào vùng mô tả trạng thái yêu cầu trả hàng/hoàn tiền',
  'Hệ thống không cho phép tạo yêu cầu mới (chỉ xem lại thông tin yêu cầu cũ)','','BA confirm hành vi khi click: chặn điều hướng hay mở màn chỉ đọc'),
 ('T',None,'Check khi người dùng chưa định danh CCCD click gửi yêu cầu trả hàng/hoàn tiền',
  'ĐK: Tài khoản chưa eKYC\n1. Click vào vùng Gửi yêu cầu trả hàng/hoàn tiền',
  'Hệ thống hiển thị màn hình TKNH với button Định danh ngay, user click để thực hiện luồng định danh tài khoản','Tài khoản chưa eKYC',''),
 ('T',None,'Check khi người dùng đã định danh nhưng chưa khai báo tài khoản ngân hàng',
  'ĐK: Tài khoản đã eKYC, chưa khai báo TKNH\n1. Click vào vùng Gửi yêu cầu trả hàng/hoàn tiền',
  'Hệ thống hiển thị màn hình TKNH với button Liên kết ngay, user click để thực hiện luồng khai báo tài khoản ngân hàng','Tài khoản đã eKYC, chưa có TKNH',''),

 ('S','Màn hình Yêu cầu trả hàng/hoàn tiền'),
 ('P','Pre-condition: \nBước 1: Người dùng đăng nhập thành công vào hệ thống bằng tài khoản đã eKYC và đã khai báo tài khoản ngân hàng\nBước 2: Người dùng click vào icon Đơn hàng trên navigation\nBước 3: Click vào 1 đơn hàng có trạng thái Đã giao, còn lượt gửi yêu cầu\nBước 4: Click Gửi yêu cầu trả hàng/hoàn tiền'),

 ('T','Giao diện tổng quan','Kiểm tra giao diện màn hình Yêu cầu trả hàng/hoàn tiền',
  '1. Kiểm tra title của màn hình\n2. Kiểm tra hiển thị đầy đủ thông tin của các label trên màn hình',
  '1. Hiển thị title màn hình: Yêu cầu trả hàng/hoàn, icon Back, icon ... và icon X\n2. Hiển thị đầy đủ các label theo đúng design:\n+ Thông tin sản phẩm\n+ Hoàn tiền vào\n+ Tổng tiền hoàn\n+ Lý do\n+ Đăng tải hình ảnh hoặc video\n+ Mô tả\n+ Email cập nhật tình hình\n+ Button Gửi yêu cầu','',''),
 ('T',None,'Kiểm tra hiển thị giao diện màn Yêu cầu trả hàng/hoàn tiền',
  '1. Kiểm tra về bố cục\n2. Kiểm tra font chữ, cỡ chữ, màu chữ\n3. Kiểm tra chính tả.',
  '1. Bố cục\n- Các label, textbox, button được bố trí thẳng hàng, có độ dài, độ rộng, và khoảng cách bằng nhau, không xô lệch.\n- Form được bố trí hợp lý và dễ sử dụng.\n2. Font chữ, màu chữ\n- Các label, text sử dụng cùng 1 loại font chữ, cỡ chữ\n- Màu chữ: giống như giao diện Figma\n3. Chính tả: Không có lỗi về chính tả, cấu trúc câu, ngữ pháp trên màn hình.','',''),
 ('T',None,'Kiểm tra dữ liệu khi màn hình để chế độ sáng',
  '1. Người dùng cài đặt chế độ sáng trên máy\n2. Kiểm tra giao diện của màn hình',
  'Dữ liệu hiển thị bình thường, rõ nét và không vỡ giao diện','',''),
 ('T',None,'Kiểm tra dữ liệu khi màn hình để chế độ tối',
  '1. Người dùng cài đặt chế độ tối trên máy\n2. Kiểm tra giao diện của màn hình',
  'Dữ liệu hiển thị bình thường, rõ nét và không vỡ giao diện','',''),
 ('T',None,'Kiểm tra hiển thị màn hình khi thay đổi cỡ chữ hệ thống lớn nhất',
  '1. Cài đặt cỡ chữ lớn nhất trên thiết bị\n2. Mở màn Yêu cầu trả hàng/hoàn tiền',
  'Các label, button hiển thị đầy đủ nội dung, không bị cắt chữ, không vỡ giao diện','',''),
 ('T',None,'Kiểm tra cuộn màn hình',
  '1. Cuộn lên/xuống toàn bộ nội dung màn hình',
  'Nội dung cuộn mượt, button Gửi yêu cầu luôn được ghim ở cuối màn hình','',''),

 ('T','Button Back/Đóng','Check khi click icon Back lúc chưa nhập thông tin',
  'ĐK: Chưa nhập/chọn bất kỳ thông tin nào\n1. Click icon Back',
  'Hệ thống quay về màn hình Chi tiết đơn hàng, không lưu yêu cầu','',''),
 ('T',None,'Check khi click icon Back lúc đang nhập thông tin yêu cầu',
  'ĐK: Đã chọn lý do/nhập mô tả/thêm ảnh\n1. Click icon Back',
  'Hệ thống hiển thị popup xác nhận rời trang theo design','','BA confirm nội dung popup rời trang khi đang nhập dở'),
 ('T',None,'Check khi click icon X',
  '1. Click icon X trên header',
  'Hệ thống đóng màn Yêu cầu trả hàng/hoàn tiền và quay về màn hình trước đó','',''),

 ('T','Thông tin sản phẩm','Check hiển thị thông tin sản phẩm của đơn hàng',
  '1. Check vùng thông tin sản phẩm trên màn Yêu cầu trả hàng/hoàn tiền',
  'Hiển thị đầy đủ:\n+ Ảnh sản phẩm\n+ Tên sản phẩm\n+ Số lượng sản phẩm\n+ Tổng tiền: [số tiền đơn hàng]','',''),
 ('T',None,'Check hiển thị ảnh sản phẩm khi sản phẩm có 1 SKU',
  'ĐK: Sản phẩm chỉ có 1 SKU\n1. Check ảnh sản phẩm hiển thị',
  'Hiển thị ảnh của SKU đó','',''),
 ('T',None,'Check hiển thị ảnh sản phẩm khi SKU không có ảnh',
  'ĐK: SKU không có ảnh\n1. Check ảnh sản phẩm hiển thị',
  'Hiển thị ảnh của sản phẩm','',''),
 ('T',None,'Check hiển thị tên sản phẩm khi tên chưa hết 1 dòng',
  'ĐK: Tên sản phẩm ngắn hơn 1 dòng\n1. Check hiển thị tên sản phẩm',
  'Hiển thị đầy đủ tên sản phẩm','',''),
 ('T',None,'Check hiển thị tên sản phẩm khi tên dài hơn 1 dòng',
  'ĐK: Tên sản phẩm dài hơn 1 dòng\n1. Check hiển thị tên sản phẩm',
  'Hiển thị tối đa 1 dòng, tự động cắt ngắn và hiển thị dấu … ở cuối dòng thứ 1','Tên sản phẩm > 60 ký tự',''),
 ('T',None,'Check hiển thị số lượng sản phẩm khi đơn hàng có nhiều sản phẩm',
  'ĐK: Đơn hàng có 3 sản phẩm\n1. Check hiển thị số lượng sản phẩm',
  'Hiển thị đúng tổng số lượng sản phẩm của đơn hàng (3 sản phẩm)','Đơn hàng 3 sản phẩm',''),
 ('T',None,'Check hiển thị tổng tiền đơn hàng',
  '1. Check hiển thị Tổng tiền',
  'Hiển thị tổng tiền người mua đã thanh toán cho đơn hàng, định dạng có dấu chấm ngăn cách hàng nghìn và hậu tố đ (VD: 125.000 đ)','Đơn hàng 125.000 đ',''),

 ('T','Hoàn tiền vào','Check hiển thị tài khoản nhận tiền hoàn mặc định khi thanh toán bằng mã QR',
  'ĐK: Đơn hàng thanh toán bằng QR chuyển khoản\n1. Check vùng Hoàn tiền vào',
  'Hiển thị tài khoản ngân hàng liên kết (tài khoản người mua chọn khi eKYC) kèm logo ngân hàng và 4 số cuối tài khoản','',''),
 ('T',None,'Check khi click vào vùng Hoàn tiền vào',
  '1. Click vào vùng Hoàn tiền vào',
  'Hiển thị bottom sheet Chọn tài khoản nhận tiền hoàn gồm:\n+ Title: Chọn tài khoản nhận tiền hoàn\n+ Danh sách tài khoản ngân hàng đã khai báo (tên ngân hàng, tên chủ tài khoản, số tài khoản, tag Mặc định)\n+ Radio button chọn tài khoản\n+ Button Xác nhận','',''),
 ('T',None,'Check hiển thị tag Mặc định tại bottom sheet Chọn tài khoản nhận tiền hoàn',
  'ĐK: Người dùng có nhiều hơn 1 tài khoản ngân hàng\n1. Click vào vùng Hoàn tiền vào\n2. Check danh sách tài khoản',
  'Tài khoản mặc định hiển thị tag Mặc định và được tick radio sẵn','Tài khoản có 2 TKNH',''),
 ('T',None,'Check khi chọn tài khoản nhận tiền hoàn khác và click Xác nhận',
  '1. Click vào vùng Hoàn tiền vào\n2. Chọn tài khoản ngân hàng thứ 2\n3. Click button Xác nhận',
  'Đóng bottom sheet, vùng Hoàn tiền vào cập nhật theo tài khoản vừa chọn','',''),
 ('T',None,'Check khi đóng bottom sheet mà không chọn tài khoản',
  '1. Click vào vùng Hoàn tiền vào\n2. Vuốt xuống/click vùng ngoài bottom sheet để đóng',
  'Đóng bottom sheet, giữ nguyên tài khoản nhận tiền hoàn đang chọn trước đó','',''),
 ('T',None,'Check hiển thị khi người dùng chỉ có 1 tài khoản ngân hàng',
  'ĐK: Người dùng chỉ khai báo 1 TKNH\n1. Click vào vùng Hoàn tiền vào',
  'Bottom sheet hiển thị 1 tài khoản duy nhất và được chọn mặc định','',''),
 ('T',None,'Check hiển thị tài khoản nhận tiền hoàn khi thanh toán qua Zalopay',
  'ĐK: Đơn hàng thanh toán qua Zalopay\n1. Check vùng Hoàn tiền vào',
  'Hiển thị TKNH thanh toán qua Zalopay','','SRS ghi: phát triển sau khi tích hợp xong với Zalopay - dự kiến N/A ở phase này'),

 ('T','Tổng tiền hoàn','Check hiển thị tổng tiền hoàn của đơn hàng',
  '1. Check vùng Tổng tiền hoàn',
  'Hiển thị tổng tiền hoàn = tổng tiền người mua đã thanh toán cho đơn hàng','Đơn 125.000 đ',''),
 ('T',None,'Check tổng tiền hoàn với đơn hàng có áp dụng voucher giảm giá',
  'ĐK: Đơn hàng có giá sản phẩm sau khuyến mãi 145.000 đ, voucher giảm 20.000 đ\n1. Check vùng Tổng tiền hoàn',
  'Tổng tiền hoàn = số tiền người mua thực thanh toán = 125.000 đ (không hoàn phần voucher)','Giá 145.000 đ - Voucher 20.000 đ',''),
 ('T',None,'Check tổng tiền hoàn với đơn hàng nhiều sản phẩm',
  'ĐK: Đơn hàng có nhiều sản phẩm\n1. Check vùng Tổng tiền hoàn',
  'Tổng tiền hoàn = tổng tiền đã thanh toán của toàn bộ đơn hàng','Đơn 3 sản phẩm',''),

 ('T','Lý do','Check hiển thị mặc định trường Lý do',
  '1. Check vùng Lý do khi chưa chọn lý do',
  'Hiển thị label Lý do kèm dấu * (bắt buộc), placeholder: Chọn lý do và icon mũi tên','',''),
 ('T',None,'Check khi click vào trường Lý do',
  '1. Click vào vùng Lý do',
  'Hiển thị bottom sheet Chọn lý do trả hàng/hoàn tiền gồm danh sách lý do theo design và button Xác nhận','','Đối chiếu danh sách lý do với Figma/BA trước khi test'),
 ('T',None,'Check chọn 1 lý do và click Xác nhận',
  '1. Click vào vùng Lý do\n2. Chọn 1 lý do (VD: Thiếu hàng)\n3. Click button Xác nhận',
  'Đóng bottom sheet, vùng Lý do hiển thị lý do vừa chọn','Lý do: Thiếu hàng',''),
 ('T',None,'Check khi chọn lý do thứ 2 trong danh sách',
  '1. Click vào vùng Lý do\n2. Chọn lý do thứ 1\n3. Chọn tiếp lý do thứ 2',
  'Hệ thống chỉ cho phép chọn 1 lý do, lý do thứ 2 được chọn và bỏ chọn lý do thứ 1','',''),
 ('T',None,'Check khi đóng bottom sheet Lý do mà không chọn',
  '1. Click vào vùng Lý do\n2. Vuốt xuống/click vùng ngoài để đóng bottom sheet',
  'Đóng bottom sheet, trường Lý do giữ nguyên trạng thái trước đó (trống hoặc lý do đã chọn)','',''),
 ('T',None,'Check khi thay đổi lý do đã chọn',
  'ĐK: Đã chọn lý do Thiếu hàng\n1. Click vào vùng Lý do\n2. Chọn lý do khác\n3. Click Xác nhận',
  'Vùng Lý do cập nhật theo lý do mới chọn','',''),
 ('T',None,'Check khi click Xác nhận mà chưa chọn lý do nào',
  '1. Click vào vùng Lý do\n2. Không chọn lý do\n3. Click button Xác nhận',
  'Hệ thống không ghi nhận lý do, trường Lý do vẫn hiển thị placeholder Chọn lý do','','BA confirm: button Xác nhận disable hay hiển thị cảnh báo'),

 ('T','Đăng tải hình ảnh hoặc video','Check hiển thị mặc định vùng Đăng tải hình ảnh hoặc video',
  '1. Check vùng Đăng tải hình ảnh hoặc video',
  'Hiển thị:\n+ Label: Đăng tải hình ảnh hoặc video kèm dấu *\n+ Text hướng dẫn: Tối đa 6 ảnh và 2 video\n+ Ô Hình ảnh và ô Video','','SRS mục 1.3.3 STT 7 ghi Bắt buộc = No nhưng design gắn dấu * - cần BA confirm'),
 ('T',None,'Check hiển thị nội dung hướng dẫn tặng voucher',
  '1. Check text hướng dẫn tại vùng đăng tải hình ảnh/video',
  'Hiển thị nội dung: Thêm 1 hình ảnh và 1 video để nhận 1 voucher giảm giá 10%','','SRS mục 1.3.3 STT 7'),
 ('T',None,'Check khi click button Thêm hình ảnh',
  '1. Click ô Hình ảnh',
  'Hệ thống mở thư viện ảnh hoặc camera trên thiết bị cho phép chọn/chụp ảnh','',''),
 ('T',None,'Check khi click button Thêm video',
  '1. Click ô Video',
  'Hệ thống mở thư viện ảnh mục video hoặc camera trên thiết bị cho phép chọn/quay video','',''),
 ('T',None,'Check thêm 1 hình ảnh thành công',
  '1. Click ô Hình ảnh\n2. Chọn 1 ảnh hợp lệ\n3. Xác nhận',
  'Ảnh được hiển thị tại vùng đăng tải kèm icon xoá','Ảnh JPG 2MB',''),
 ('T',None,'Check thêm tối đa 6 hình ảnh',
  '1. Click ô Hình ảnh\n2. Chọn 6 ảnh hợp lệ',
  'Hệ thống cho phép thêm đủ 6 ảnh, hiển thị đầy đủ 6 ảnh','6 ảnh JPG/PNG',''),
 ('T',None,'Check thêm hình ảnh thứ 7',
  'ĐK: Đã thêm đủ 6 ảnh\n1. Click ô Hình ảnh\n2. Chọn thêm 1 ảnh',
  'Hệ thống không cho phép thêm quá 6 ảnh, hiển thị cảnh báo theo design','',''),
 ('T',None,'Check thêm hình ảnh có dung lượng đúng ngưỡng 20MB',
  '1. Click ô Hình ảnh\n2. Chọn ảnh dung lượng 20MB',
  'Hệ thống cho phép thêm ảnh thành công','Ảnh 20MB',''),
 ('T',None,'Check thêm hình ảnh có dung lượng lớn hơn 20MB',
  '1. Click ô Hình ảnh\n2. Chọn ảnh dung lượng 21MB',
  'Hệ thống chặn, hiển thị thông báo lỗi vượt quá dung lượng cho phép','Ảnh 21MB',''),
 ('T',None,'Check thêm video đúng ngưỡng 200MB',
  '1. Click ô Video\n2. Chọn video dung lượng 200MB',
  'Hệ thống cho phép thêm video thành công','Video 200MB',''),
 ('T',None,'Check thêm video lớn hơn 200MB',
  '1. Click ô Video\n2. Chọn video dung lượng 201MB',
  'Hệ thống chặn, hiển thị thông báo lỗi vượt quá dung lượng cho phép','Video 201MB',''),
 ('T',None,'Check thêm tối đa 2 video',
  '1. Click ô Video\n2. Chọn 2 video hợp lệ',
  'Hệ thống cho phép thêm đủ 2 video','2 video MP4',''),
 ('T',None,'Check thêm video thứ 3',
  'ĐK: Đã thêm đủ 2 video\n1. Click ô Video\n2. Chọn thêm 1 video',
  'Hệ thống không cho phép thêm quá 2 video, hiển thị cảnh báo theo design','',''),
 ('T',None,'Check thêm file sai định dạng',
  '1. Click ô Hình ảnh\n2. Chọn file không phải ảnh (VD: .pdf, .gif)',
  'Hệ thống chặn, hiển thị thông báo định dạng không hợp lệ','File PDF','BA confirm danh sách định dạng ảnh/video được hỗ trợ'),
 ('T',None,'Check xoá hình ảnh đã thêm',
  'ĐK: Đã thêm 2 ảnh\n1. Click icon xoá trên 1 ảnh',
  'Ảnh bị xoá khỏi vùng đăng tải, số lượng ảnh còn lại cập nhật đúng','',''),
 ('T',None,'Check xoá video đã thêm',
  'ĐK: Đã thêm 1 video\n1. Click icon xoá trên video',
  'Video bị xoá khỏi vùng đăng tải','',''),
 ('T',None,'Check huỷ thao tác chọn ảnh từ thư viện',
  '1. Click ô Hình ảnh\n2. Click Huỷ/Back tại màn thư viện ảnh',
  'Quay lại màn Yêu cầu trả hàng/hoàn tiền, không thêm ảnh nào','',''),
 ('T',None,'Check khi từ chối quyền truy cập thư viện ảnh/camera',
  'ĐK: Thiết bị chưa cấp quyền truy cập thư viện ảnh\n1. Click ô Hình ảnh\n2. Chọn Không cho phép',
  'Hệ thống hiển thị hướng dẫn cấp quyền, không crash app','',''),
 ('T',None,'Check mất kết nối mạng khi đang tải ảnh/video lên',
  '1. Thêm 1 video dung lượng lớn\n2. Ngắt kết nối mạng trong lúc tải lên',
  'Hệ thống hiển thị thông báo lỗi mạng, cho phép thử lại, không mất dữ liệu đã nhập','',''),

 ('T','Mô tả','Check hiển thị placeholder trường Mô tả',
  '1. Check vùng Mô tả khi chưa nhập nội dung',
  'Hiển thị label Mô tả, bộ đếm 0/2000 và placeholder: Ghi chú thêm','',''),
 ('T',None,'Check bộ đếm ký tự khi nhập nội dung',
  '1. Nhập 100 ký tự vào trường Mô tả',
  'Bộ đếm hiển thị 100/2000','Chuỗi 100 ký tự',''),
 ('T',None,'Check nhập đúng 2.000 ký tự',
  '1. Nhập 2.000 ký tự vào trường Mô tả',
  'Cho phép nhập đủ 2.000 ký tự, bộ đếm hiển thị 2000/2000','Chuỗi 2000 ký tự',''),
 ('T',None,'Check nhập quá 2.000 ký tự',
  '1. Nhập 2.001 ký tự vào trường Mô tả',
  'Hệ thống chặn nhập, chỉ ghi nhận 2.000 ký tự','Chuỗi 2001 ký tự',''),
 ('T',None,'Check paste nội dung dài hơn 2.000 ký tự',
  '1. Copy đoạn text 2.500 ký tự\n2. Paste vào trường Mô tả',
  'Hệ thống chỉ nhận 2.000 ký tự đầu tiên, không cho vượt giới hạn','Chuỗi 2500 ký tự',''),
 ('T',None,'Check nhập ký tự đặc biệt',
  '1. Nhập chuỗi chứa ký tự đặc biệt vào trường Mô tả',
  'Cho phép nhập ký tự đặc biệt, hiển thị đúng nội dung đã nhập','!@#$%^&*()_+<>?~`',''),
 ('T',None,'Check nhập ký tự xuống dòng',
  '1. Nhập nội dung có nhiều dòng vào trường Mô tả',
  'Cho phép xuống dòng, ký tự xuống dòng được tính vào giới hạn 2.000 ký tự','Nội dung 3 dòng',''),
 ('T',None,'Check nhập tiếng Việt có dấu và emoji',
  '1. Nhập nội dung tiếng Việt có dấu kèm emoji',
  'Hiển thị đúng nội dung đã nhập, không bị lỗi font','Sản phẩm bị lỗi, giao thiếu 1 cái',''),
 ('T',None,'Check trim khoảng trắng đầu/cuối nội dung mô tả',
  '1. Nhập nội dung có khoảng trắng ở đầu và cuối\n2. Click Gửi yêu cầu\n3. Xem lại mô tả tại màn Chi tiết hoàn tiền',
  'Hệ thống tự động cắt khoảng trắng đầu/cuối, chỉ lưu nội dung chính','"   Sản phẩm bị lỗi   "',''),
 ('T',None,'Check nhập chỉ toàn khoảng trắng',
  '1. Nhập 10 ký tự khoảng trắng vào trường Mô tả\n2. Click Gửi yêu cầu',
  'Hệ thống trim thành chuỗi rỗng, yêu cầu vẫn gửi được vì Mô tả không bắt buộc','10 dấu cách',''),
 ('T',None,'Check để trống trường Mô tả',
  '1. Chọn đầy đủ các trường bắt buộc, để trống Mô tả\n2. Click Gửi yêu cầu',
  'Gửi yêu cầu thành công (Mô tả không bắt buộc)','',''),

 ('T','Email cập nhật tình hình','Check hiển thị email khi tài khoản đăng ký bằng email',
  'ĐK: Tài khoản đăng ký bằng email\n1. Check vùng Email cập nhật tình hình',
  'Hiển thị đúng email người dùng đã đăng ký tài khoản','daika36@gmail.com',''),
 ('T',None,'Check hiển thị email khi tài khoản đăng ký bằng số điện thoại',
  'ĐK: Tài khoản đăng ký bằng SĐT, chưa khai báo email\n1. Check vùng Email cập nhật tình hình',
  'Trường Email cập nhật tình hình để trống','Tài khoản đăng ký bằng SĐT',''),

 ('T','Button Gửi yêu cầu','Check trạng thái mặc định của button Gửi yêu cầu',
  '1. Mở màn Yêu cầu trả hàng/hoàn tiền, chưa nhập thông tin\n2. Check button Gửi yêu cầu',
  'Button Gửi yêu cầu hiển thị trạng thái disable','',''),
 ('T',None,'Check button Gửi yêu cầu khi chưa chọn Lý do',
  '1. Thêm ảnh/video\n2. Không chọn lý do\n3. Check button Gửi yêu cầu',
  'Button Gửi yêu cầu vẫn disable','',''),
 ('T',None,'Check button Gửi yêu cầu khi chưa đăng tải hình ảnh/video',
  '1. Chọn lý do\n2. Không thêm ảnh/video\n3. Check button Gửi yêu cầu',
  'Button Gửi yêu cầu disable (theo design hình ảnh/video là trường bắt buộc)','','Mâu thuẫn SRS (Bắt buộc = No) và design (dấu *) - cần BA confirm'),
 ('T',None,'Check button Gửi yêu cầu khi đã điền đầy đủ trường bắt buộc',
  '1. Chọn tài khoản nhận tiền hoàn\n2. Chọn lý do\n3. Thêm 1 ảnh\n4. Check button Gửi yêu cầu',
  'Button Gửi yêu cầu chuyển sang trạng thái enable','',''),
 ('T',None,'Check gửi yêu cầu trả hàng/hoàn tiền thành công',
  '1. Nhập đầy đủ thông tin các trường bắt buộc\n2. Click button Gửi yêu cầu',
  'Hiển thị toast message: "Yêu cầu Trả hàng/Hoàn tiền được gửi thành công. Thời gian xử lý từ 1- 3 ngày. Sau thời gian này, nếu yêu cầu của bạn chưa được xử lý, liên hệ CSKH để được hỗ trợ." và điều hướng sang màn hình Chi tiết hoàn tiền','',''),
 ('T',None,'Check trạng thái đơn hàng sau khi gửi yêu cầu thành công',
  '1. Gửi yêu cầu trả hàng/hoàn tiền thành công\n2. Quay về màn Danh sách đơn hàng',
  'Đơn hàng chuyển sang trạng thái Trả hàng, hiển thị tại tab Trả hàng và không còn tại tab Đã giao','',''),
 ('T',None,'Check thông tin hiển thị tại card đơn hàng sau khi gửi yêu cầu',
  '1. Gửi yêu cầu thành công\n2. Vào tab Trả hàng tại màn Danh sách đơn hàng',
  'Card đơn hàng hiển thị: Yêu cầu trả hàng/hoàn tiền đang chờ xử lý! [DD/MM/YYYY] - thời gian xử lý dự kiến 24h kể từ khi gửi yêu cầu, onclick điều hướng màn Chi tiết hoàn tiền','',''),
 ('T',None,'Check dữ liệu yêu cầu được lưu đúng sau khi gửi',
  '1. Gửi yêu cầu với lý do Thiếu hàng, mô tả và 2 ảnh, 1 video\n2. Tại màn Chi tiết hoàn tiền click Xem chi tiết\n3. Click vào Lý do trả hàng/hoàn tiền',
  'Bottom sheet Lý do trả hàng/hoàn tiền hiển thị đúng lý do, mô tả và ảnh/video đã gửi','Lý do: Thiếu hàng + 2 ảnh + 1 video',''),
 ('T',None,'Check mã yêu cầu sau khi gửi thành công',
  '1. Gửi yêu cầu thành công\n2. Tại màn Chi tiết hoàn tiền click Xem chi tiết',
  'Hiển thị Mã yêu cầu, click icon copy hiển thị thông báo Sao chép thành công','',''),
 ('T',None,'Check click liên tiếp button Gửi yêu cầu',
  '1. Nhập đầy đủ thông tin\n2. Click nhanh 2 lần liên tiếp button Gửi yêu cầu',
  'Hệ thống chỉ ghi nhận 1 yêu cầu, không tạo trùng 2 yêu cầu cho cùng 1 đơn hàng','',''),
 ('T',None,'Check gửi yêu cầu khi mất kết nối mạng',
  '1. Nhập đầy đủ thông tin\n2. Ngắt kết nối mạng\n3. Click button Gửi yêu cầu',
  'Hệ thống hiển thị thông báo lỗi kết nối, không mất dữ liệu đã nhập, cho phép gửi lại khi có mạng','',''),
 ('T',None,'Check gửi yêu cầu khi API lỗi',
  '1. Giả lập API gửi yêu cầu trả về lỗi 500\n2. Click button Gửi yêu cầu',
  'Hệ thống hiển thị thông báo lỗi thân thiện, không crash app, đơn hàng giữ nguyên trạng thái Đã giao','',''),
 ('T',None,'Check thời gian phản hồi khi gửi yêu cầu',
  '1. Nhập đầy đủ thông tin\n2. Click button Gửi yêu cầu\n3. Đo thời gian phản hồi',
  'Hệ thống phản hồi trong vòng 3 giây, có hiển thị loading trong lúc xử lý','',''),

 ('T','Giới hạn số lần gửi yêu cầu','Check gửi yêu cầu lần 2 sau khi đã huỷ yêu cầu lần 1',
  'ĐK: Đơn hàng đã gửi và huỷ yêu cầu 1 lần, chưa quá 5 ngày kể từ ngày giao thành công\n1. Click vào vùng yêu cầu trả hàng/hoàn tiền\n2. Nhập đầy đủ thông tin\n3. Click Gửi yêu cầu',
  'Gửi yêu cầu thành công lần 2, đơn hàng chuyển sang trạng thái Trả hàng','',''),
 ('T',None,'Check gửi yêu cầu lần 2 sau khi yêu cầu lần 1 bị từ chối',
  'ĐK: Đơn hàng có yêu cầu bị Sàn/Nhà bán từ chối 1 lần\n1. Click vào vùng yêu cầu trả hàng/hoàn tiền\n2. Nhập đầy đủ thông tin\n3. Click Gửi yêu cầu',
  'Gửi yêu cầu thành công lần 2','',''),
 ('T',None,'Check gửi yêu cầu lần 3',
  'ĐK: Đơn hàng đã gửi yêu cầu 2 lần, cả 2 lần đều bị huỷ/từ chối\n1. Check vùng yêu cầu trả hàng/hoàn tiền',
  'Hệ thống hiển thị: Bạn đã hết lượt gửi yêu cầu trả hàng/hoàn tiền và không cho phép gửi yêu cầu lần 3','',''),
 ('T',None,'Check gửi yêu cầu khi đã quá 5 ngày kể từ ngày giao thành công',
  'ĐK: Đơn hàng giao thành công quá 5 ngày\n1. Vào màn Chi tiết đơn hàng\n2. Tìm chức năng gửi yêu cầu trả hàng/hoàn tiền',
  'Không cho phép gửi yêu cầu, đơn hàng đã chuyển sang trạng thái Đã hoàn thành','',''),
 ('T',None,'Check huỷ yêu cầu và trạng thái đơn hàng sau khi huỷ',
  'ĐK: Yêu cầu trả hàng/hoàn tiền đang chờ xử lý\n1. Vào màn Chi tiết hoàn tiền\n2. Click button Huỷ yêu cầu\n3. Click Đồng ý tại popup "Bạn có chắc muốn huỷ Yêu cầu trả hàng/hoàn tiền"',
  'Hệ thống điều hướng màn Chi tiết đơn hàng và hiển thị bottom sheet: Yêu cầu trả hàng/hoàn tiền đã được huỷ thành công, kèm ngày gửi yêu cầu lần đầu, số lượt còn lại và đơn hàng chuyển về trạng thái Đã giao','',''),
 ('T',None,'Check khi click Huỷ tại popup xác nhận huỷ yêu cầu',
  'ĐK: Đang hiển thị popup xác nhận huỷ yêu cầu\n1. Click button Huỷ',
  'Đóng popup, giữ nguyên yêu cầu trả hàng/hoàn tiền','',''),

 ('T','Kiểm thử kỹ thuật','Check dữ liệu hiển thị lấy từ API',
  '1. Mở màn Yêu cầu trả hàng/hoàn tiền\n2. Đối chiếu dữ liệu hiển thị với response API',
  'Thông tin sản phẩm, số tiền hoàn, tài khoản nhận tiền hoàn, email hiển thị đúng dữ liệu từ API','','Bổ sung tên API và tên trường sau khi dev cung cấp'),
 ('T',None,'Check xoay ngang màn hình khi đang nhập yêu cầu',
  '1. Nhập thông tin yêu cầu\n2. Xoay ngang thiết bị',
  'Giao diện hiển thị đúng, không vỡ layout, dữ liệu đã nhập không bị mất','',''),
 ('T',None,'Check giữ dữ liệu khi chuyển app ra nền và quay lại',
  '1. Nhập thông tin yêu cầu\n2. Chuyển app ra nền 30 giây\n3. Quay lại app',
  'Dữ liệu đã nhập được giữ nguyên, màn hình không bị reset','',''),
 ('T',None,'Check hiển thị khi bàn phím bật lên lúc nhập Mô tả',
  '1. Click vào trường Mô tả',
  'Bàn phím bật lên, màn hình tự cuộn để trường Mô tả không bị bàn phím che','',''),
 ('T',None,'Check hiển thị màn hình trên thiết bị màn hình nhỏ',
  '1. Mở màn Yêu cầu trả hàng/hoàn tiền trên thiết bị màn hình nhỏ (VD: iPhone SE)',
  'Hiển thị đầy đủ các thành phần, không vỡ giao diện, cuộn được toàn bộ nội dung','',''),
 ('T',None,'Check hiển thị màn hình trên máy tính bảng',
  '1. Mở màn Yêu cầu trả hàng/hoàn tiền trên tablet/iPad',
  'Hiển thị đầy đủ các thành phần theo design, không vỡ giao diện','',''),
]
